OANS / BTV Advanced Guide
flybywiresim/docs pull request #1020
Opened 2024-10-22 01:50 UTC by flogross89

## Summary

### Location

Discord username (if different from GitHub): floridude

2024-10-22 06:37 UTC, frankkopp requested changes
Thanks for this guide!
Some remarks...

For images we have some standard sizes. 
Full width is 826px. Using this you avoid browser resizing which introduces some blur in most cases. 

Or you could use width 1024px as clicking on the images pops them out and shows them larger. Good for reading details. 

Table with image sizes is pinned in the documentation Discord channel. 

And all images need to optimized to <100kB - I can do this for you at the end. But there are many free png optimizers out there and is an easy step. 

If you also could keep lines <120 char it would be nice. Same as with code long lines are harder to read when using an IDE when autowrap is not turned on (which at least I never have). 
MD does not care if you add a line break in long lines. Will not be visible in the output.

2024-10-22 06:37 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-advanced-guides/oans-btv.md
> +![Runway ahead](../assets/advanced-guides/oans-btv/oans-runway-ahead.png)
```suggestion

![Runway ahead](../assets/advanced-guides/oans-btv/oans-runway-ahead.png)
```

2024-10-22 06:37 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-advanced-guides/oans-btv.md
> +If the aircraft is on ground and ground speed is below 40 knots, OANS continuously checks the aircraft protection volume in front of the aircraft (as widge as the wingspan, foresight of 7 seconds) fo
I would define volume or use another term like "area". 
At least for me volume seems a strange term here and harder to understand. But I'm no native speaker so I might be wrong.

2024-10-22 23:50 UTC, flogross89 commented on docs/pilots-corner/a380x/a380x-advanced-guides/oans-btv.md
> +If the aircraft is on ground and ground speed is below 40 knots, OANS continuously checks the aircraft protection volume in front of the aircraft (as widge as the wingspan, foresight of 7 seconds) fo
Volume is the term which Airbus uses but I'll use area from now. Also more suitable to less technical people

2024-10-23 00:31 UTC, flogross89 commented
> Thanks for this guide! Some remarks...
> 
> For images we have some standard sizes. Full width is 826px. Using this you avoid browser resizing which introduces some blur in most cases.
> 
> Or you could use width 1024px as clicking on the images pops them out and shows them larger. Good for reading details.
> 
> Table with image sizes is pinned in the documentation Discord channel.
> 
> And all images need to optimized to <100kB - I can do this for you at the end. But there are many free png optimizers out there and is an easy step.
> 
> If you also could keep lines <120 char it would be nice. Same as with code long lines are harder to read when using an IDE when autowrap is not turned on (which at least I never have). MD does not care if you add a line break in long lines. Will not be visible in the output.

Thanks for the review! I just commited a new version. 
- I didn't have any image over 826px, but I resized all my images to match your table and compressed them
- I also introduced some line breaks now, amongst other small things

2024-10-23 21:52 UTC, frankkopp approved these changes

2024-10-23 21:53 UTC, frankkopp commented
I will merge this now - any changes we can also make directly in the target branch. 
Brings things together more quickly.

2024-10-23 21:53 UTC, merged