refactor: Restructure of dev-corner
flybywiresim/docs pull request #1040
Opened 2024-11-02 16:34 UTC by frankkopp

## Summary
Restructure of dev-corner
Moving some pages
Adding A380X Paint Kit

Discord username (if different from GitHub): cdr_maverick

2024-11-05 10:05 UTC, Valastiri requested changes

2024-11-05 10:05 UTC, Valastiri commented on docs/dev-corner/dev-guide/contribute.md
> +description: Overview of the FlyByWire Documentation Guide
Change meta?

2024-11-05 10:05 UTC, Valastiri commented on docs/dev-corner/dev-guide/contribute.md
>  Welcome to the A32NX project repository. Thank you for your interest in contributing to the project. Full details and guidelines on how to ensure this project is managed well are included below.
Small change to the copy since we handle both aircraft now in the project? Good to check across the board here in the refactor.
```suggestion
Welcome to the FlyByWire Simulations Aircraft project repository. Thank you for your interest in contributing to the project. Full details and guidelines on how to ensure this project is managed well are included below.
```

2024-11-05 10:05 UTC, Valastiri commented on docs/dev-corner/dev-guide/index.md
>  description: The Development Guide is dedicated to providing information to efficiently contribute to the A32NX project.
Would this also need to be FlyByWire Simulation projects?

2024-11-05 10:05 UTC, Valastiri commented on docs/dev-corner/localization-guide/index.md
> +---
```suggestion
---
title: Localization Guide - Overview
description: Overview of the FlyByWire Localization Guide
search:
    exclude: true
---
```

Stop it being searchable

2024-11-05 10:05 UTC, Valastiri commented
check build

2024-11-07 07:54 UTC, frankkopp commented
check build

2024-11-09 09:06 UTC, Valastiri approved these changes

2024-11-16 16:24 UTC, merged