docs(beginner-guide): starting the aircraft
flybywiresim/docs pull request #123
Opened 2021-07-19 17:37 UTC by scoopscode

Made a new PR after GitHub Desktop acting up

2021-07-21 10:55 UTC, frankkopp commented
General feedback regarding content: 

- I like that you used "we" form - I did as well :)
- Use the FlyByWire checklist in the chapters - e.g. "Before Start"
- Let's assume Ext power and add a info box for when not available - should say turn on APU now 
- Are you sure the parking brake should be OFF (pre-checks)?
- Fire Test: Also look at ECAMs for the fire wqarning messages
- Fire Test before Fuel Pumps
- APU missing (see engine-start-taxi.md prerequisits - these need to match)
- Missing section about lighting (cabin - also displays but you have that already)
- Maybe add to contact ATC to get clearance for the flightplan at the end 
- You could in general also describe the Overhead Scan Method (https://youtu.be/uqKeSO6msDk?t=128)

Let me know if you need help with the images.

2021-07-21 11:00 UTC, frankkopp requested changes

2021-07-21 11:00 UTC, frankkopp commented on docs/beginner-guide/starting-the-aircraft.md
> +To start off, we will begin by doing a few prechecks in all areas of the cockpit to ensure the aircraft is in an normal position before turning on the batteries.
pre-checks

2021-07-21 11:00 UTC, frankkopp commented on docs/beginner-guide/starting-the-aircraft.md
> +Once we our exterior lighting is in the correct state, we can then turn on the **seat belts sign and no smoking sign**.
remove "we"

2021-07-21 11:55 UTC, frankkopp requested changes

2021-07-21 11:55 UTC, frankkopp commented on docs/beginner-guide/starting-the-aircraft.md
> +!!! info "External Power availible"
typo: available

2021-07-21 16:07 UTC, Valastiri requested changes
Additional changes

2021-07-21 16:07 UTC, Valastiri commented on docs/beginner-guide/starting-the-aircraft.md
> +This guide will assist you with starting your aircraft. This guide includes images as well to allow you to understand the locations of all buttons and switches.
```suggestion
This guide will assist you with starting your aircraft. It includes images to assist you with understanding the locations of all buttons and switches.
```
Double use of "this guide" is verbose.

2021-07-21 16:07 UTC, Valastiri commented on docs/beginner-guide/starting-the-aircraft.md
> +    The level of detail in this guide is meant to get a FlyByWire A320neo beginner starting the aircraft correctly.
```suggestion
    The level of detail in this guide is meant to teach a FlyByWire A320neo beginner to start the aircraft correctly.
```

2021-07-21 16:27 UTC, Valastiri commented
> * Are you sure the parking brake should be OFF (pre-checks)?

This was debated in our ground school series. I think we can write this off as SOP and possibly since "MSFS" do this as parking brake ON instead.

2021-07-23 02:54 UTC, Valastiri approved these changes

2021-07-23 14:10 UTC, frankkopp approved these changes

2021-07-23 20:07 UTC, Valastiri commented
Reviewed by Tarek and Shomas.

2021-07-23 20:07 UTC, merged