PFD Briefing Page
flybywiresim/docs pull request #177
Opened 2021-08-23 10:33 UTC by oim1

2021-08-28 19:14 UTC, Valastiri commented
Apologies for the double force push. PR should be clean now.

2021-08-29 07:16 UTC, Valastiri commented
Another fix to bad commit* -force

2021-09-01 11:13 UTC, frankkopp requested changes

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/.pages
> +  - PFD
Would prefer to have lowercase folders and files. We have not been support strict in the past but maybe you could change this to "pfd"

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/altitude-indicator.md
> +
Requires VNAV - correct? 

Add something like:
!!! attention ""
    Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/altitude-indicator.md
> +
.. less than 2500 feet (radio) ==> 2.500ft above ground (radio altitude)

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/artificial-horizon.md
> +This is made up of several different parts that all come together to provide flight guidance to the pilots. It is an oval split in half with brown at the bottom and blue at the top. The black line wh
suggestion - explain colors in terms of blue=sky, brown=ground

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/artificial-horizon.md
> +In flight it will display sideslip. One centimeter of displacement indicates 0.2g. The sideslip index will stop at 0.3g.
is centimeter correct here? one centimeter on the display?

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fifth-column.md
> +---
remove hide navigation

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/first-column.md
> +---
remove hide navigation

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/first-column.md
> +It is displayed with white text surrounded by a white box. It is displayed when at least one thrust lever is in the MCT/FLX detent and the other is at or below this detent.
maybe add MCT=Maximum Continuous Thrust

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/first-column.md
> +
Can you doublecheck if the chime is implemented in fbw? Otherwise please make a note.

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/flags-messages.md
> +
where? a image with numbering would help

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/flags-messages.md
> +This is displayed in amber. It flashes on the top of the glide scale when the aircraft is in the approach phase and when either the final mode is armed/engaged or a non ILS approach has been selected
Doublecheck fbw capability - add note if required

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/flags-messages.md
> +
Capability check and note if required

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/flags-messages.md
> +This is shown when the predictive windshear function has detected a windshear in front of the aircraft.
Capability check and note if required

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fourth-column.md
> +---
remove hide navigation

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fourth-column.md
> +
suggestion: add that this is independent of airport/runway capability.

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fourth-column.md
> +
suggestion: add that this mean one AP active

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fourth-column.md
> +Displayed with white text. Tells the pilot that the aircraft is capable of CAT 3 approaches, with fail operational condition.
suggestion: add that this mean two AP acitve

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fourth-column.md
> +
suggestion: add the MCDU PERF APPR page field name (BARO)

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/fourth-column.md
> +Displayed in white text with blue numbers. Displays the desicion height that is inserted into the APPR PERF page in the MCDU
suggestion: add the MCDU PERF APPR page field name (RADIO)

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/heading-ref.md
> +
suggestion: add a it more explanation - crosswind compensated etc.

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/ils-indicator.md
> +This is a scale that displays the aircraft's deviation from the localiser and glideslope or the deviation from the trajectory defined by the FMGC in a non precision approach.
Capability check and note if required

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/ils-indicator.md
> +- AWY is displayed in white when the aircraft flies over an airways marker beacon or the ILS inner marker.
suggested add: audio signals are played
https://en.wikipedia.org/wiki/Marker_beacon

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/ils-indicator.md
> +## Non Precision Approaches
Capability check and note if required

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +---
remove hide navigation

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +Displayed with green text. Displayed when takeoff or go around mode is engaged.
SRS = Speed Reference System
The SRS mode controls pitch to steer the aircraft along a path in the vertical plan at a speed defined by the SRS guidance law.

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +
do you need the \ here?

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +Displayed with green text. Displayed when Descent mode is engaged and the FMGS target altitude is lower than the current altitude. Altitude Constraints are taken into account.
I would add: "Managed" mode

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +
I would add: "Selected" mode

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/special-message-annunciators.md
> +---
remove hide navigation

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/special-message-annunciators.md
> +
Capability note

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/special-message-annunciators.md
> +Displayed with white text. Displays if the thrust is not reduced when the aircraft is passing the top of descent point, and the aircraft is above the descent profile.
capability note

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/special-message-annunciators.md
> +- In auto speed control and the aircraft enters a speedbrake decelerating segment.
capability note

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/special-message-annunciators.md
> +- The aircraft is less than 30 seconds from the path that is too steep.
Capability note

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/special-message-annunciators.md
> +
Capability note

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/speedtape.md
> +The lower speed margin is the target speed - 20 knots. It is limited to green dot, F, S or VLS speeds, whichever is higher.
Capability check and note

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/speedtape.md
> +---
You could add: Vr (rotate) - blue dot and V2 (magenta triangle)

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/third-column.md
> +---
remove hide navigation

2021-09-01 11:13 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/third-column.md
> +---
suggestion: add a little more explanation what the modes do

2021-09-12 01:17 UTC, oim1 commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +
yes - this is alt star mode and is displayed on the FMA as an asterisk. Without the slash the text would just become bold.

2021-09-12 01:38 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/PFD/second-column.md
> +
Of course. What a dumb question of me. 🙃

2021-09-12 05:09 UTC, oim1 commented on docs/pilots-corner/a32nx-briefing/PFD/artificial-horizon.md
> +In flight it will display sideslip. One centimeter of displacement indicates 0.2g. The sideslip index will stop at 0.3g.
yes - one centimeter on the display
i will add that in.

2021-09-17 21:38 UTC, frankkopp approved these changes

2021-09-22 03:04 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/autobrake-gear.md
> +    - Note: On slippery runway, the predetermined deceleration may not be reached due to antiskid operation. In this case DECEL light will not illuminate. This does not mean that autobrake is not wor
Minor comment: Add "a" between "On" and "slippery runway."

2021-09-22 03:06 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/dcdu.md
> +The DCDU is not implemented in the FlyByWire A32NX. For additional information please refer to the Flight Crew Operating Manual (FCOM) as this system would go beyond this briefing.
Not sure if directing people to the FCOM is the right thing to do since we are not providing them an FCOM to refer to.

2021-09-22 03:09 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/nd.md
> +The Navigation Display (ND) is one the main instruments for the pilots for situational awareness and navigation in flight.
"One the main" doesn't makes sense. Should either revert back to "one of the main" or be changed to "is the main..."

2021-09-22 03:11 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/nd.md
> +    A more in depth description of the Navigation Display is currently developed and will be available in the near future.
"being developed" is correct verbage. Unless it has already been developed, then you can just remove "is currently developed and"

2021-09-22 03:12 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/nd.md
> +These pushbutton are located on either side of the ECAM. Each pushbutton controls the onside terrain display.
There is more than one push button. ("Each push button...")

2021-09-22 03:13 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/upper-ecam.md
> +    A more in depth description of the ECAM is currently developed and will be available in the near future.
Same comment as before. "is currently developed" is not proper verbiage.

2021-09-22 03:15 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/glareshield/efis_control.md
> +- Note : If there are any failures, the display defaults to ROSE NA V mode and 80NM range
What is "ROSE NA V mode?"

2021-09-22 03:17 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/flight-deck/glareshield/fcu.md
> +The Flight Control Unit (FCU) provides short-term interface between the Flight Management and Guidance Computer (FMGC) and crew for:
Suggest "provides a short term interface..." (I also liked the previous "the flight crew" instead of "crew").

2021-09-22 06:39 UTC, frankkopp commented
@donstim thanks for the review. I will make the changes for this review in this PR: https://github.com/flybywiresim/docs/pull/212
You went over the flight-deck pages which are not part of this PR - this one is dedicated to the PFD section.

2021-09-22 06:45 UTC, frankkopp commented
@donstim I see now that this PR is also not using the latest flight-deck pages and most of your comments are already addressed in the published version. This is because we did not rebase this PR with the latest version.

Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

As written above I'm collection fixes to the flight-deck pages in this PR: https://github.com/flybywiresim/docs/pull/212

2021-09-22 06:45 UTC, BlueberryKing reviewed
Great work! I just have some small suggestions.

2021-09-22 06:45 UTC, BlueberryKing commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This is displayed in green and is shown if the mach number reaches above 0.5. It is displayed underneath the scale.
```suggestion
This is displayed in green and is shown if the Mach number reaches above 0.5. It is displayed underneath the scale.
```

2021-09-22 06:45 UTC, BlueberryKing commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This is displayed in green and is shown if the mach number reaches above 0.5. It is displayed underneath the scale.
The Mach number is named after the Austrian physicist Ernst Mach, so we should capitalize it.

2021-09-22 06:45 UTC, BlueberryKing commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This speed is V~MO~~ (maximum operating speed) + 6 knots or MMO (maximum mach speed) + 0.01
```suggestion
This speed is V~MO~~ (maximum operating speed) + 6 knots or MMO (maximum Mach speed) + 0.01
```

2021-09-22 06:45 UTC, BlueberryKing commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +# Actual Airspeed Reference Line and Scale
What are you referring to here when you say "*Actual* Airspeed Reference Line and Scale"? I might be confusing something, but I think we should call this "*Indicated* Airspeed Reference Line and Scale", since it could be mistaken for a true airspeed indication instead.

2021-09-22 06:48 UTC, oim1 commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +# Actual Airspeed Reference Line and Scale
That is what the fcom called it. I can change it to indicated if preferred

2021-09-22 06:52 UTC, BlueberryKing commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +# Actual Airspeed Reference Line and Scale
Ah, interesting. If the FCOM says so it's probably best to keep it this way. I don't really know why they would call it that though. 😆

2021-09-22 06:57 UTC, oim1 commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +# Actual Airspeed Reference Line and Scale
yeah it's quite odd

2021-09-22 06:59 UTC, donstim commented
> @donstim thanks for the review. I will make the changes for this review in this PR: #212
> You went over the flight-deck pages which are not part of this PR - this one is dedicated to the PFD section.

Sorry about that. I just started going through the files and didn't pay proper attention to what this PR was about.  Disregard!

2021-09-22 07:02 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/autobrake-gear.md
> +    - Note: On slippery runway, the predetermined deceleration may not be reached due to antiskid operation. In this case DECEL light will not illuminate. This does not mean that autobrake is not wor
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:02 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/dcdu.md
> +The DCDU is not implemented in the FlyByWire A32NX. For additional information please refer to the Flight Crew Operating Manual (FCOM) as this system would go beyond this briefing.
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:04 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/nd.md
> +    A more in depth description of the Navigation Display is currently developed and will be available in the near future.
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:04 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/nd.md
> +The Navigation Display (ND) is one the main instruments for the pilots for situational awareness and navigation in flight.
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:04 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/nd.md
> +These pushbutton are located on either side of the ECAM. Each pushbutton controls the onside terrain display.
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:04 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/front/upper-ecam.md
> +    A more in depth description of the ECAM is currently developed and will be available in the near future.
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:06 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/glareshield/efis_control.md
> +- Note : If there are any failures, the display defaults to ROSE NA V mode and 80NM range
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:07 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/flight-deck/glareshield/fcu.md
> +The Flight Control Unit (FCU) provides short-term interface between the Flight Management and Guidance Computer (FMGC) and crew for:
Unfortunately this was an old version of the flight-deck pages (no rebased for t his PR).
Find the published flight-deck pages here: https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/

2021-09-22 07:11 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This speed is V~MO~~ (maximum operating speed) + 6 knots or MMO (maximum mach speed) + 0.01
Capitalize Mach

2021-09-22 07:17 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +# Actual Airspeed Reference Line and Scale
I think there is a small misunderstanding here. 
See the FCOM reference below. The whole thing is called Airspeed. Only the static line is called "Actual Airspeed Reference Line and Scale"
I will change headline to Airspeed.

![image](https://user-images.githubusercontent.com/16833201/134299464-45e8fd25-da4d-423e-b96b-9082e527898d.png)

2021-09-22 07:20 UTC, oim1 commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +# Actual Airspeed Reference Line and Scale
Ah right - thanks!

2021-09-22 07:23 UTC, frankkopp commented
> Great work! I just have some small suggestions.

Thanks for the review :)

2021-09-23 22:46 UTC, merged

2021-10-08 19:27 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This speed is V~MO~~ (maximum operating speed) + 6 knots or MMO (maximum Mach speed) + 0.01
Simple typos.  Looks like one too many ~ for VMO (for subscript) and missing subscript entirely for MMO.

2021-10-08 19:27 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +The upper speed is equal to the target speed + 20 knots, limited to V~MAX~, V~MO~ - 3 knots or MMO - 0.006, whichever is the lowest.
Missing subscript for MMO.

2021-10-08 19:27 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +- V~MO~ or the corresponding to MMO
Missing subscript for MMO.

2021-10-08 19:27 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +It is sown as blue numeral one (1) at a speed that the pilot inserted manually in the takeoff performance page in the MCDU. When it is off the scale, the upper part of the scale shows the speed in nu
Typo. Missing h in "shown" (3rd word in the first sentence.)

2021-10-08 19:27 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This is a magenta triangle on the right side of the speedtape. It displays the V~2~ speed which has been set in the TAKE OFF PERF page of the MCDU. This is the speed the aircraft needs to maintain at
I suggest a bit of a modification as this implies (to me anyway) that it would be acceptable to allow the speed to decrease to V2 if, for example, you had an engine failure at  V2+10.  This is not the case. In that case, you would maintain V2+10. I suggest, "This is the speed you should reach by the time you attain a height of 35 feet after takeoff with an engine failure and maintain until reaching the acceleration altitude."

2021-10-10 22:26 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +- V~MO~ or the corresponding to MMO
No subscript without V

2021-10-10 22:26 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +The upper speed is equal to the target speed + 20 knots, limited to V~MAX~, V~MO~ - 3 knots or MMO - 0.006, whichever is the lowest.
No subscript without V

2021-10-10 22:26 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This speed is V~MO~~ (maximum operating speed) + 6 knots or MMO (maximum Mach speed) + 0.01
No subscript without V

2021-10-10 22:27 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This is a magenta triangle on the right side of the speedtape. It displays the V~2~ speed which has been set in the TAKE OFF PERF page of the MCDU. This is the speed the aircraft needs to maintain at
Reference for V2+10?

FCOM says:
![image](https://user-images.githubusercontent.com/16833201/136714899-479a1afb-a28b-4a6b-b71b-704cae846ed0.png)

2021-10-11 00:23 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This is a magenta triangle on the right side of the speedtape. It displays the V~2~ speed which has been set in the TAKE OFF PERF page of the MCDU. This is the speed the aircraft needs to maintain at
From the FCOM:
![Screenshot (1246)_LI](https://user-images.githubusercontent.com/70166617/136717198-36bcd240-af06-480b-97f7-adc9d4eb066c.jpg)

 And from the FCTM:
![Screenshot (1247)_LI](https://user-images.githubusercontent.com/70166617/136717214-34227b7f-43de-44c8-9564-3c646d83c2ca.jpg)

My use of V2+10 was just an example, although highly relevant since it is the target all-engines-operating initial climb speed. But the speed could have been, say V2+5 for example, at the time of the engine failure and the pilot should then maintain V2+5. V2 remains an absolute minimum, if, for example, the situation is resulting in some speed decay, but it should not be a speed the pilot should purposefully target if already at a higher speed.

The reason for this came from the 1979 DC-10 accident in Chicago. In that accident, involving an engine failure (actually an engine separation), the crew reduced speed to V2 from a higher speed. Due to unknown wing damage causing a slat retraction on the left wing, the left wing stalled, causing an uncontrollable roll and crash. Since that time, the procedures for all airplanes (not just the A320) for an engine failure just after takeoff is to maintain the current speed (up to a limit like V2+15) and not reduce back to V2 (which is the speed that would be flown if the engine failure had occurred before V2 is reached).

From the accident report:
![Screenshot (1251)](https://user-images.githubusercontent.com/70166617/136718077-fbf34cf0-1d17-44e0-ade5-63453aee2569.png)