Update landing.md
flybywiresim/docs pull request #178
Opened 2021-08-23 13:08 UTC by FreshDave29

Minima have nothing to do with ATC landing clearance. You do not have to go-around for not receiving a landing clearance at minimums! Minimum is only applicable for runway visibility, although some airlines may have put this in their SOPs.

2021-08-23 14:05 UTC, Valastiri requested changes
This seems reasonable and makes a lot of sense in my mind. It may have slipped our pilot review. 

Just wanted to get some clarification here as a lot of the guide can be SOP-dependent. While I am no pilot, some SOP / checklist / procedures may require PF/PM to state `continue` verbally past minimums. If situations such as these would a landing transition to a go-around? 

If the situations really differ as such a small disclaimer would be prudent to add stating SOP-dependent as used in other places in the guide.

References welcome and thanks for contributing!

2021-08-23 14:05 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/landing.md
> +We **MUST** get landing clearance from ATC before we actually are allowed to land. Without landing clearance we must do a go-around (not part of this beginner guide) before touching the runway. Usual
```suggestion
We **MUST** get landing clearance from ATC before we actually are allowed to land. Without landing clearance we must do a go-around (not part of this beginner guide) before touching the runway. Usually ATC will have given us clearance at this point. Late clearance is rare and usually communicated to us beforehand. We can basically flare above the runway until we get a clearance, but we usually aim for the touch-down zone. Otherwise, we perform a go-around as this leads to long landings and potential runway overruns.
```
Found a typo in the original copy (thanks!)

Also suggestion to split the run-on sentence at the end.

2021-08-23 14:19 UTC, frankkopp commented
> Minima have nothing to do with ATC landing clearance. You do not have to go-around for not receiving a landing clearance at minimums! Minimum is only applicable for runway visibility, although some airlines may have put this in their SOPs.

@FreshDave29 You got a Discord ID to contact?

2021-08-23 14:36 UTC, FreshDave29 commented
References: https://www.aerocomsystem.com/e-system/amcgmText/list.html?show_code=CAT.OP.MPA.110&part_code=CAT&limit_date=2017/02/26&amcgm_id=998&part_amnd_id=

CAT.OP.MPA.110 with corresponding AMC1 through 11 - which describes the operational implications of aerodrome minima to operators. There is nowhere mentioned that an ATC landing clearance is required, although SOP may dictate something like OCA in order to be on the safe side.
But a major airline would not be able to land on busy aerodromes when going-around at minima (e.g. non-precision approaches with corresponding high MAPt).


Discord: David L.#4587

2021-08-23 15:56 UTC, Flurus commented
Hi Team, 

_Landing Minima are established to provide a safe escape route in case of a missing visual reference!_

Industry professional here, i've done a little research on this. The understanding that an approach must be discontinued after MDA/H when no landing clearance has been received is not correct.

In EASA Air Ops Part CAT are two main items that implement the rules for Aerodrome Operating Minima and the item that refulates whether an approach shall be commenced and continued.

The first one is CAT.OP.MPA.110, and the corresponding AMC (Acceptable Means of Compliance). https://www.easa.europa.eu/document-library/easy-access-rules/online-publications/easy-access-rules-air-operations?page=37#_Toc256000856
This rule states how to establish an aerodrome operating minima. All references for this are mainly based on one thing: visual reference (and aircraft performance). Aerodrome Operating minima are there to ensure that an aircraft without visual reference is safely able to discontinue the approach, taking into account all kinds of things (I will not reiterate what the rule says, see link :) )


The second one is CAT.OP.MPA.305 Commencement and continuation of approach
Again, there is the rule and the AMC. The rule says: _An approach may be continued below DA/H or MDA/H, and the landing may be completed provided that the visual reference adequate for the type of approach operation and for the intended runway is established at the DA/H or MDA/H and is maintained._ 
![unknown](https://user-images.githubusercontent.com/89405977/130478013-73d528a7-fa27-47b1-93c1-23768d8c6d35.png)

The visual reference adequte for the approach is the defined in the AMC1.CAT.OP.MPA.305(e) 
![unknown](https://user-images.githubusercontent.com/89405977/130478037-7d36d952-062c-46e2-860b-90f8ec415c52.png)
There is, again, no statement of the necessity of a landing clearance from Air traffic control. 

Saying all of that, and due to the absence of anything related to a landing clearance while talking about a minimum, it is clear that the intention of the ruling body (EU Commission) is clearly **not** to couple the continuation of an Approach to the existence of a landing clearance. **If that would be the case it would be clearly stated otherwise.** 

And to proof it further wrong: i.e. Airport of Innsbruck RNP Y 08: Minima is at 5193' AGL, that means almost 15 miles out. If everyone would fly a missed approach at that point due to a missing landing clearance that would be pure madness.



Best regards

2021-08-23 22:18 UTC, frankkopp requested changes
Suggestion: 

We **MUST** get landing clearance from ATC before we actually are allowed to land. Without landing clearance we must do a go-around (not part of this beginner guide) before touching the runway. Usually ATC will have given us clearance at this point. Late clearance is rare and communicated to us beforehand. 

This says it all - "do not touch runway". Our pilots have a hard time with this one as it never happens in real life. They would however not land and go-around shortly before flare the latest.

Does that work for you?

2021-08-24 09:48 UTC, frankkopp approved these changes
Changed as discussed with pilots.

2021-08-24 15:08 UTC, Valastiri approved these changes

2021-08-24 16:00 UTC, Valastiri commented
Fun discussion on minima! Thanks for all the clarifications.

@FreshDave29 If you are happy with the edit to your PR, this LGTM.

2021-08-25 13:25 UTC, FreshDave29 commented
Thanks for all involved, PR can be further processed :)

2021-08-25 13:47 UTC, merged