docs: A32NX Briefing - MCDU
flybywiresim/docs pull request #191
Opened 2021-09-02 17:03 UTC by frankkopp

Overview and reference for the A320neo MCDU

Sections and pages:

- [ ] MCDU Overview
- [ ] MCDU Setup Procedure
- Pages:
    - [ ] DIR TO
    - [ ] PROG
    - [ ] PERF
    - [ ] INIT
    - [ ] DATA
    - [ ] F-PLN
    - [ ] RAD NAV
    - [ ] FUEL PRED
    - [ ] SEC F-PLN
    - [ ] ATC COMM
    - [ ] MCDU MENU
    - [ ] AIR PORT

2021-11-05 23:26 UTC, frankkopp commented
Changed target branch to primary.

2022-09-11 19:15 UTC, pdellaert reviewed
This is an amazing PR with great information (I learned a bunch while reviewing)

My only remarks are some spelling fixes, few clarifications and some formatting. The one thing I noticed is commas in places where I believe they are not needed. I could be very wrong on that, of course, so ignore if my English grammar is bad in that. 

Cool update :)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/index.md
> +The MCDU is the main interface for them flight crew to the FMGC (Flight Management Guidance Computer). There are two
```suggestion
The Multipurpose Control and Display Unit (MCDU) is the main interface for the flight crew to interact with the Flight Management Guidance Computer (FMGC). There are two 
```
+ First use of the acronym in this large section: Suggest to expand fully and clarify the acronym
+ fix a typo 
+ suggestion to clear language
+ trying to standardize of "Full name (acronym)" model for the first mention of an acronym.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/index.md
> +After entry or selection of the flight plan and other required performance data into the MCDU, the FMGS generates
```suggestion
After entry or selection of the flight plan and other required performance data into the MCDU, the Flight Management Guidance System (FMGS) generates 
```
Suggests to use full name for the first reference in this broader documentation section as a clarification.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/index.md
> +See the [MCDU Setup Procedure](../../beginner-guide/preparing-mcdu.md) in our
```suggestion
Also see the [MCDU Setup Procedure](../../beginner-guide/preparing-mcdu.md) in our 
```
Minor suggestion to clarify this is additional information

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +The MCDU (Multipurpose Control and Display Unit) has 14 lines and 24 characters in each line.
```suggestion
The MCDU has 14 lines and 24 characters in each line.
```
Could be stripped out as the Overview/Index already has the expanded acronym. If repeated, maybe it's better to do : `Multipurpose Control and Display Unit (MCDU)`

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +      “first out” message queue that holds maximum of 5 messages. Type 2 messages are displayed in the scratchpad
```suggestion
      “first out” message queue that holds a maximum of 5 messages. Type 2 messages are displayed in the scratchpad 
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +White messages are advisory only.
```suggestion
White messages are advisory only and do not require an action from the flight crew. These messages can be cleared with the CLR key.
```
Had users in support get confused by this, so suggest to call it out specifically no action is required.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +The MCDU has two columns of data (left and right) with 6 rows of title and data field on each side. The data is
```suggestion
The MCDU has two columns of data (left and right) with 6 rows of title and data fields on each side. The data is 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +either a stored value, computed value or a value entered by the crew.
```suggestion
either a stored value, a computed value or a value entered by the crew.
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +These LSK are used to move data from the scratchpad to the corresponding line, or to call specific function pages
```suggestion
The LSK next to the line is used to move data from the scratchpad to that corresponding line, or to call specific function pages 
```
Not sure if this makes more sense, but I feel it does

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +- clearing of data fields by first pressing CLR on an empty Scratchpad so that CLR appears in the Scratchpad and the
```suggestion
- clearing of data fields by first pressing CLR on an empty Scratchpad so that CLR appears in the Scratchpad and then 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +  pressing the LSK next to the data field which shall be erased.
```suggestion
  pressing the LSK next to the data field which needs to be erased.
```
Minor suggestion, feels like it makes more sense.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +Allows the aircraft to overfly a selected waypoint.
What exactly does "overly a selected waypoint" mean? How does it affect the flight plan/path? 
(I don't know myself, which is why I think it would be good to explain the outcome of the button a bit more with an explanation of the behavior. It's not explained anywhere in our documentation.)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +Calls up the flight plan page that contains the next airport along the current flight plan. Successive pushes on the
Would it be clearer to use "Destination" airport (if that is correct terminology and not wrong information)?

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +- Primary Flight Plan: <span style="color: #00ff00">Green</span> waypoints, white legs
```suggestion
- Primary Flight Plan: <span style="color: #00ff00">green</span> waypoints, white legs 
```
Consistency with other lines

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/dir.md
> +The aircraft immediately starts turing towards the waypoints.
```suggestion
The aircraft immediately starts turning towards the waypoint.
```
Minor corrections/suggestions

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/dir.md
> +    Below is a quick explanation of what this feature entails.
```suggestion
    Below is a quick explanation of what this functionality entails. It is not yet implemented in the FlyByWire A32NX.
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/dir.md
> +    Below is a quick explanation of what this feature entails.
```suggestion
    Below is a quick explanation of what this functionality entails. It is not yet implemented in the FlyByWire A32NX.
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/prog.md
> +Value cannot be lower than the altitude selected in the FCU.
```suggestion
The value cannot be lower than the altitude selected in the FCU.
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/prog.md
> +In descent or approach this shows dashes.
```suggestion
In the descent or approach phase this field shows dashes.
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/prog.md
> +GPS PRIMARY is displayed, when the FMS navigation mode is GPS PRIMARY. When GPS PRIMARY is not available, or
```suggestion
GPS PRIMARY is displayed when the FMS navigation mode is GPS PRIMARY. When GPS PRIMARY is not available, or 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +- ACTIVATE APPR PHASE (&L):
```suggestion
- ACTIVATE APPR PHASE (6L):
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +- NEXT PHASE (&R):
```suggestion
- NEXT PHASE (6R):
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +      !!! note ""
```suggestion

      !!! note ""
```
Think a newline needs to be added to make this show up as a proper note. (it doesn't in the preview build page)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        In the FlyByWire A32NX you can click on the LSK next to V1, VR, V2, to let the aircraft calculate the
```suggestion
        In the FlyByWire A32NX you can click on the LSK next to V1, VR and V2, to let the aircraft calculate the 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - The pilot can modify this altitude: The minimum is 400 ft above the runway elevation.
```suggestion

    - The pilot can modify this altitude: The minimum is 400 ft above the runway elevation.
```
A newline is needed to make sure this is not part of the Tip box

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +                Can be set in the flyPad settings.
```suggestion
                The default value can be changed in the EFB Aircraft Options settings page.
```
Minor suggestion to clarify in a bit more detail where to find this setting.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - Passing acceleration altitude triggers the climb phase.
```suggestion
    - The acceleration altitude is the altitude at which the climb phase is activated and the target speed is changed to the initial climb speed.
```
Suggestion to bring it to the same format as the THR RED explanation.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - The target speed changes to the initial climb speed.
```suggestion
```
Suggestion to remove if the line above is changed as per suggestion.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - The default value is 1.500 ft above runway elevation.
```suggestion
    - The default value is 1.500 ft above runway elevation.
    
    !!! tip
        The default value can be changed in the EFB Aircraft Options settings page.

```
Suggestion to add the same tip as THR RED.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        - Cannot be modified directly in this field, but with the SPD/MACH selection knob on the FCU.
```suggestion
        - Cannot be modified directly in this field, but it will update when the SPD/MACH is changed using the selection knob on the FCU.
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +            Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.
```suggestion
- Blank or EXPEDITE (5L):
    - Blank as long as the aircraft is in preflight.
    - Displays this legend when the takeoff or climb phase is active.
    - The flight crew cannot engage EXPEDITE from this field. It indicates the time and distance required to 
      reach the altitude displayed in the 2R field, in case of climb at green dot.

    !!! attention ""
        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.

- EO CLR (1R):
    - The system displays the EO CLR prompt in case of engine out in climb.

    !!! attention ""
        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.

- PRED TO... (2R):
    - This field displays the target altitude for the predictions shown in 3R, 4R, or 5L. It defaults to FCU 
      altitude, but the pilot can modify it to any altitude below CRZ FL.

    !!! attention ""
        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.

- (3R) (4R) (5R):
    - These fields show time and distance predictions for the target altitude selected in (2R), computed for the 
      current vertical mode and speed mode (MANAGED, SELECTED). These fields are displayed only while the 
      takeoff, or climb phase is active.

    !!! attention ""
        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.
```
Indented too much, this corrects it.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +- TIME/UTC DES EFOB (1R)
```suggestion
- TIME/UTC DES EFOB (1M/1R)
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +- TIME/UTC DES EFOB
```suggestion
- TIME/UTC DES EFOB (1M/1R)
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        - Blue brackets are displayed
Is this correct? In FBW A32NX MCDU, it always shows up as orange boxes for me (currently in flight, 1900NM from my destination, and it's orange boxes)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        - Blue brackets are displayed
Same remark as QNH: orange boxes even when 1900NM out in my case

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - Used by the FMGS to refine computation of the descent profile [ISA model).
```suggestion
    - Used by the FMGS to refine computation of the descent profile (ISA model).
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - The Cabin Pressure Controller [CPC) uses QNH to compute the cabin pressurization. Therefore, a wrong QNH
```suggestion
    - The Cabin Pressure Controller (CPC) uses QNH to compute the cabin pressurization. Therefore, a wrong QNH 
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - Transmitted to the vertical revision and flight plan B pages [which display wind direction as true, not magnetic).
```suggestion
    - Transmitted to the vertical revision and flight plan B pages (which display wind direction as true, not magnetic).
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - Shows transition altitude taken from the navigational data base [small font) or entered by the flight crew [large
```suggestion
    - Shows transition altitude taken from the navigational data base (small font) or entered by the flight crew (large
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        - VAPP = VLS + 1/3 of the headwind components [limited to VLS + 5 as a minimum and VLS + 15 as a maximum).
```suggestion
        - VAPP = VLS + 1/3 of the headwind components (limited to VLS + 5 as a minimum and VLS + 15 as a maximum).
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +            VLS = 1.23 VS1G (Stall Speed) of the selected landing configuration [full or 3).
```suggestion
            VLS = 1.23 VS1G (Stall Speed) of the selected landing configuration (full or 3).
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +- FINAL (1R)
```suggestion
- FINAL (1M)
```
Minor correction

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - The Minimum Descent Height (MDH) with associated brackets, if the FCU setting is QFE
```suggestion
    - The Minimum Decision Altitude (MDA) with associated brackets, or
    - The Minimum Decision Height (MDH) with associated brackets, if the FCU setting is QFE
```

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +## APPROACH
On APPROACH: Do the O, S & F speeds need to be explained (2M, 3M, 4M)?

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +    - When not entered, the system will not provide predictions, while the aircraft is on the ground.
```suggestion
    - When not entered, the system will not provide predictions,while the aircraft is on the ground.
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +    - ICAO codes for city of origin and destination must be entered here.
```suggestion
    - ICAO codes for airport of origin and destination must be entered here.
```
Think ICAO codes are not strictly related to cities but to airports.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +    - Shown, if no flight plan is entered or the origin/destination pair is changed.
```suggestion
    - Shown if no flight plan is entered or the origin/destination information is changed.
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +- TROPO (6R):
Does it make sense to add information on what the Tropopause altitude is?

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +- BLOCK (2R)
Should it be clarified what BLOCK fuel is? How to determine the number (total fuel required, or total fuel on board before departure?)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/data.md
> +    This section will not cover all DATA INDEX pages as most are not useful in a simulation anyway or not
```suggestion
    This section will not cover all DATA INDEX pages as most are not useful in a simulation or not 
```
Minor suggestion to remove unnecessary commentary style language

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/data.md
> +- FMGC 1 (1L)
```suggestion
- FMS 1 (1L)
```
Minor suggestion based on actual display

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/data.md
> +- FMGC 2 (2L)
```suggestion
- FMS 2 (2L)
```
Minor suggestion based on actual display

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/data.md
> +    -Used this to calculate predictions.
```suggestion
    - Used to calculate predictions.
```
Minor correction to list otherwise it doesn't show up properly. Suggestion on language.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/data.md
> +        - The new IDLE and/or PERF factors are displayed in large blue font.
```suggestion
    - When it is necessary to modify the IDLE or the PERF factor:
        - ENTER the change code in the CHG CODE field (5L).
        - Default value for the code is "ARM" but can be modified in the Airline Modifiable Information (AMI) file.
        - With a valid code, the IDLE and PERF factors are displayed in blue.
        - ENTER the new IDLE and/or PERF factor(s) in the scratchpad.
        - PRESS the (6L) key to insert the new IDLE and/or PERF factor.
        - The new IDLE and/or PERF factors are displayed in large blue font.
```
Wrong dashes used (UTF8 copy/paste issue is my guess), causing bad rendering as the lines are not recognized as list items.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/data.md
> +Pilots can add a 5th airport.
```suggestion
Automatically loads the closest 4 airports from the current position. The pilots can add a 5th airport with a manual entry.
```
Language suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +may only be entered from the RTA page.
```suggestion
!!! note
    SPD and ALT CSTR may either be entered on the VERT REV page or directly on the F-PLN A page, whereas TIME CSTR 
    may only be entered from the RTA page.
```
Suggestion to make this an actual note.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - Only available on departure or alternate departure airport.
```suggestion
    - Only available on the current FROM waypoint (first waypoint when opening the F-PLN page). 
```
Fix info is available at any time, but only for the current FROM waypoint (maybe there's better language to explain that than the suggestion).

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - Only available on origin or alternate airport.
Also on Alternate airport? Thought departure was only on origin?

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - Used for selecting the arrival runway and procedures (STAR, APPR, TRANS, etc.)
```suggestion
    - Used for selecting the arrival runway and procedures (STAR, APPR, TRANS, etc.)
    - Only available on the departure airport.
```
Suggestion to add the clarification.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +       Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.
```suggestion
    !!! attention ""
        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.
```
Needs corrected spacing to properly render.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +origins is the revise waypoint. To enter the Lateral Revision page the pilots pushes the LSK right of the waypoint
```suggestion
origins is the revise waypoint. To enter the Vertical Revision page the pilots pushes the LSK right of the waypoint 
```
Correction for the correct page name

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +-
```suggestion

```
Unnecessary list item, does need to be a newline for proper rendering.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - CLB SDP is show in CLIMB phase, DES SPD in DES phase
```suggestion
    - CLB SDP is shown in CLIMB phase, DES SPD in DES phase
```
Minor correction

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - The speed limit is either a system default, a NAV database airport default, or a pilot--entry.
```suggestion
    - The speed limit is either a system default, a NAV database airport default, or a pilot entry.
```
Minor correction

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +-
```suggestion

```
Unnecessary list item

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +        - A magenta * indicates the constraint will be met.
```suggestion
    - A yellow * indicates the constraint will be missed.
    - A magenta * indicates the constraint will be met.
```
Should not be extra indented, I think?

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - Only show once a cruise alt has been entered.
```suggestion
    - Only shown once a cruise alt has been entered.
```
Minor correction

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.
I do get these *CLB and *DES in my MCDU in experimental, is this only in experimental? In which case the attention box should reflect this.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    of descent not yet defined).
```suggestion
    of descent are not yet defined).
```
Minor suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +The RWY, SIDS and TRANS (if any) pages are available.
```suggestion
The RWY, SIDS and TRANS will be shown if any pages are available.
```
I'm not sure what is meant by the original sentence, so my suggestion is based on limited information.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +- RWY/SIDs (2L)
```suggestion
- RWY/SIDs (2L to 5L)
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - When a runway is selected, a temporary is created or modified, and the DEPARTURE page 2 for SID selection is
```suggestion
    - When a runway is selected, a temporary flight plan is created or modified, and the DEPARTURE page 2 for SID selection is
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - When a TRANS is selected, a temporary is created or updated (if one already exists).
```suggestion
    - When a TRANS is selected, a temporary flight plan is created or updated (if one already exists).
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +- 3R zo 5R
```suggestion
- 3R to 5R
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +        - The indent and the frequency of the NAVAID specified for the approach, or
```suggestion
        - The ident and the frequency of the NAVAID specified for the approach, or
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    (white font), but can be inserted into the CLIMB WIND page by using the 6R key and modified accordingly.
```suggestion
    - This key calls up the history wind page and is only displayed in the preflight phase. It cannot be modified 
      (white font), but can be inserted into the CLIMB WIND page by using the 6R key and modified accordingly.
```
Indentation fix to show proper rendering.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/rad-nav.md
> +    - It is autotuned, if the ILS is associated with the departure runway, or if the flight plan shows an ILS
```suggestion
    - It is autotuned if the ILS is associated with the departure runway, or if the flight plan shows an ILS 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/fuel-pred.md
> +    All fields, are dashed before engines are started.
```suggestion
    All fields are dashed before engines are started.
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/fuel-pred.md
> +    - The EFOB at destination will turn to amber, if it becomes less than the MIN DEST FOB value.
```suggestion
    - The EFOB at destination will turn to amber if it becomes less than the MIN DEST FOB value.
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/fuel-pred.md
> +    - It may be equal to 0.0, if such is the policy of the operator. The crew can either enter a fuel quantity or a
```suggestion
    - It may be equal to 0.0 if such is the policy of the operator. The crew can either enter a fuel quantity or a 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/fuel-pred.md
> +    - If at engine start, no ZFW or ZFWCG values have been entered, amber boxes are displayed in the
```suggestion
    - If at engine start no ZFW or ZFWCG values have been entered, amber boxes are displayed in the 
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/sec-f-plan.md
> +and the secondary flight plan page. The secondary flight plan is generally used to prepare a diversion
```suggestion
and the secondary flight plan page. The secondary flight plan is generally used to prepare a diversion,
```
Minor correction/suggestion (comma)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/mcdu-menu.md
> +# Description
```suggestion
## Description
```
Wrong header type causes table of content to be missing.

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/mcdu-menu.md
> +    - COMM MENU
Should there be at least a on-liner description of what this is supposed to be? (same for AIDS and CFDS; and for other INOP items that have no description, like in the AOC menu and others)

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/mcdu-menu.md
> +- FREE TEXT (1R) --> See [Free Text Guide](../../../fbw-a32nx/feature-guides/freetext.md)
```suggestion
- INIT/PRES (1L) --> See [INIT/PRES](#initpres-page)
- WX REQUEST (2L) --> See [WX REQUEST](#wx-request-page)
- ATIS (3L) --> See [ATIS](#atis-page)
- FREE TEXT (1R) --> See [Free Text Guide](../../../fbw-a32nx/feature-guides/freetext.md) 
```
Adding text for consistency between items

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/messages.md
> +- They are suppressed, if correct data is entered or when they no longer apply
```suggestion
- They are suppressed if correct data is entered or when they no longer apply
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/messages.md
> +| DEST/ALTN MISMATCH                                                                   | I/W      | The pilot attempts to enter an alternate CO RTE (which starts at an origin that is not the primary
```suggestion
| DEST/ALTN MISMATCH                                                                   | I/W      | The pilot attempts to enter an alternate CO RTE which starts at an origin that is not the primary flight plan destination.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/messages.md
> +| <span style="color: #ff9a00">RWY/LS MISMATCH</span>                                  | II/A     | <br/>- During climb, cruise, (ILS or GLS) descent approach, or go-around, the LS frequency entered
```suggestion
| <span style="color: #ff9a00">RWY/LS MISMATCH</span>                                  | II/A     | - During climb, cruise, (ILS or GLS) descent approach, or go-around, the LS frequency entered on the RAD NAV page does not match the LS associated with the destination runway.<br/>- During preflight or takeoff, the LS frequency entered on the RAD NAV page does not match the LS associated with the takeoff runway.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/messages.md
> +| SENSOR IS INVALID                                                                    | I/W      | <br/>- The pilot has selected FF or FQ, or FF + FQ, or FQ + FF on the FUEL PRED page and the sole s
```suggestion
| SENSOR IS INVALID                                                                    | I/W      | - The pilot has selected FF or FQ, or FF + FQ, or FQ + FF on the FUEL PRED page and the sole sensor or both of the selected sensors are invalid, or<br/>- The flight crew has entered fuel on board only, and the FF sensor is invalid.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
```
Minor correction/suggestion

2022-09-11 19:15 UTC, pdellaert commented on docs/pilots-corner/a32nx-briefing/mcdu/messages.md
> +| <span style="color: #ff9a00">SPECIF VOR-D UNAVAIL <br/>(also displayed on ND)</span> | II/A     | <br/>- The VOR, VOR-DME, or VORTAC to be autotuned (specified for an RNAV or VOR approach) has prev
```suggestion
| <span style="color: #ff9a00">SPECIF VOR-D UNAVAIL <br/>(also displayed on ND)</span> | II/A     | - The VOR, VOR-DME, or VORTAC to be autotuned (specified for an RNAV or VOR approach) has previously been deselected by the flight crew, or<br/>- The bearing, the frequency, or the IDENT of the VOR (or VORDME or VORTAC) to be autotuned is invalid.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
```
Minor correction/suggestion

2022-09-12 13:03 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/interface.md
> +Allows the aircraft to overfly a selected waypoint.
Good idea - I thought it is self explaining but maybe not.

2022-09-12 13:39 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        - Blue brackets are displayed
Haven't checked - this is what the FCOM says. So might be implemnted incorrectly :) I can make a note

2022-09-12 13:48 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +    - The Minimum Descent Height (MDH) with associated brackets, if the FCU setting is QFE
FCOM says this: 
![image](https://user-images.githubusercontent.com/16833201/189670730-252db3a9-5beb-413b-9a26-7986653ff8ef.png)
So both should be there

2022-09-12 13:50 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +## APPROACH
Yes - will add

2022-09-12 14:00 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +- TROPO (6R):
added link to SKYbrary

2022-09-12 14:42 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +- BLOCK (2R)
Added a note

2022-09-12 15:50 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +    - Only available on origin or alternate airport.
I'll remove it

2022-09-12 15:59 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +        Currently not available or INOP in the FBW A32NX for Microsoft Flight Simulator.
The docs do not cover Experimental - if it not on Dev/Stable it will not be documented. Some exception apply of course.

2022-09-12 16:03 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/f-pln.md
> +The RWY, SIDS and TRANS (if any) pages are available.
the "if any" is only related to TRANS - I think the other pages would always show.

2022-09-12 17:08 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/mcdu-menu.md
> +    - COMM MENU
Mhhh - these extra applications are not well defined and not even mentioned in the FCOM. 
I can try to find some info for these.  
I just wanted to mention the buttons the A32NX shows.

2022-09-12 17:11 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/messages.md
> +- They are suppressed, if correct data is entered or when they no longer apply
I trust your knowledge about "," in English - but all these comma mistakes are also in the FCOM (probably written by a French guy :) )

2022-09-12 17:19 UTC, frankkopp commented
> 

Awesome review - thanks!!
Accepted most changes - even the commas :D - although these were from the FCOM. But I don't think it is critical - who actually understands English commas :D

2022-09-19 02:09 UTC, Valastiri commented
https://docs-git-fork-frankkopp-briefing-mcdu-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/pedestal/mcdu/

Suggest adding a link from this page (flight deck MCDU) to the MCDU guides

2022-09-19 02:42 UTC, Valastiri requested changes
Based on straks review lgtm did a full pass on layouts only one broken admonition hence marking this review as changed req.

2022-09-19 02:42 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/mcdu/perf.md
> +        this altitude. (The 400 ft minimum still applies).
```suggestion
  !!! note ""
      - A clearing action reverts both values to the default values.
      - When the flight crew selects an altitude on the FCU that is below THR RED, it brings THR RED and ACC down to
        this altitude. (The 400 ft minimum still applies).
```
Broken in production 
![image](https://user-images.githubusercontent.com/1619968/190941275-4222f23d-55b2-435f-ab1a-6cc73edb69d9.png)

2022-09-19 02:42 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +## INIT B
```suggestion
## INIT FUEL PRED
```

Is this still referred to as INIT B in our spec of the MCDU? or simply INIT FUEL PRED?

2022-09-19 08:51 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/mcdu/init.md
> +## INIT B
The FCOM calls it INIT B still

2022-09-19 08:53 UTC, frankkopp commented
> [docs-git-fork-frankkopp-briefing-mcdu-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/pedestal/mcdu](https://docs-git-fork-frankkopp-briefing-mcdu-flybywire.vercel.app/pilots-corner/a32nx-briefing/flight-deck/pedestal/mcdu/)
> 
> Suggest adding a link from this page (flight deck MCDU) to the MCDU guides and removing the "future update"
> 
> ![image](https://user-images.githubusercontent.com/1619968/190939571-cf724d61-7d9e-4fb2-ad4a-c9e2e249d184.png)

done

2022-09-20 09:07 UTC, merged