EFB development guide
flybywiresim/docs pull request #194
Opened 2021-09-05 23:05 UTC by NUTTTTTTTT

## Summary
Adds an EFB development guide for new people wanting to contribute code to the EFB. Guides through setup and Symlink, covers hot reloading in-sim and basic troubleshooting.

Discord username (if different from GitHub):
█▀█ █▄█ ▀█▀#2123

2021-09-06 08:29 UTC, frankkopp requested changes

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/.pages
> +    - flyPadOS Development: flypad-dev.md
```suggestion
    - flyPadOS Development: flypad-dev.md
    - Javascript Development: javascript.md
```

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +![image](../dev-corner/assets/EFBLoader.png){loading=lazy}
Suggestion:
The max image width the layout allows is 826px - maybe resize it to that so make it even smaller. 
Also may apply a little sharpening (sharpen edges) to it. 
Let me know if I can help.

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +[GitHub Contributing.md](https://github.com/flybywiresim/a32nx/blob/master/.github/Contributing.md), please familiarise yourself with the information, steps and requirements listed there before readi
```suggestion
[GitHub Contributing.md](https://github.com/flybywiresim/a32nx/blob/master/.github/Contributing.md). Please familiarise yourself with the information, steps and requirements listed there before reading further.
```

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +Note: Make sure you remove any existing copy of the aircraft from your community folder before doing this.
```suggestion
!!! warning ""
    Make sure you remove any existing copy of the aircraft from your community folder before doing this.
```

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +```  npx rollup -wc src/instruments/buildSrc/simulatorBuild.mjs ```
Best is to write this always in separate line - the 3 escape characters should be on a separate line.

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +``` VCockpit16 - EFB_TEMPLATE [coui://html_UI/Pages/VCockpit/Core/VCockpit.html]```
the 3 escape characters should be on a separate line.

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +- You'll find the main EFB content under ``` src/instruments/src/EFB ``` of your Github fork, try making small changes at first to test, such as changing the colour of an icon, or changing a few word
```suggestion
- You'll find the main EFB content under `src/instruments/src/EFB` of your Github fork, try making small changes at first to test, such as changing the colour of an icon, or changing a few words to make sure the reloading is working. 
```

When you want to have code in a line mixed with other content you can you a single `

2021-09-06 08:29 UTC, frankkopp commented on docs/dev-corner/flypad-dev.md
> +- The flyPad will turn on, but switch and stay off when clicking on an affected page (Reloading the build in the browser will bring this back).
"The flyPad will turn on, but switch and stay off when clicking on an affected page"

this is a bit unclear...

2021-09-06 15:02 UTC, Valastiri requested changes
After these changes, highly suggest you bring this up to dev-team to ensure the content is valid / correct. 

Grammatically and functionally for the document though Maverick + myself.

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +[**Development Guide Overview**](https://docs.flybywiresim.com/dev-corner/development-guide){ .md-button target=new}
```suggestion
[**Development Guide Overview**](https://docs.flybywiresim.com/dev-corner/development-guide){.md-button target=new}
```

Just to keep it clean remove the empty sspace, same with the GitHub one.

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +
```suggestion
[GitHub Contributing.md](https://github.com/flybywiresim/a32nx/blob/master/.github/Contributing.md){target=new}. Please familiarise yourself with the information, steps and requirements listed there before reading further.
```

Maybe add this since it's offsite here

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +Before you can load the project to test in your simulator, you first need to ensure you've created a fork of the [A32NX project on GitHub](https://github.com/flybywiresim/a32nx) and have cloned this
{target=new} here as well and the link below

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +## Creating a Symlink and setting up instant-reload
```suggestion
## Creating a Symlink and Setting up Instant-Reload
```

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +## Quick reloading the flyPad
capitalize "Reloading"

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +## Getting started with the EFB code
```suggestion
## Getting Started with the EFB Code
```

2021-09-06 15:02 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +- Take a look at previous commits made to the flyPad on the [A32NX Github Repository](https://github.com/flybywiresim/a32nx/commits/master) and see what changes were made to get the desired result.
{target=new} the link here as well

2021-09-06 15:04 UTC, Valastiri commented on docs/dev-corner/flypad-dev.md
> +
it's the {target=new}. Apologies weird suggestion commit.

2021-09-08 13:34 UTC, Valastiri approved these changes

2021-09-08 20:56 UTC, frankkopp approved these changes

2021-09-10 15:03 UTC, Valastiri commented
retargeted to the `dev-guide-overhaul` branch to include your work. We'll merge that branch as part of the larger requested changes to the dev corner section.

2021-09-10 15:04 UTC, merged