docs: EFB User Documentation
flybywiresim/docs pull request #195
Opened 2021-09-06 10:33 UTC by frankkopp

Adds a comprehensive end user documentation for the FlyByWire flyPad. 

- [x] Base structure
  - [x] Redirect for throttle-calibration.md
- [x] Screenshots
- [ ] Content on all pages
  - [ ] Overview: index.md
   - [ ] flyPad Dashboard: dashboard.md
   - [ ] flyPad Dispatch: dispatch.md
   - [ ] flyPad Ground: ground.md
   - [ ] flyPad Performance: performance.md
   - [ ] flyPad Naviagtion & Charts: charts.md
   - [ ] flyPad Online ATC: online-atc.md
   - [ ] flyPad Failures: failures.md
   - [ ] flyPad Settings: settings.md
- [ ] Review/QA

2021-09-09 14:39 UTC, Valastiri requested changes
Small typos and a few suggestions for review - can discuss in discord

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/dispatch.md
> +Set this setting to the desired duration of refueling. Either unrealistic but instant refueling (Instant), realistic refuel time (Real) or a middle ground (Fast).
```suggestion
Set this setting to the desired duration of refueling. Either instant refueling (Instant - but unrealistic), realistic refuel time (Real) or a middle ground (Fast).
```

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/failures.md
> +This page is a prototype of failures simulation for the FlyByWire A32NX. It lays
```suggestion
This page is a prototype for utilizing failures simulation for the FlyByWire A32NX. It lays
```

the use case is fine here, this is purely suggestion for readability

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/failures.md
> +This page will therefore change along the implementation of the failure system.
alongside
```suggestion
This page will therefore change alongside the implementation of the failure system.
```

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/ground.md
> +It also has more and better features as the default sim ground services.
```suggestion
It also has more and better features than the default sim ground services.
```

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/ground.md
> +It is not necessary to use this with the FlyByWire A32NX as fuel can be loaded through the MCDU ([MCDU Load Fuel & Payload](../../../pilots-corner/beginner-guide/preparing-mcdu.md#load-fuel-and-paylo
Maybe here we recommend not to use this feature as the MSFS fuel / pax loading can mess with the rest of the config. Thoughts?

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +Depending on the scenarios ground speeds are included in the calculation to take into account that during descent we usually also slow down at some point.
```suggestion
Depending on the scenario, ground speeds are included in the calculation to take into account that we usually also slow down at some point during descent.
```

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +**Result: We need to start our descent ^^88NM^^ before the target fix at which we want to reach 11.000ft. **
```suggestion
**Result: We need to start our descent ^^88NM^^ before the target fix at which we want to reach 11.000ft.**
```

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +To calculate the TOD with a fixed distance to the a specific fix we have to enter the starting altitude and the desired target altitude and also the distance to the target fix.
```suggestion
To calculate the TOD with a fixed distance to the a specific fix we have to enter the starting altitude, the desired target altitude, and the distance to the target fix.
```

2021-09-09 14:39 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +To calculate the TOD with a fixed vertical speed (rate of descent) we have to enter the starting altitude and the desired target altitude and also the desired vertical speed.
```suggestion
To calculate the TOD with a fixed vertical speed (rate of descent) we have to enter the starting altitude, the desired target altitude, and the desired vertical speed.
```

2021-09-09 21:08 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/ground.md
> +It is not necessary to use this with the FlyByWire A32NX as fuel can be loaded through the MCDU ([MCDU Load Fuel & Payload](../../../pilots-corner/beginner-guide/preparing-mcdu.md#load-fuel-and-paylo
Done, OK?

![image](https://user-images.githubusercontent.com/16833201/132762879-fc601af3-f6e0-489a-b704-4b374bdcded4.png)

2021-09-10 09:20 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/ground.md
> +It is not necessary to use this with the FlyByWire A32NX as fuel can be loaded through the MCDU ([MCDU Load Fuel & Payload](../../../pilots-corner/beginner-guide/preparing-mcdu.md#load-fuel-and-paylo
Yup!

2021-09-10 09:20 UTC, Valastiri approved these changes

2021-09-10 10:22 UTC, xZreai commented
Discord: Cleon#5802
Object of testing: (#195)
Date: (10/09/2021)

Testing Process: Read through all pages of the document, checked all sublinks
Conclusions: 

1 Note for LINK MCDU being INOP. should be added in the overview page

2 *You can click and drag or use the handlebar to scroll up or down the page.* Text can be added for this
![image](https://user-images.githubusercontent.com/81078099/132839148-174ebad9-97b7-4597-b462-1e55c2f45edf.png)

3 Spelling error *Angle of Descent* under flyPad performance page 

4 Spelling error flyPad **Navigation & Charts** in the sublinks section and page

5 Failures page image needs to be updated in accordance to PR #5792 in Master branch

6 Spelling error for **ADIRS** under Sim options in flyPad settings 

Overall good job!

2021-09-10 11:20 UTC, frankkopp commented
@xZreai changes are done if you like to re-review :)

2021-09-10 12:28 UTC, merged

2021-09-10 22:59 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/dashboard.md
> +    - Shows current METAR information for the loaded origin and destination airport.
suggest "loaded and destination airport**s**."

2021-09-10 23:00 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/dashboard.md
> +    Distance measure tools.
Distance measurement tools?

2021-09-10 23:24 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/dispatch.md
> +This page provides information about the aircraft. It has no further functionality at this time.
The accompanying picture shows we have the wrong max fuel capacity stated on that page. Also max passengers and cargo values will be changing soon from pr 5547. I think I will open a pr to change the values on this page.

2021-09-10 23:33 UTC, donstim commented
I suggest also adding something on the overview page that provides a legend for the symbols used to access the different EFB pages. Although you can see what each one is by holding the cursor over it, people may not use those symbols to reach the other pages when going through this document. Maybe just add something simple like "Placing the mouse cursor over the EFB menu icon will show a pop up of which page it will access."  (It would be nice if the EFB on the airplane would also have these popups.)

2021-09-10 23:40 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +**Result: We need to start our descent 90NM before the target fix with either a ^^vertical speed of -2.333ft/min^^ or a ^^descent angle of -2.9°^^**
The vertical speed and descent angles are averages that need to be achieved over the descent distance in order to obtain the target altitude in the target distance. It should not be implied that the user needs to set one of these values in the autopilot.

2021-09-11 01:21 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/dashboard.md
> +    Distance measure tools.
What else are these?

2021-09-11 01:22 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/dispatch.md
> +This page provides information about the aircraft. It has no further functionality at this time.
Ok, happy to do a new screenshots then. Also I'm aware there might be changes in the future we have to also make on these pages.

2021-09-11 01:24 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +**Result: We need to start our descent 90NM before the target fix with either a ^^vertical speed of -2.333ft/min^^ or a ^^descent angle of -2.9°^^**
Good point. Will clarify that.

2021-09-11 01:27 UTC, frankkopp commented
> I suggest also adding something on the overview page that provides a legend for the symbols used to access the different EFB pages. Although you can see what each one is by holding the cursor over it, people may not use those symbols to reach the other pages when going through this document. Maybe just add something simple like "Placing the mouse cursor over the EFB menu icon will show a pop up of which page it will access."  (It would be nice if the EFB on the airplane would also have these popups.)

There is actually a description under the image on the overview page. 

On PC it is probably not an issue as the pages are in the navigation. On mobile I thought the linked buttons might help. Maybe it is necessary to put a note under each image?

2021-09-11 04:44 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/dashboard.md
> +    Distance measure tools.
Sorry, the bold text didn't come through in my comment. I was asking if it should be "Distance measurement tools" rather than "Distance measure tools."

2021-09-11 04:46 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +    - as required
How about, "Flaps:  - Planned landing flap setting (CONF FULL or CONF 3)?"

2021-09-11 04:49 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +    - as required
How about "Overweight Procedure: - Will the landing weight be greater than the maximum landing weight (Yes or No)?"

2021-09-11 04:55 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +    - This information can be obtained from the airport chart (see example below).
I think this should be re-written from the standpoint that it is the flightcrew's or operator's decision whether or not to use reverse thrust, but it may be subject to airport requirements. Are there any airports that flat out prohibit the use of reverse thrust?  In the example shown, shortening the landing distance is certainly a safety consideration.

I suggest say something like "Will reverse thrust be used (Yes or No)? and then maybe saying that this might be subject to airport requirements that can be found on the airport chart.

2021-09-11 04:56 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +This runway can be used for landing with the given circumstances and full flaps in all autobrake configurations (low, medium, max manual).
Max manual is not an autobrake configuration. How about saying in all braking configurations rather than in all autobrake configurations?

2021-09-11 04:57 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +Be aware that there might be other restriction that prohibit landing of an A320neo on this airport/runway.
"might be other restriction" should be "might be other restrictions"

2021-09-11 04:58 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +This runway could be technically used for landing with the given circumstances and full flaps and with max manual braking.
How about, "This runway's landing distance is long enough to be used for landing with..."

2021-09-11 05:03 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/settings.md
> +    - Configures if the aircraft should use "No Smoking" or "No Portable Devices" in its ECAM message.
I suggest adding "in its ECAM message when the no smoking selector switch on the overhead panel is selected on."

2021-09-11 07:51 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/dashboard.md
> +    - Shows current METAR information for the loaded origin and destination airport.
I don't understand this change? Now it's missing a word.
Is the word origin the issue? Would departure be better?

2021-09-11 07:53 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/dispatch.md
> +This page provides information about the aircraft. It has no further functionality at this time.
Should I add a comment on this page that the values are currently not correct?
What are the correct values?

2021-09-11 09:13 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +**Result: We need to start our descent 90NM before the target fix with either a ^^vertical speed of -2.333ft/min^^ or a ^^descent angle of -2.9°^^**
Added average during descent distance. 

**Result: We need to start our descent 90NM before the target fix with either an average of ^^vertical speed of -2.333ft/min^^ or an average ^^descent angle of -2.9°^^** during the descent distance.

On the other it would not be wrong to set these values into the autopilot as long as there are no other restrictions (charts, ATC), right?

2021-09-11 09:21 UTC, frankkopp commented
> I suggest also adding something on the overview page that provides a legend for the symbols used to access the different EFB pages. Although you can see what each one is by holding the cursor over it, people may not use those symbols to reach the other pages when going through this document. Maybe just add something simple like "Placing the mouse cursor over the EFB menu icon will show a pop up of which page it will access." (It would be nice if the EFB on the airplane would also have these popups.)

Changed all images to have a image caption with the note that the menu can be clicked.

2021-09-11 14:48 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/dashboard.md
> +    - Shows current METAR information for the loaded origin and destination airport.
Just missing a letter. Airports is missing the "s" at the end to make it plural.

2021-09-12 04:37 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +**Result: We need to start our descent 90NM before the target fix with either a ^^vertical speed of -2.333ft/min^^ or a ^^descent angle of -2.9°^^**
It would not be wrong, but this calc is a general back-of-the-envelope calculation that is a way to approximate the descent distance during a normal open descent. It is not meant to be precise (though it can be very good), and is not meant to specify a vertical speed or fpa to fly. If they really want to fly a specific vertical speed or fpa, they can use one of the other calculation types.

2021-09-12 10:49 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/performance.md
> +**Result: We need to start our descent 90NM before the target fix with either a ^^vertical speed of -2.333ft/min^^ or a ^^descent angle of -2.9°^^**
Ok - will rewrite this accordingly

2021-09-12 10:49 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/flyPad/dispatch.md
> +This page provides information about the aircraft. It has no further functionality at this time.
No change required as per DM