feat: QA Docs Page
flybywiresim/docs pull request #209
Opened 2021-09-14 16:31 UTC by frankkopp

## Summary
Adds a page to document the QA process.

### Location
page under developer corner

## Structure and Tasks:

- [ ] Why QA
- [ ] FlyByWire QA Process Overview
- [ ] Requirements: Github
- [ ] What to test (QA board)
- [ ] How to get PR builds
- [ ] How to test 
  - [ ] Tiers
- [ ] Reporting on Tests 
  - [ ] Template
- [ ] Roles 
- [ ] Contact

2021-09-15 21:08 UTC, Valastiri commented
lgtm so far

2021-09-16 13:28 UTC, BlueberryKing requested changes
lgtm! Just a couple of typos I spotted

2021-09-16 13:28 UTC, BlueberryKing commented on docs/dev-corner/qa-process.md
> +This is a simple Kanban board where items move from the left to the rights. For QA tests the third column is relevant ("QA Team Review: Ready to Test"
```suggestion
This is a simple Kanban board where items move from the left to the right. For QA tests the third column is relevant ("QA Team Review: Ready to Test")
```

2021-09-16 13:28 UTC, BlueberryKing commented on docs/dev-corner/qa-process.md
> +Read the test instructions of the PR carefully. Focus only on what is requested and part of this PR. Do not bloat you reports with many additional observations.
```suggestion
Read the test instructions of the PR carefully. Focus only on what is requested and part of this PR. Do not bloat your reports with many additional observations.
```

2021-09-16 13:28 UTC, BlueberryKing commented on docs/dev-corner/qa-process.md
> +This documentation describes the FlyByWire QA Process and tools in detail to make sure, we can efficiently and effectively delivery the highest quality in our products.
```suggestion
This documentation describes the FlyByWire QA Process and tools in detail to make sure, we can efficiently and effectively deliver the highest quality in our products.
```

2021-09-16 13:28 UTC, BlueberryKing commented on docs/dev-corner/qa-process.md
> +5. Unzip the file and place the "flybywire-aircraft-a320-neo" folder into you Community.
```suggestion
5. Unzip the file and place the "flybywire-aircraft-a320-neo" folder into your Community.
```

2021-09-16 13:28 UTC, BlueberryKing commented on docs/dev-corner/qa-process.md
> +More complex features or features vital for the stability of the add-on will need considerably more testing then a simple change of a button text.
```suggestion
More complex features or features vital for the stability of the add-on will need considerably more testing than a simple change of a button text.
```

2021-09-16 13:28 UTC, BlueberryKing commented on docs/dev-corner/qa-process.md
> +- Tests without a full flight or media are not valid and will require other tester to still do a full tier 2 test.
```suggestion
- Tests without a full flight or media are not valid and will require another tester to still do a full tier 2 test.
```

2021-09-16 16:26 UTC, frankkopp commented
> lgtm! Just a couple of typos I spotted

Thanks a lot! Accepted all changes.

2021-09-16 16:45 UTC, BlueberryKing approved these changes

2021-09-17 02:46 UTC, Valastiri approved these changes

2021-09-17 12:05 UTC, merged