docs: update info for new flight model w&B + simbrief information
flybywiresim/docs pull request #217
Opened 2021-09-18 00:20 UTC by Valastiri

Supports changes to A32NX via https://github.com/flybywiresim/a32nx/pull/5547
## Summary

Created an appendix in beginner guide to support new information and model changes to the A32NX weights and balance. 

Additionally adds supporting information about the built-in simBrief integration to round out the documentation.
### Location

Discord username (if different from GitHub):

2021-09-21 22:29 UTC, MikeRLJones commented
Looking great, is there a way to print this or at least a checklist of headings that I can use as a reference.

Thanks

MikeJ

2021-09-21 22:53 UTC, frankkopp commented
> Looking great, is there a way to print this or at least a checklist of headings that I can use as a reference.
> 
> 
> 
> Thanks
> 
> 
> 
> MikeJ

Use browser read mode and then print. Easiest way :)

2021-09-22 02:23 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 46262 (in kilograms)
FYI. We (actually Sid) are in the process of revising the OEW. With this OEW, you cannot load 174 pax plus their bags (84 kg per passenger plus 20 kg per bag) without exceeding the MZFW.

2021-09-22 02:25 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- Passenger Weight: 140 (in kilograms)
Looks like a typo. Total weight added per passenger is 104 kg, not 140 kg. It consists of 84 kg for the passenger (including clothing and carry-on bags) and 20 kg of checked luggage.

2021-09-22 02:29 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +In simple terms the zero fuel weight (ZFW) is the empty weight of the aircraft + payload. The payload would be pilot, passengers, baggage, and no fuel on board. In a situation where your payload woul
The flightcrew is part of the OEW. Payload is only that weight that generates revenue (that's the "pay" in payload).  MSFS UI is wrong, where the pilot and co-pilot weight are included as payload. We are fixing that. The flight and cabin crew weights, as well as things like food, galley carts, etc. are included in the OEW.

2021-09-22 02:34 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +The A32NX simBrief integration's auto-loading feature allows for automated ZFWCG configuration. The auto population of ZFW and ZFWCG on the INIT B page (once the aircraft and associated payload is lo
I hope this will be true in the future. I think currently, the ZFW will be correct on the INIT B page (I can't remember if it needs for the boarding process to complete), but in my testing, the ZFWCG on this page still comes from the MSFS UI weight distribution rather than the Simbrief weight distribution. In that case, until it is fixed (soon), you would have to observe the ZFW CG on the MCDU weight and balance page after loading is complete, and then insert this ZFW CG into the INIT B page input field.

2021-09-22 02:38 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +Trimming the aircraft for takeoff can be optional, we recommend pilots continue to trim their aircraft based on the reported CG value on INIT B or on your simBrief OFP prior to takeoff. "Auto-rotatio
As noted above, I don't think the ZFW CG reflects the actual ZFW CG when loading the airplane from the MCDU. And if someone is going to go to the trouble of setting takeoff trim, why would you recommend setting it according to the ZFW CG instead of the Takeoff CG?

2021-09-22 02:40 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +    This does not equate to have better takeoff or landing performance with an aft CG configuration. For a smaller aircraft as the A320neo, most operators would favor an aft CG loading for fuel consu
You can probably just delete that first sentence, "This does not equate..." I don't think most sim pilots would understand the nuances of this. It should be adequate just to have the 2nd sentence.

2021-09-22 02:42 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +    While opting to choose between either CG configuration (aft/fwd) please consider the above information.
Why not put this just below the line about what constitutes a forward load and what constitutes an aft load (line 47)? Then, it could say, "please consider the following" instead of saying to look again at what you just read.

2021-09-22 02:45 UTC, donstim commented on docs/fbw-a32nx/feature-guides/simbrief.md
> +Microsoft Flight Simulator tries to offer a simple way to do route planning (World Map before starting a flight) this is falls short, especially for users wanting a more realistic experience for airl
"this is falls short." Something wrong here. Either this should start a new sentence, "This falls short,..." or there should be a conjunction to continue the sentence, "but" (or "however")", this falls short..."

2021-09-22 02:48 UTC, donstim commented on docs/fbw-a32nx/feature-guides/simbrief.md
> +In our development version we have introduced a new flight model paired with a new weight and balance payload method that incorporates rows and the correct center of gravity. Please use the correct i
Maybe add the word "seat" to "that incorporates rows..." to read "that incorporates seat rows?"

2021-09-22 02:50 UTC, donstim commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    **NOTE:** It is advisable to **not** use the MSFS Fuel Panel to load fuel or weights until we have overridden it.
I think you can remove the "until we have overridden it." That note would be true either way. The only difference is that once we override it, whatever they enter in the MSFS fuel/payload UI will, after a few seconds, "bounce" back to the values from the MCDU/EFB.

2021-09-22 11:04 UTC, Valastiri commented
Retasking this PR solely for the fuel and weights flight model to facilitate the simbrief integration guide going live ahead of other information. 

Will draft while new changes to flight model pending + changes from review applied

2021-09-22 11:29 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 46262 (in kilograms)
Sounds good send me a ping when the frame is updated.

2021-09-27 15:26 UTC, Valastiri commented
rebased on primary

2021-09-27 17:59 UTC, Valastiri commented
Using the sample frame provided in https://github.com/flybywiresim/a32nx/pull/5895, will finalize when PR is merged

2021-09-28 20:37 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 46262 (in kilograms)
Using the new frame in PR -> https://github.com/flybywiresim/a32nx/pull/5895

2021-09-28 22:04 UTC, frankkopp requested changes

2021-09-28 22:04 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
OEW = EW + Crew 
https://en.wikipedia.org/wiki/Operating_empty_weight

2021-09-28 22:04 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +In simple terms the zero fuel weight (ZFW) is the empty weight of the aircraft + payload. The payload would be passengers, baggage, and no fuel on board. In a situation where your payload would be so
ZFW = OEW + Payload

2021-09-28 22:04 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +The auto population of ZFW and ZFWCG on the INIT B page (once the aircraft and associated payload is loaded into the simulator) should match your simBrief OFP.
Is ZFWCG on the OFP?

2021-09-28 22:04 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +!!! info ""
Suggestion: Add that checking the MSFS dialog for CG is a temporary thing. Otherwise we confuse people by saying don't touch it but look this value is important. 
I think we can mention that this will all move to the EFB.

2021-09-28 22:04 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +Trimming the aircraft for takeoff can be optional and technically not required. However, please reference the above image in your simulator to find takeoff CG and use the [FBW Checklist](../../pilots
Auto-rotation should be explained -sounds like a ECAM message or feature :)

2021-09-28 22:04 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/simbrief.md
> +        Note: this not start the boarding process. (Cargo will be limited as a protection to a max capacity if the simBrief OFP cargo exceeds the cargo hold limits).
```suggestion
        Note: this does not start the boarding process. (Cargo will be limited as a protection to a max capacity if the simBrief OFP cargo exceeds the cargo hold limits).
```

2021-09-28 22:26 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +The auto population of ZFW and ZFWCG on the INIT B page (once the aircraft and associated payload is loaded into the simulator) should match your simBrief OFP.
No, Simbrief would have no way of knowing what that would be. It would have to be calculated from the DOW/OEW CG and the payload in each loading station. It does not have that information.

2021-09-28 22:44 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +The auto population of ZFW and ZFWCG on the INIT B page (once the aircraft and associated payload is loaded into the simulator) should match your simBrief OFP.
Will correct to reflect the difference here in an update.

2021-09-28 22:45 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +!!! info ""
@sidnov You wanted to not reference the move to EFB. I sort of do agree here that we technically should so that users are aware of an impending "switch" in the future. Most are used to `.when` anyways.

2021-09-28 23:02 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
There are many definitions of different empty weights, but the Wikipedia definition is inconsistent with any definitions I am familiar with. Basically, the OEW = Manufacturer's empty weight + Standard Items + Operator Items, where "Standard Items" include cabin layout changes, certain optional equipment as well as provisions for potential future optional equipment, etc, but **not** things like fluids necessary for operation. "Operator Items" include usable and unusable fluids, crew, documents, life vests, passenger service items, food and beverage, etc. See https://www.smartcockpit.com/docs/Determination_Of_Dispatch_Takeoff_Weight.pdf and https://www.smartcockpit.com/docs/Determination_Of_Dispatch_Takeoff_Weight.pdf for example, as well as
![OEW breakdown](https://user-images.githubusercontent.com/70166617/135177129-7a60cb1b-5a03-4141-9bef-0c83eace9c72.jpg)
:

2021-09-28 23:18 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
Suggest: "OEW (Operating Empty Weight), also referred to as DOW (Dry Operating Weight): 42,500 kg/93,697 lb

2021-09-28 23:28 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
I did not intend to claim that Wikipedia is correct. The focus was on OEW = EW plus Crew and maybe other stuff. 

Or to see it from the other direction, payload is does not include crew. 

Meaning: ZFW = OEW + Payload = EW + Crew (+other stuff) + Payload

2021-09-29 01:36 UTC, donstim commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
Well, I'll just repeat, OEW = Manufacturer's empty weight + Standard Items + Operator Items. Operator items aren't just crew and "maybe other stuff" added to the basic empty weight.  There's a lot of "other stuff" that has to be included in the OEW.

2021-09-29 07:12 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
Yes, you are missing my point. I try to anticipate what questions a user might have. And as you already pointed it out some aircraft show pilots and crew separately.

I would expect some user to start thinking if they have to add the 6 crew to the pax or not. And I think it would be helpful to provide the definition of these weights without going into unnecessary detail.

So basically we should point out that Crew is included in the OEW weight because that might be unclear to some users.

2021-09-29 12:50 UTC, sidnov commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +!!! info ""
Fine with me. I would also not mention the TOCG or MSFS Fuel dialog at all. The CGs are balanced during autoload, and the ones who know how to use CG accurately will do so.

2021-09-29 18:24 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +- OEW (Empty Weight): 42500 (in kilograms)
![image](https://user-images.githubusercontent.com/1619968/135327013-b14e34cb-2a0f-4bf1-be41-54a7534e5e84.png)

This is what i've settled on to provide the best of both worlds without having to overburden with too much information.

2021-09-29 18:37 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +Trimming the aircraft for takeoff can be optional and technically not required. However, please reference the above image in your simulator to find takeoff CG and use the [FBW Checklist](../../pilots
Removing this as it's just sort of out of place and would consume more space for something that is meant to be a very general discussion on CG.

2021-09-29 18:43 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/fuel-and-weight.md
> +!!! info ""
Made some changes to the text and left the original commented out temporarily. If satisfied can remove entirely. Just sort of remove the references to the fuel and weights window in general and anyone that wants to figure out CG can just ask in Discord (or if they know what they are doing as you mentioned).

2021-10-19 15:56 UTC, Valastiri commented
[Direct Preview of Documentation](https://docs-git-supporting-flight-model-flybywire.vercel.app/fbw-a32nx/feature-guides/fuel-weights/)

- New location and dedicated placement as a feature-guide.
- Checked for other references to fuel loading and corrected navigation / copy.

Updated to match changes to https://github.com/flybywiresim/a32nx/pull/5895

2021-10-29 09:43 UTC, frankkopp commented
This PR is in QA now - time to review this before the merge :)

2021-10-29 16:07 UTC, Valastiri commented
Requires some validation on final config from https://github.com/flybywiresim/a32nx/pull/5895 based on the testing airframe for the supporting information. 

Rest of the guide should be fine.

2021-11-04 09:43 UTC, frankkopp approved these changes

2021-11-09 21:06 UTC, Valastiri commented
will handle a rebase later on this after all changes done

2021-11-12 15:30 UTC, Valastiri commented
Self note: https://github.com/flybywiresim/docs/pull/290 -- Ensure documentation from this page reflects updated pages in this PR

2021-11-20 15:41 UTC, frankkopp approved these changes

2021-11-26 18:53 UTC, merged