docs: experimental version documentation changes after cFMS is merged into dev
flybywiresim/docs pull request #249
Opened 2021-10-09 11:11 UTC by Valastiri

## Summary

Update all reference to experimental version to correctly describe features that are now available in development and retool the experimental page to correctly reflect what the branch will be doing next. 
### Location

- fixinfo
- installation
- landing
- descent
- reported-issues
- faq (this is a correction that was not done when exp went live again)

### TODO

- [ ] Update exp.md with what is being featured/tested and any known issues and where to report them
- [ ] Cross check other documents for references to experimental
- [ ] Other documentation to support cFMS for the userbase
Discord username (if different from GitHub):
 Valastiri#8902

2021-10-09 11:59 UTC, derl30n commented on docs/fbw-a32nx/fbw-versions.md
> +        Please do not seek support for the Experimental Version on Discord and only report issues if you have read this page and the reported and known issues.
Dunno the tripple and kinda threw me of when reading this...

```suggestion
        Please do not seek support for the Experimental Version on Discord and only report issues if you have read this page as well as the reported and known issues.
```

2021-10-14 15:09 UTC, Valastiri commented on docs/fbw-a32nx/fbw-versions.md
> +        Please do not seek support for the Experimental Version on Discord and only report issues if you have read this page and the reported and known issues.
Just saw this, thanks!

2021-10-29 13:29 UTC, frankkopp requested changes
Initial feedback/review

2021-10-29 13:29 UTC, frankkopp commented on docs/fbw-a32nx/fbw-versions.md
> +    Currently we are testing the new implementation of the TCAS.
contradicts exp.md change

2021-10-29 13:29 UTC, frankkopp commented on docs/fbw-a32nx/fbw-versions.md
> +    The experimental version will be updated regularly and also with the latest changes to the Development version. Expect updates about once a week (not guaranteed).
```suggestion
    The experimental version will be updated regularly with the latest changes to the Development version. Expect updates about once a week (not guaranteed).     
```

2021-10-29 13:29 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/cFMS.md
> +## Known Issues
As discussed on Discord - consider to move this to a section in reported-issues

2021-10-29 13:29 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/fixinfo.md
> +The A32NX has implemented the display of these lines and circles on the ND.
```suggestion

```

2021-10-29 13:29 UTC, frankkopp commented on docs/fbw-a32nx/support/exp.md
> +This page will be updated when we start work on new features in the experimental branch.
contradicts fbw-versions.md

2021-10-31 19:29 UTC, Valastiri commented on docs/fbw-a32nx/fbw-versions.md
> +    The experimental version will be updated regularly and also with the latest changes to the Development version. Expect updates about once a week (not guaranteed).
Going to just comment this portion out for usage later, instead of altering it.

2021-11-07 11:30 UTC, frankkopp requested changes
We need to rebase b/o reported-issues

2021-11-07 11:30 UTC, frankkopp commented on docs/fbw-a32nx/fbw-versions.md
> +    The experimental version will be updated regularly and also with the latest changes to the Development version. Expect updates about once a week (not guaranteed).-->
```suggestion
    While not "on hold" the experimental version will be updated regularly and also with the latest changes to the Development version. Expect updates about once a week (not guaranteed).-->
```

2021-11-07 11:30 UTC, frankkopp commented on docs/fbw-a32nx/installation.md
> +        <!--Currently the new FlyByWire Custom Flight Management System (cFMS) is available in the Experimental version.-->
```suggestion
        <!--Currently the new FlyByWire Custom Flight Management System (cFMS) is available in the Experimental version.-->
        Currently the Experimental version is on hold until we start testing new major features. We will then update this page. 
```

2021-11-07 11:30 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/landing.md
> +    You might ask what the blue dashed line is. It is part of the new FIX INFO feature available only in the development version for the time being. It allows to draw distance rings or radial lines f
```suggestion
    You might ask what the blue dashed line is. It is part of the new FIX INFO feature available only in the Development version for the time being. It allows to draw distance rings or radial lines from navigation fixes. For this illustration it helps us to visualize the localizer signal path at 261° into the runway which we are going to capture with the APPR mode.
```

2021-11-12 14:49 UTC, frankkopp approved these changes

2021-11-12 14:49 UTC, frankkopp commented on docs/fbw-a32nx/support/reported-issues.md
> +    Due to the complex nature of our custom autopilot, please visit the dedicated ^^Autopilot / Fly-By-Wire^^ page for more information:
```suggestion
    Due to the complex nature of our custom autopilot, please visit the dedicated ^^Custom Autopilot / Fly-By-Wire^^ page for more information:
```

2021-11-20 08:56 UTC, xZreai commented
Noticed a small typo in point 3 of the Known Issues section: 
![image](https://user-images.githubusercontent.com/81078099/142720606-2216163b-94ea-4b5d-8408-fc9bdbeb9ba7.png)
Other than that all seems good 👍😉

2021-11-20 14:05 UTC, frankkopp commented
> Noticed a small typo in point 3 of the Known Issues section: ![image](https://user-images.githubusercontent.com/81078099/142720606-2216163b-94ea-4b5d-8408-fc9bdbeb9ba7.png) Other than that all seems good 👍😉

fixed

2021-11-21 02:43 UTC, merged