docs(PFD Briefing): corrections and updates
flybywiresim/docs pull request #252
Opened 2021-10-10 19:57 UTC by Valastiri

fixes #251

## Summary

Currently only targeting review comments made in https://github.com/flybywiresim/docs/pull/177 past the merge date. 

A rather large change to the V2 speed description to provide more clarity and detail to engine out ops and general definition of V2.

![image](https://user-images.githubusercontent.com/1619968/136711459-5d0cdb00-af29-41d7-b8e1-7b4b990ec10d.png)

### Location

 docs/pilots-corner/a32nx-briefing/pfd/speedtape.md

Discord username (if different from GitHub):
 Valstiri#8902

2021-10-10 22:24 UTC, frankkopp requested changes

2021-10-10 22:24 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This speed is V~MO~ (maximum operating speed) + 6 knots or ~MMO~ (maximum Mach speed) + 0.01
```suggestion
This speed is V~MO~ (maximum operating speed) + 6 knots or MMO (maximum Mach speed) + 0.01
```

Only subscripted when added to Vxyz

2021-10-10 22:24 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +The upper speed is equal to the target speed + 20 knots, limited to V~MAX~, V~MO~ - 3 knots or ~MMO~ - 0.006, whichever is the lowest.
```suggestion
The upper speed is equal to the target speed + 20 knots, limited to V~MAX~, V~MO~ - 3 knots or MMO - 0.006, whichever is the lowest.
```

2021-10-10 22:24 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +- V~MO~ or the corresponding to ~MMO~
```suggestion
- V~MO~ or the corresponding to MMO
```

2021-10-10 22:24 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +This is a magenta triangle on the right side of the speedtape. It displays the V~2~ speed which has been set in the TAKE OFF PERF page of the MCDU. V~2~ is the minimum speed that needs to be maintain
```suggestion
This is a magenta triangle on the right side of the speedtape. It displays the V~2~ speed which has been set in the TAKE OFF PERF page of the MCDU. V~2~ is the minimum speed that needs to be maintained in the event of an engine failure after V~1~ up to acceleration altitude.
```

2021-10-10 22:24 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +V~2~+10 provides the best climb performance (before acceleration altitude + during NAPs).
reference?

2021-10-10 22:24 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +    After takeoff **V~2~+10** is the targeted speed you should reach and maintain by the time you attain a height of 35 FT after takeoff with an engine failure until reaching the acceleration altitud
Reference for V2:
![image](https://user-images.githubusercontent.com/16833201/136714826-ad23e6d1-badc-44cc-92fe-8562657a9be9.png)

V2+10 reference?

2021-10-10 22:40 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +    After takeoff **V~2~+10** is the targeted speed you should reach and maintain by the time you attain a height of 35 FT after takeoff with an engine failure until reaching the acceleration altitud
![image](https://user-images.githubusercontent.com/16833201/136715202-70836cc2-79a5-48b8-975a-7fbc02ed3b5a.png)

2021-10-10 22:43 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +    After takeoff **V~2~+10** is the targeted speed you should reach and maintain by the time you attain a height of 35 FT after takeoff with an engine failure until reaching the acceleration altitud
![image](https://user-images.githubusercontent.com/16833201/136715274-97e0281c-0167-44fa-b222-fc591ea62bac.png)

2021-10-10 22:44 UTC, frankkopp commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +The upper speed is equal to the target speed + 20 knots, limited to V~MAX~, V~MO~ - 3 knots or ~MMO~ - 0.006, whichever is the lowest.
Reference: Wikipedia:
![image](https://user-images.githubusercontent.com/16833201/136715295-cdcf14e9-6565-46a2-a9ce-f798584a721e.png)

2021-10-11 00:58 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +V~2~+10 provides the best climb performance (before acceleration altitude + during NAPs).
V2+10 provide better climb performance, not the "best" climb performance. A higher speed would provide even better climb performance, but it could negatively affect close-in obstacle clearance if it requires a lower climb angle while accelerating to that speed.

I recommend writing out Noise Abatement Program Departures rather than "NAPs" as I doubt many readers of this material will have a clue as what NAPs refers to. It isn't even in the list of abbreviations that may in itself be hard to find.

2021-10-11 01:02 UTC, donstim commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +    After takeoff **V~2~+10** is the targeted speed you should reach and maintain by the time you attain a height of 35 FT after takeoff with an engine failure until reaching the acceleration altitud
Suggest pilots should not "decelerate to" rather than not "degrade to." And may as well add "but not higher than V2+15" to the "maintain the speed at the time of engine failure" (a bit of suggest re-wording there as well). I assume you saw my further response to this item in the old PR so I don't have to reproduce it here.

EDIT:  I have a further comment. The current text you have says you should maintain V2+10 after takeoff with an engine failure. V2+10 is the speed you should reach without an engine failure.  The target speed for the engine failure case depends on when the engine failure occurs. If it is before reaching V2 (like before or just after lifting off), the target is V2. If after you are at a speed higher than V2, then you maintain the higher speed (but no higher than V2+15).

2021-10-11 10:29 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/pfd/speedtape.md
> +    After takeoff **V~2~+10** is the targeted speed you should reach and maintain by the time you attain a height of 35 FT after takeoff with an engine failure until reaching the acceleration altitud
Perfect thanks, I'll reword this to take all into account, was waiting for input and referential information to close both urs and mav's comments.

2021-10-13 23:10 UTC, frankkopp approved these changes

2021-10-14 06:56 UTC, Valastiri commented
@donstim Would you like to continue review on PFD or are you happy we merge this?

You could open an issue with any changes to production as well. Let me know :)

2021-10-14 07:05 UTC, donstim commented
LGTM

2021-10-14 15:08 UTC, merged