docs(beg-guide): abbreviations page updates and corrections
flybywiresim/docs pull request #255
Opened 2021-10-13 19:47 UTC by Inaxair

## Summary
Addition of 298 abbreviations.
Modification of the V/S V1 V2 Speed (indicated as vertical speed, modified for its own definition)
Addition of a Weight table like the V-Speed table.

### Location
docs/pilots-corner/beginner-guide/abbreviations.md

Discord username : Inax #1819

2021-10-14 01:06 UTC, Valastiri requested changes
Typo's and questions

2021-10-14 01:06 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| V1 | Decision Speed |
```suggestion
| V1 | Decision Speed/Critical Engine Failure Speed |
```

2021-10-14 01:06 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| T2CAS | Traffic and Terrain Collision Avoidance System |
```suggestion
| TCAS | Traffic and Terrain Collision Avoidance System |
```
Typo?

2021-10-14 01:06 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| ACT | Addutuibak Center Tank |
what is addutuibak?

2021-10-14 01:06 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| AGC | Automatic Gain Control, APU Generato Contactor |
```suggestion
| AGC | Automatic Gain Control, APU Generator Contactor |
```

2021-10-14 01:06 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| BHD | Bulhead |
```suggestion
| BHD | Bullhead |
```
Two L's?

2021-10-14 01:13 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| ACT | Addutuibak Center Tank |
Additional Center Tank. Don't know what happened

2021-10-14 01:13 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| BHD | Bulhead |
Actually is Bulkhead lol

2021-10-14 01:15 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| T2CAS | Traffic and Terrain Collision Avoidance System |
T2CAS is an actual thing

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| T2CAS | Traffic and Terrain Collision Avoidance System |
Then also add TCAS?  "Traffic Alert and Collision Avoidance System"
How about TAWS? ""Terrain Avoidance Warning System"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| V1 | Decision Speed/Critical Engine Failure Speed |
V1 is neither a "Decision Speed" nor a "Critical Engine Failure Speed." It is the maximum speed from which a rejected takeoff can be initiated to stop within the accelerate-stop distance and the minimum speed from which a takeoff can be safely continued following an engine failure just before V1.

The current regulatory definition for V1 is provided in (for the U.S) 14 Code of Federal Regulations Section 25.107(a)(2) and for Europe CS 25.107(c)(2):
 
“V1, in terms of calibrated airspeed, is selected by the applicant; however, V1 may not be less than VEF plus the speed gained with critical engine inoperative during the time interval between the instant at which the critical engine is failed, and the instant at which the pilot recognizes and reacts to the engine failure, as indicated by the pilot's initiation of the first action (e.g., applying brakes, reducing thrust, deploying speed brakes) to stop the airplane during accelerate-stop tests.”

The above definition was put into the regulations in 1988 and much effort was put into trying to get rid of all the old "Decision Speed" and "Critical Engine Failure Speed" references. Unfortunately, this effort was not entirely successful, and some manuals/etc still contain the old, incorrect terminology. (But not if I can help it. xD)

Also, the 1 in V1 should be subscript.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| V2 | Takeoff Safety Speed |
The "2" in V2 should be a subscript

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | V2min          | Critical Engine Failure Speed Decision Speed        |
V2min is not the Critical Engine Failure Speed. It is a speed that may not be less than:
(1) 1.13 VSR;  and
(2) 1.10 VMCA  

(Need to add VSR and VMCA to the list of abbreviations. As in other speeds the "SR" and "MCA" are subscripts. VSR is the reference stall speed) and VMCA is the minimum control speed in the air.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | MMO            | Mach Max Operating Speed                            |
Delete this one. MMO is Maximum Operating Mach, which is in the next line. The "MO" after "M" should be a subscript.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | VDF            | Very High Frequency Direction Finding Station       |
Need to add VMO - Maximum Operating Speed
"MO" is a subscript to "V"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | Mn             | Mach Number                                         |
Mach number is often abbreviated just as "M"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| BOH                 | Brake-Off Weight                                                    |
Should this be BOW rather than BOH?

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| MTOGW                | Maximum takeoff Gross Weight                      |
"takeoff" should be capitalized.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | A/BRK          | Autobrake Aircraft                                  |
Shouldn't this just be autobrake?

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | ACARS          | Aircraft Communication Addressing and               |
Missing the end of this - "Reporting System"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| ADM | Air data Module |
Capitalize "data?"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | AFM            | Aircraft Flight Manual                              |
"Aircraft" should be "Airplane" as i
![Screenshot (1263)](https://user-images.githubusercontent.com/70166617/137405489-304629d2-d0a5-4c88-9df7-1993a47c60af.png)
n

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| AOM | Aircraft Operating Manual |
I suggest removing this and replacing it with "FCOM  Flight Crew Operating Manual." Transport category airplanes like the A320 generally don't have AOMs; they have FCOMs.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | ASD            | Accelerate Stop Distance                            |
Suggest a hyphen between accelerate and stop.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| ESCESS | Excessive |
Should be EXCESS?

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| FEDR | Feeder |
Add "FDP - Final Descent Point?

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| CDC | Cargo Door Controller |
Add "CDA - Continuous Descent Arrival?"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | KIAS           | Knots Indicated Airspeed                            |
How about adding KCAS, KTAS, and maybe KEAS? Also, it looks like there is a KIAS and a TAS in this list, but no CAS, IAS, EAS, KCAS, KEAS, or KTAS.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | N1             | Engine Fan Speed                                    |
Why have 2 N1 definitions here?  I suggest keeping just the 2nd one as it is consistent with how the FCOM describes N
![Screenshot (1265)](https://user-images.githubusercontent.com/70166617/137407034-15fd596e-5b58-4ee1-96af-19d03c8415ab.png)
1

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | QFE            | Baro Pressure Setting for Airfield Altitude         |
Why 3 definitions?  The 1st and 3rd seem like repeats.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | QNH            | Sea Level Atmospheric Pressure                      |
Same question here as for QFE.

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | r/min          | Revolutions per Minute                              |
Also add "RPM - Revolutions per Minute?"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | RCLM           | Runway Center Line Marking                          |
Suggest adding "RCR - Runway Condition Report"

2021-10-14 23:17 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| SDCU | Smoke Detection Control Unit |
Add "SID - Standard Instrument Departure?"

2021-10-18 14:45 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| BOH                 | Brake-Off Weight                                                    |
It is BOH and not BOW

2021-10-18 14:47 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | A/BRK          | Autobrake Aircraft                                  |
Made a mistake of line with the A/C

2021-10-18 14:48 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | Mn             | Mach Number                                         |
![image](https://user-images.githubusercontent.com/70079939/137754674-eded4ab9-0456-420b-9211-82432ce12e3b.png)

2021-10-18 14:50 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | AFM            | Aircraft Flight Manual                              |
![image](https://user-images.githubusercontent.com/70079939/137754987-1848a277-337c-403d-991b-b53756fca458.png)
Modified, but it can also be aircraft

2021-10-18 14:52 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | N1             | Engine Fan Speed                                    |
I don't know, it was the previous writer who did it.

2021-10-18 14:53 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | QFE            | Baro Pressure Setting for Airfield Altitude         |
I'm not sure, but I guess depending on situations. You'll need to ask Maverick about it. I don't want to mess his stuff

2021-10-18 14:55 UTC, Inaxair commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| SDCU | Smoke Detection Control Unit |
Already there

2021-10-19 00:30 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
>  | AFM            | Aircraft Flight Manual                              |
Not officially. The term "aircraft" refers to anything that is used or is intended to be used for flight in the air. For example, it encompasses airplanes, airships, helicopters (rotorcraft), etc.. The manual for an airplane is an airplane flight manual; for a helicopter (rotorcraft), it is a rotorcraft flight manual.

2021-10-19 00:39 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| BOH                 | Brake-Off Weight                                                    |
xD: What does the "H" stand for?

2021-10-19 07:49 UTC, Valastiri commented
@donstim If you don't mind double-checking changes based on your review and any final comments. Happy to merge if you are good with this. Thanks in advance!

2021-10-19 07:49 UTC, Valastiri approved these changes

2021-10-28 08:47 UTC, tracernz commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| F                    | Minimum speed at which the flaps may be retracted at takeoff (i.e., CONF 2/3). Also the minimum speed in approach when in CONF 2 or 3                         |
s/minimum speed/recommended speed/
Minimum is VLS. Same applies for S speed.

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| V1                   | The highest speed during take-off that you can reject the take-off and still stop on the runway.
It is also the lowest speed from which a takeoff can be safely continued within the takeoff distance after an engine failure at the critical engine failure speed.

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| V2                   | Take-off safety speed, where if an engine fails, climb out and control is still guaranteed.
Takeoff safety speed that the airplane attains no later than reaching an altitude of 35 feet with one engine failed, and is maintained during the 2nd segment of the takeoff.  (This is the definition from the FCOM.) (BTW, nothing is guaranteed xD:)

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VA                   | Maximum design maneuvering speed, the maximum speed to do full control deflection in normal or alternate law.
Suggest slight re-wording -- the maximum speed at which a full control deflection in one direction should be made in normal or alternate law

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VLS                  | Lower Selectable Speed
**Lowe**st**** selectable speed

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VR                   | Rotate speed, the point where you lift the nose off the runway.
Rotation speed, the speed at which the pilot pulls back on the stick to pitch the airplane to the takeoff attitude

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VREF                 | Reference speed for a normal approach, what you aim to touchdown roughly at.
I would remove the bit about "what you aim to touchdown roughly at." VREF should be the speed you are at at the 50 foot height. With a normal flare, touchdown should occur at approx 96% of VREF.

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VSW                  | Airbus for when the stall warning will activate, represented by a black and red strip at the bottom of the airspeed indicator, when there has been a failure to affect the fli
Instead of "when there has been a failure to affect the flight control laws," I suggest "when the normal flight control law is inoperative" or "when operating in pitch alternate or pitch direct law" to be consistent with the FCOM (and "failure to affect" is not what is meant I hope).

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VX                   | Speed of Best Angle of Climb
Speed "for" Best Angle of Climb

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| VαMAX                | Airbus for the speed that the maximum angle of attack (AoA) can be without the aircraft stalling, shown by the top of a red strip at the bottom of the airspeed indicator.
Not exactly correct. There is some margin in the max AoA allowed by the flight envelope protection system such that you could reach a slightly higher AoA without stalling.  Probably better to say that it's the speed for the maximum angle of attack (AoA) that the pilot can achieve in normal law, shown by the top of a red strip...

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| JFGW                 | Jettison Final Gross Weight         |
Since the A320 cannot jettison fuel, is there any need to include this acronym?

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| V/S V1 V1 V2     | Vertical Speed                                         |
V1 V1 V2 don't belong here, do they?

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| RPM              | Rotation Per Minute                                    |
Also "Revolutions Per Minute"  (never heard of Rotations Per Minute)

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| TOR              | Takeoff Run                                            |
There is also TORA - Takeoff Run Available

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| TOD              | Takeoff Distance                                       |
There is also TODA - Takeoff Distance Available

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| LD               | Lower Deck                                             |
There are also LD - Landing Distance and LDA - Landing Distance Available

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| RF               | Radio Frequency                                        |
There is also RLD - Required Landing Distance

2021-11-10 10:12 UTC, donstim commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| FL               | Flight Level                                           |
There is also FLD - Factored Landing Distance

2021-11-10 10:59 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| F                    | Minimum speed at which the flaps may be retracted at takeoff (i.e., CONF 2/3). Also the minimum speed in approach when in CONF 2 or 3                         |
Would you mind providing a little more context?

2021-11-10 11:53 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/abbreviations.md
> +| JFGW                 | Jettison Final Gross Weight         |
also removed jettison lower down on the list

2021-11-10 12:08 UTC, Valastiri commented
The page has been moved out of the beginner guide directory and now exists in the main pilot's corner directory as the last navigation entry.

2021-11-22 18:42 UTC, Valastiri commented
Note: Pre-merge add page to `pilots-corner` overview as an internal link

2021-12-05 03:42 UTC, merged