feat: implement documentation on the a32nx code structure
flybywiresim/docs pull request #269
Opened 2021-10-28 20:53 UTC by BlueberryKing

## Summary

This PR provides a basic overview of the code structure of the A32NX project.

### Location

`docs/dev-corner/dev-guide/specific/structure.md`

Discord username (if different from GitHub): BlueberryKing#6641

2021-12-04 10:34 UTC, frankkopp commented
@BlueberryKing - I'm sorry but I had to hard reset this branch and then force push it back here. It was totally broken as it has not been updated for a while. Best would be to save your page, check it out clean and put your page back in.

2021-12-04 11:57 UTC, BlueberryKing commented
Alright, not a problem, will have a look!

2021-12-08 20:45 UTC, frankkopp commented
@BlueberryKing  I have re-targeted this PR to primary as I have merged the Development Guide and removed the other branch.
Either do a reset and the put your page back or a rebase. I think a stash/reset/pop would be easiest.

2021-12-09 02:17 UTC, Valastiri commented
Fixed :)

2022-04-20 14:57 UTC, Valastiri requested changes
I would suggest that the title of the page be `# A32NX Code Structure` so it appears nicely in the navigation.

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/.pages
> +  - structure.md
Maybe move this above the `flypad-dev.md` so it comes after overview in the navigation.

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +- Autopilot, Fly-by-wire, and some engine-related systems in C++
Here probably choose to end each bullet point with or without a `.` just for consistency.

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +Before making a contribution to the project, it is a good plan to have a general idea of which of these categories the change would fall into. For most people (including me, the author of this articl
```suggestion
Before making a contribution to the project, it is a good plan to have a general idea of which of these categories the change would fall into. For most people (including me, the author of this page), this will probably be a change to the displays. However, this might not always be the case.
```

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +In the `a32nx` top-level directory, we can see a bunch of configuration files and folders concerning mostly the build pipeline and documentation. This part is used to get the source code into the sim
I would remove the `code block` from the two folders mentioned at the end of this paragraph and turn them into internal links i.e. [flybywire-aircraft-a320-neo](#).

Is there a functional reason when writing documentation to leave the trailing `/` for the directory in question i.e. indicating further items within it or something fo the sort?

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +### The `flybywire-aircraft-a320-neo/` folder
```suggestion
### The flybywire-aircraft-a320-neo/ Folder
```

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +#### `html_ui/`
```suggestion
#### html_ui/
```

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +#### Other folders
```suggestion
#### Other Folders
```

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +### The `src/` folder
```suggestion
### The src/ Folder
```

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +# FAQ
```suggestion
## FAQ
```

Just a note on mkdocs-material h1 = `# header` defines the page itself. So a secondary h1 will not show up in the ToC hence this change.

2022-04-20 14:57 UTC, Valastiri commented on docs/dev-corner/dev-guide/specific/structure.md
> +This is the heart of the project, most of the logic is contained in this folder. In it, we can also find representatives of the three main aspects mentioned above. Namely, `instruments/` for displays
Considering you use bullet points below consider moving this into bullet points as well. Since it's a little confusing to read. The notable ones can stay as bullet points.

```suggestion
This is the heart of the project, most of the logic is contained in this folder. In it, we can also find representatives of the three main aspects mentioned above.

- `instruments/` for displays, 
- `systems/` for -- you guessed it -- systems
- `fadec/` and `fbw/` for the Fly-by-wire and FADEC systems. 

Most of the subfolders here are self-explanatory, however, we will point out some notable ones.
```

2024-09-29 08:32 UTC, closed without merging