Update faq.md
flybywiresim/docs pull request #27
Opened 2021-03-07 23:00 UTC by FoxinTale

Added the experimental version as a thing to the faq page.

2021-03-07 23:58 UTC, Valastiri requested changes

2021-03-07 23:58 UTC, Valastiri commented on docs/start/faq.md
> +A: We have three versions, the Stable , Developer (Master), and Experimental. The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator
Possibly Formatting Change + extra space between "stable" and "the comma".

```suggestion
A: We have three versions, the Stable, Developer (Master), and Experimental. 

* The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator. 

* The Developer build is updated daily and is a constant work in progress and although we test thoroughly each update, minor issues may occur from time to time. 

* The Experimental version contains the custom fly-by-wire.  If you find this to be the case, you can report these issues in #help in discord or via GitHub Issues (Check there is not an existing issue of the same nature as yours). No support via Discord is provided for the Experimental version.
```

Copy Suggestions is to match -> https://discord.com/channels/738864299392630914/757387126173204540/812092866784526376

Or see my pin in #help 

Also add the links to both discord and github issues in line if you're going to keep it.

2021-03-07 23:58 UTC, Valastiri commented on docs/start/faq.md
> +A: We have three versions, the Stable , Developer (Master), and Experimental. The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator
```The Developer build is updated daily and is a constant work in progress and although we test thoroughly each update, minor issues may occur from time to time.```

The sentence structure here also probably should be broken up.

2021-03-07 23:58 UTC, Valastiri commented on docs/start/faq.md
> +A: We have three versions, the Stable , Developer (Master), and Experimental. The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator
Final fact, this entire .md was pulled from FAQ section of the main repo. Feel free to spread things out with formatting since end-user readablity is the goal. (Without the line breaks it's a great wall of text to read).

2021-03-08 00:25 UTC, FoxinTale commented on docs/start/faq.md
> +A: We have three versions, the Stable , Developer (Master), and Experimental. The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator
Done the changes suggested, aside form adding line breaks. Not sure how to do those in markdown.

2021-03-08 03:57 UTC, Valastiri commented on docs/start/faq.md
> +A: We have three versions, the Stable , Developer (Master), and Experimental. The Stable version is a 'snapshot' of the development which we regard as stable with the current version of the simulator
It's just "double enter" to create an empty line between points. But with bullets that's automatic. 

Could also do <br> with no close and that will work too. 

I'll build and check this out in a bit.

2021-03-08 04:39 UTC, Valastiri approved these changes

2021-03-08 04:40 UTC, merged