feat:Added new Advanced Guides section to Pilot's Corner
flybywiresim/docs pull request #317
Opened 2021-11-24 12:53 UTC by frankkopp

closes #361

## Summary
New section for Advanced A320 features not covered in the Beginner Guide. 
Meant as a loose collection of features along the current development. 
More structure can and will be introduced when necessary.

Moved AFloor and Fix Info features guides there.

### Location
Pilot's Corner

Discord username (if different from GitHub): Cdr_Maverick#6475

2021-11-24 20:45 UTC, Valastiri commented
need 2 CC the bot team to update links -- unless temporary redirects first

2021-11-26 05:33 UTC, Benjozork commented
Make sure we still mention A. FLOOR outside of this / link to the adv guide in common issues

2021-11-28 11:52 UTC, Valastiri requested changes

2021-11-28 11:52 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/overview.md
> +### Selected modes
Managed modes has a `:` while selected doesn't -- possible typoe?

2021-11-28 11:52 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-phases.md
> +The GO-AROUND phase is activated when the thrust levers are moved to the TOGA position. The FMS then guides the aircraft through the missed approach procedure.
While probably not necessary specify that it's thrust levers to TOGA when on approach?

2021-11-28 11:52 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/afloor.md
> +When the angle of attack and airspeed of the aircraft reaches the alpha floor protection range indicated by the yellow and black band on the PFD speed page. Simply put A.FlOOR will trigger when appro
```suggestion
When the angle of attack and airspeed of the aircraft reaches the alpha floor protection range indicated by the yellow and black band on the PFD speed page. Simply put, A.FlOOR will trigger when approaching a stall in the aircraft's current configuration.
```

2021-11-28 11:53 UTC, Valastiri commented
Forgot to mention -- should we include "feature currently INOP" on some of the protections / features? Mostly like say Go Around is not fully implemented and sometimes requires resetting a CRZ level on the prog page?

2021-11-29 19:33 UTC, Valastiri approved these changes

2021-11-29 20:03 UTC, Valastiri commented
- [ ] Fix Info requires a typo change in #overview -> raduises to "radii"

2021-11-29 23:26 UTC, merged