FAQ Changes
flybywiresim/docs pull request #336
Opened 2021-12-06 21:54 UTC by GhostEagle68

Fixes #223

## Summary
Change some FAQ to make it match the current status.

### Location
https://docs.flybywiresim.com/fbw-a32nx/support/faq/#general

Discord username (if different from GitHub): GhostEagle68#0030

2021-12-08 07:31 UTC, Valastiri requested changes
I also think this page should reside under `/fbw-a32nx`.

You can update the `.pages` file for it to appear under the installation guide in terms of the navigation structure. I can then use this page for other marketing duties.

2021-12-08 07:31 UTC, Valastiri commented on docs/fbw-a32nx/support/faq.md
> +    Liveries working for the default A320neo will not be compatible with the A32NX. We recommend downloading your liveries from [Flightsim.to](https://flightsim.to/c/liveries/flybywire-a32nx/){target
```suggestion
    Liveries for the default A320neo will not be compatible with the A32NX. We recommend downloading compatible liveries from [Flightsim.to](https://flightsim.to/c/liveries/flybywire-a32nx/){target=new}.
```

2021-12-08 07:31 UTC, Valastiri commented on docs/fbw-a32nx/support/faq.md
> +    Yes, we have one available for our Stable, Development, and Experimental versions where you can find the most updated profiles by visiting our Simbrief Airframes [here](../installation.md#simbrie
```suggestion
    Yes, we have one available for our Stable, Development, and Experimental versions. You can find the most updated profiles by visiting our Simbrief Airframes [here](../installation.md#simbrief-airframe).
```

2021-12-08 07:31 UTC, Valastiri commented on docs/fbw-a32nx/support/faq.md
>      **Stable**
I think for this entire section you can direct the user to our Versions and Features page. Would remove the need for updating this section for any other existent reason.

For the `Q: What is the exp version?`

I suggest adding a link to "Please read more at [exp.md]" since that page will always be updated.

2021-12-08 18:26 UTC, GhostEagle68 commented
> I also think this page should reside under `/fbw-a32nx`.
> 
> You can update the `.pages` file for it to appear under the installation guide in terms of the navigation structure. I can then use this page for other marketing duties.
Which .pages file exactly and do I need to drag it under a section?

2021-12-08 20:34 UTC, frankkopp commented
> > I also think this page should reside under `/fbw-a32nx`.
> > You can update the `.pages` file for it to appear under the installation guide in terms of the navigation structure. I can then use this page for other marketing duties.
> 
> Which .pages file exactly and do I need to drag it under a section?

fbw-a32nx/support/.pages - remove the faq.md line
fbw-a32nx/.pages - add the line
move the page
check with "mkdocs build" for broken links and fix them (better to have an IDE do it for you - let me know if I should do it)

Consider if we need a redirect from the old url to the new - redirects are in mkdocs.yml

Let me know if I should do all this :)

2021-12-10 04:34 UTC, Valastiri commented
Approving for now but one final thing maybe: 
![image](https://user-images.githubusercontent.com/1619968/145517738-0c422f18-65ae-44a9-ad43-88c29b51f174.png)
Move the page below version and features. And as an initial pass this already lgtm.

2021-12-10 04:34 UTC, Valastiri approved these changes

2021-12-12 14:50 UTC, Valastiri commented
Actually lgtm for now. Thanks for the work any further changes we'll adjust as necessary.

2021-12-12 14:50 UTC, merged