docs: New page for Wheel Chocks and GSE Safety Cones
flybywiresim/docs pull request #338
Opened 2021-12-07 10:24 UTC by frankkopp

## Summary
New page for Wheel Chocks and GSE Safety Cones
https://github.com/flybywiresim/a32nx/pull/6286/checks
Closes #328

### Location
Feature Guides

Discord username (if different from GitHub): Cdr_Maverick#6475

2021-12-08 22:21 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/chocks-cones.md
> +If chocks are in place there will be brake force is applied to the aircraft so it should not move even when the parking brake is disengaged.
```suggestion
If chocks are in place there will be brake force applied to the aircraft so it should not move even when the parking brake is disengaged.
```

2021-12-20 11:47 UTC, Valastiri requested changes
![image](https://user-images.githubusercontent.com/1619968/146762620-6c6c050e-c749-46ca-b319-b82e8fa1e125.png)
Maybe also update .pages so it's in the correct alphabetically (minus the flypad nestled pages)

2021-12-20 11:47 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/chocks-cones.md
> +The flight crew activates the Wheel Chocks and Safety Cones in the flyPad EFB. This simulates asking the ground crew to place or remove the chocks or cones. The ground crew will then (virtually) dete
```suggestion
Other than just looking gorgeous the wheel chocks even apply some braking force to hold the aircraft in place.

The flight crew activates the Wheel Chocks and Safety Cones through the flyPad EFB. This simulates asking the ground crew to place or remove the chocks or cones. The ground crew will then (virtually) determine if chocks and cones should be placed or removed based on specific criteria, which are described in the next section.
```

2021-12-20 11:47 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flyPad/ground.md
> +- Airplane is on `GND`
Maybe actually state "Airplane is on the ground". Little unsure of phrasing here -- same goes for line 64. (Matches the feature-guide page.

2021-12-20 11:47 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/chocks-cones.md
> +# Wheel Chocks and<br/>GSE Safety Cones
```suggestion
# Wheel Chocks and GSE Safety Cones
```

I don't think we should break H1's -- unless this is some formatting thing on the front end?

![image](https://user-images.githubusercontent.com/1619968/146762561-b0f70fe2-520d-45ea-9738-82589d1d2dbf.png)
Breaks the Tab Title

2021-12-20 23:50 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/chocks-cones.md
> +# Wheel Chocks and<br/>GSE Safety Cones
True did it because of the left navigation - looked better to break a defined place - didn't see the tabs title though (my tabs are too narrow because I have too many open :D)

2021-12-21 00:05 UTC, frankkopp commented
> Maybe also update .pages so it's in the correct alphabetically (minus the flypad nestled pages)

It is using the filename and not the title :(
Renamed the file

2022-01-01 14:14 UTC, bouveng requested changes

2022-01-01 14:14 UTC, bouveng commented on docs/fbw-a32nx/feature-guides/flyPad/ground.md
```suggestion
- Airplane speed = 0kts
```

2022-05-11 19:58 UTC, Valastiri commented
From bouveng changes in Discord:

> Engines are off (ENG1+2 N2 < 1%) is changed to Engines are off (ENG1+2 N1 < 3.5%)
> and added to that list:
> Airplane is not moving / rolling

2022-05-11 22:49 UTC, Valastiri approved these changes

2022-05-11 23:01 UTC, Valastiri commented
check build

2022-05-11 23:47 UTC, merged