docs: New page for MCDU Web Interface
flybywiresim/docs pull request #343
Opened 2021-12-09 15:30 UTC by frankkopp

## Summary
New page for MCDU Web Interface
https://github.com/flybywiresim/a32nx/pull/3467
Closes #342 

### Location
Feature Guides

Discord username (if different from GitHub): Cdr_Maverick#6475

2021-12-11 18:29 UTC, tyler58546 commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +## How to Use the MCDU Web Interface
Add something here about how you can view just the screen without the buttons by tapping the top line or adding `/fullscreen` to the url. You can exit this mode by tapping anywhere.

2021-12-11 22:56 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +## How to Use the MCDU Web Interface
Will do on Monday.

2021-12-14 11:28 UTC, Valastiri requested changes
Preliminary draft review.

2021-12-14 11:28 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +!!! warning "Disclaimer"
```suggestion
!!! danger "Disclaimer"
```
Probably use the danger admon here - mostly because of the critical nature of firewall editing.

2021-12-14 11:28 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +Just use ++ctrl+left-button++ on the `localhost`link in the command window and it should open the MCDU Web Interface in your default browser.
```suggestion
Just use ++ctrl+left-button++ on the `localhost` link in the command window and it should open the MCDU Web Interface in your default browser.
```

2021-12-14 11:28 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +    The IP address shown for the remote device might be incorrect. The tool pics the first local address it finds put there is a chance that you need to use a different ip address to reach your PC.
```suggestion
    The IP address shown for the remote device might be incorrect. The tool chooses the first local address it finds put there is a chance that you need to use a different IP address to reach your PC.
```
You can use "chooses" or fix the typo in "picks".

2021-12-14 11:28 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +If you choose to use your real printer the press ++y++ after which you need to select which printer you want to use. The MCDU Server will list all printers available in your Windows.
```suggestion
If you choose to use your real printer then press ++y++, after which you need to select which printer you want to use. The MCDU Server will list all printers available in your Windows.
```

2021-12-20 12:07 UTC, Valastiri requested changes
Minor typos and suggestions.

2021-12-20 12:07 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +If you chose a local printer during the start of the MCDU Server every prints you will make from the MCDU to the cockpit printer will instead by printed using your previously selected printer.
```suggestion
If you chose a local printer when starting the MCDU Server, every print you will make from the MCDU to the cockpit printer will instead be printed using your previously selected printer.
```

2021-12-20 12:07 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +If you want only the MCDU display to be shown then tap on the top-most part of the MCDU display. To return to full MCDU view tap anywhere on the display.
```suggestion
If you want only the MCDU display to be shown then tap on the top-most part of the MCDU display. To return to the full MCDU view tap anywhere on the display.
```

2021-12-20 12:07 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +The printers available are those known to the PC where you run Microsoft Flight Simulator and the MCDU Server on. It is not relevant if your remote device where you use the MCDU Web Interface actuall
```suggestion
The printers available are those known to the PC where you run Microsoft Flight Simulator and the MCDU Server is on. It is not relevant if your remote device where you use the MCDU Web Interface actually knows this printer.
```

2021-12-20 12:07 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +- websocket-port:
Put this in a danger admon (or some part of it) so it's very clear that users should not mess with this setting. Reference the next section as well maybe with more disclaimers if necessary.

2021-12-20 12:07 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +[How Do I Open a Port on Windows Firewall?](https://www.howtogeek.com/394735/how-do-i-open-a-port-on-windows-firewall/){target=new}
```suggestion
[Opening a Port on Windows Firewall Instructions](https://www.howtogeek.com/394735/how-do-i-open-a-port-on-windows-firewall/){target=new}
```

Quick suggestion here to change the link title to be different OR turn it into a button so it looks clean. Kinda looks like a header (even tho it's a link).

2021-12-22 06:16 UTC, ssewell commented
Being able to explicitly set the width and height (or aspect ratio) of the display in fullscreen mode would be a great feature for us cockpit builders, allowing minor adjustments to fit the appropriate line-select positions on real-world LCD panels.

2021-12-23 07:13 UTC, Valastiri approved these changes

2021-12-25 07:21 UTC, tyler58546 requested changes

2021-12-25 07:21 UTC, tyler58546 commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +    Details see in chapter [Browser on Remote Device](#browser-on-remote-device)
This bug appears to be fixed so I think we should take this part out.

2021-12-25 09:32 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +    Details see in chapter [Browser on Remote Device](#browser-on-remote-device)
Can do. 

Thought of leaving it in until more tests were in. Should be good now.

2021-12-26 04:28 UTC, tyler58546 commented on docs/fbw-a32nx/feature-guides/web-mcdu.md
> +    To find your correct IP address follow this guide: [How to Find Your IP Address on Windows 11](https://www.howtogeek.com/744082/how-to-find-your-ip-address-on-windows-11/){target=new}
```suggestion
The MCDU Server command window tries to detect your IP address. Use the `http://xxx.xxx.xxx.xxx:8125` address and enter it into your browser on the remote device.

??? note "Unknown IP Address (click to expand)"
    Sometimes the MCDU Server is not able to detect your IP address.
    To find your correct IP address follow this guide: [How to Find Your IP Address on Windows 11](https://www.howtogeek.com/744082/how-to-find-your-ip-address-on-windows-11/){target=new}
```

2021-12-26 17:22 UTC, tyler58546 approved these changes

2021-12-29 10:08 UTC, merged