feat: preflight page in beginner guide
flybywiresim/docs pull request #354
Opened 2021-12-17 08:29 UTC by Valastiri

Closes #348 

## Summary

See linked issue for more information. 

Organizational page for pilot actions.

### Location

- docs/pilots-corner/beginner-guide/preflight.md

Discord username (if different from GitHub): Valastiri#8902

2021-12-19 23:08 UTC, frankkopp requested changes
Sorry for the many comments and suggestions.
Could have changed the PR directly but I noticed it too late.

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +MSFS Nav Data is updated during their patching process. It's important to take stock of what nav data you are currently using and if it matches the current AIRAC cycle. When using simBrief without a
```suggestion
The AIRAC cycle (nav data version) of MSFS's nav data is updated during MSFS's regular sim updates. It's important to take stock of what nav data AIRAC cycle you are currently using for your flight planning and if it matches the current AIRAC cycle in MSFS. When using simBrief or other planning tools with older nav data AIRAC cycles you may encounter `NOT IN DATABASE`, `AWY/WPT Mismatch` OR the [flight plan import](#flight-plan-import) may fail due to outdated/incorrect AIRAC cycle. 
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +We highly recommend **not** using the built-in MSFS flight planner. SimBrief is a great resources that provides routing and other information to successfully plan your flight. You can choose to use o
```suggestion
We highly recommend **not** using the built-in MSFS flight planner (World Map). We recommend using [SimBrief](https://www.simbrief.com/){target=new} as it is a great resource that provides routing and other information to successfully plan your flight. You can choose to use other software/websites to plan your route but when using simBrief we have a handy import feature as seen in the next section. Also other tools often don't have the most current nav data AIRAC cycle available. 
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +## Flight Plan Discontinuities
```suggestion
### Flight Plan Discontinuities
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +[EFB Navgraph](../../fbw-a32nx/feature-guides/flyPad/charts.md){.md-button}
```suggestion
[EFB Navigraph](../../fbw-a32nx/feature-guides/flyPad/charts.md){.md-button}
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +To help with navigation during your flight our flyPad EFB can connect to your Navigraph account to provide access to all of your enroute charts!
```suggestion
To help with navigation during your flight our flyPad EFB can connect to your Navigraph account to provide access to all of the required charts for your flight!
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +Owning a Navigraph subscription gives you access to their standalone nav data addon for MSFS that pairs with their simBrief flight planning. Not only does it provide you with an up-to-date AIRAC alon
```suggestion
Owning a Navigraph subscription gives you access to their standalone nav data addon for MSFS that pairs with their simBrief flight planning. It will provide you with an up-to-date AIRAC alongside any revisions, and it will ensure compatibility when importing from simBrief or planning your flight manually.
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +    - [SimBrief Website](https://www.simbrief.com/) (Flight Planning)
```suggestion
    - [SimBrief Website](https://www.simbrief.com/){target=new} (Flight Planning) 
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +    - [Little Nav Map](https://albar965.github.io/littlenavmap.html) (Flight Planning and Charts)
```suggestion
    - [Little Nav Map](https://albar965.github.io/littlenavmap.html){target=new} (Flight Planning and Charts)
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +    - [ChartFox](https://chartfox.org/) (Charts)
```suggestion
    - [ChartFox](https://chartfox.org/){target=new} (Charts)
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +    - [Navigraph](https://navigraph.com/) (Flight Planning and Charts) <span style="color:red;">**Requires Subscription**</span>
```suggestion
    - [Navigraph](https://navigraph.com/){target=new} (Flight Planning and Charts) <span style="color:red;">**Requires Subscription**</span>
```

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +!!! info "MCDU Interaction Requires Aircraft to be Powered"
Why is this important? The screen would be dark otherwise :D

2021-12-19 23:08 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preflight.md
> +!!! info "Passengers and Baggage Require the Aircraft to be Powered"
Here as well - you can't load payload without power anyway - MCDU will be dark .
EFB is a different matter. Have never tried fueling without power :)

2021-12-20 11:05 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/preflight.md
> +We highly recommend **not** using the built-in MSFS flight planner. SimBrief is a great resources that provides routing and other information to successfully plan your flight. You can choose to use o
Switched "also" for "additionally" in final sentence

2021-12-20 11:07 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/preflight.md
> +!!! info "MCDU Interaction Requires Aircraft to be Powered"
Removing them and edited the intro paragraph

2021-12-21 00:20 UTC, frankkopp approved these changes

2021-12-24 12:17 UTC, merged