docs(issues): add installer livery module error
flybywiresim/docs pull request #405
Opened 2022-01-12 01:08 UTC by Valastiri

## Summary

### Location

- docs/fbw-a32nx/support/reported-issues.md

Discord username (if different from GitHub): Valastiri#8902

2022-01-12 11:00 UTC, Valastiri commented
pending #support-ops consideration + possible additions to PR

2022-01-15 22:17 UTC, frankkopp requested changes

2022-01-15 22:17 UTC, frankkopp commented on docs/fbw-a32nx/support/reported-issues.md
> +??? tip "Ailerons When Using the Keyboard"
I would move this completely to the Fixed section as it is no longer an issue for users.

2022-01-15 22:17 UTC, frankkopp commented on docs/fbw-a32nx/support/reported-issues.md
> +## FBW Installer Issue
```suggestion
## FBW Installer Issues
```

2022-01-15 22:17 UTC, frankkopp commented on docs/fbw-a32nx/support/reported-issues.md
> +    Please delete the flybywire folder in your community folder and redownload the aircraft.
```suggestion
    Please delete the flybywire folder in your community folder and redownload the aircraft.
    
    This should only be necessary once. 
```

2022-01-16 11:11 UTC, frankkopp approved these changes

2022-01-16 11:15 UTC, merged