docs: Created documentation page for Hoppie ACARS System
flybywiresim/docs pull request #422
Opened 2022-02-02 22:43 UTC by frankkopp

Closes #421

## Summary
Feature Guide for Hoppie ACARS System

- [x] Draft
- [ ] Expand
- [ ] New Screenshots and imageoptimization
- [ ] Review

### Location
Feature Guides

Discord username (if different from GitHub): Cdr_Maverick#6475

2022-02-04 11:44 UTC, Valastiri commented
check build

2022-02-05 07:24 UTC, Valastiri requested changes
Suggestions + Changes

2022-02-05 07:24 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/hoppie.md
> +    This plan might change at any time.
Maybe state first what features "are currently available" and then what is planned after?

2022-02-05 07:24 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/hoppie.md
> +It allows a communication from ATC stations with the aircraft without the use of voice, but it is still required that the pilot monitors the voice frequency.
```suggestion
It allows communication between ATC stations and the aircraft without the use of voice, but it is still required that the pilot monitors the voice frequency.
```

2022-02-05 07:24 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/hoppie.md
> +!!! warning "Not available in the Stable Version"
```suggestion
!!! warning "Not available in the Stable Version"

!!! warning "Requires use and credentials with Hoppie service"
```

Maybe include this at the top feel free to adjust the admon as you see fit.

2022-02-05 07:24 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/hoppie.md
> +A complete list can be found [here](http://www.hoppie.nl/acars/system/online.html).
```suggestion
A complete list can be found [here](http://www.hoppie.nl/acars/system/online.html){target=new}.
```

2022-02-05 07:28 UTC, Valastiri commented
Reference: https://github.com/flybywiresim/a32nx/pull/6451

2022-02-05 09:11 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/hoppie.md
> +    This plan might change at any time.
will do

2022-02-06 08:34 UTC, Valastiri approved these changes

2022-02-07 15:31 UTC, merged