docs: Docs update for migration of MCDU Server to local-api
flybywiresim/docs pull request #469
Opened 2022-03-01 15:40 UTC by frankkopp

## Summary
Docs update for migration of MCDU Server to local-api

### Location
Feature Guide

Discord username (if different from GitHub): Cdr_Maverick#6475

2022-03-19 02:32 UTC, Valastiri approved these changes
Minor suggestions / Corrections -- otherwise lgtm

2022-03-19 02:32 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +If you still can't connect to the MCDU server your firewall might block the traffic. See next chapter.
```suggestion
If you still can't connect to the MCDU server your firewall might be blocking the traffic. See next chapter.
```

2022-03-19 02:32 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +    Changing Windows settings, especially security settings like the firewall comes with certain risks. Please do not change these settings if you are not comfortable doing so. FlyByWire Simulations
```suggestion
    Changing Windows settings, especially security settings like the firewall comes with certain risks. Please do not change these settings if you are not comfortable doing so. FlyByWire Simulations does not take any responsibility for any issues caused by your changes to Windows or security settings.
```
Change the "voice" here so that it's less us not wanting to take responsibility and just out right don't (when config'in system critical things). Use this at will.

2022-03-19 02:32 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +    When you start the server and and it crashes immediately with an error message mentioning `...Encoding not recognized...` you Windows most likely uses a rare UTF-8 based encoding.
```suggestion
    When you start the server and and it crashes immediately with an error message mentioning `...Encoding not recognized...` your Windows OS most likely uses a rare UTF-8 based encoding.
```

Is it most likely or "most likely isn't using" since the encoding is not recognized? Change as necessary but see grammar change.

2022-03-22 13:14 UTC, Lucky38i requested changes
Just a few changes but LGTM

2022-03-22 13:14 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +It will also host services like the Remote MCDU Server to access the aircraft's MCDU via a browser from any device connected to the network.
just to specify, `to the local network`

2022-03-22 13:14 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +**You will need to keep this window open and the Local API Server running to use the MCDU Web Interface**.
How about `You will need to keep the Local API server running to use remote web interfaces and local file features like coroutes`

2022-03-22 13:14 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +The Local API configuration file can be found here:
```The Local API configuration file can be found in the `resources` folder of the addon```

2022-03-22 13:14 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +
A note just mentioning the configuration is subject to change as more features are added to the local-api

2022-03-22 13:14 UTC, Lucky38i commented on docs/pilots-corner/advanced-guides/data-management.md
> +- Rename the simBrief XML Datafile to any name with maximal 9 characters. E.g. `EDDSEKCH.xml`
```E.g. the airport's IATA codes `STRCPH1.xml` ``` This is to better promote what pilot's are used to seeing, but they can really rename it to whatever they want.

2022-03-22 13:14 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +
Something like `Please send us the latest logfile to the support channel on discord or on github issues if you're facing issues using the Local API's features`

2022-03-22 13:14 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +The log is also stored in a file in this folder:
`The log file is also stored in a file in this folder, formatted by date`

2022-03-22 22:09 UTC, frankkopp commented on docs/fbw-a32nx/feature-guides/local-api-server.md
> +
We should try to keep this docs page updated then

2022-03-24 12:45 UTC, Lucky38i approved these changes

2022-08-01 12:40 UTC, Valastiri commented
@frankkopp can we close this?

2022-08-01 12:42 UTC, frankkopp commented
> @frankkopp can we close this?

@Valastiri assuming you copied everything from here into the others PRs then yes.

2022-08-01 22:19 UTC, Valastiri commented
> > @frankkopp can we close this?
> 
> @Valastiri assuming you copied everything from here into the others PRs then yes.

Will verify and also cc: @Lucky38i just to double check and save time.

2022-09-15 09:17 UTC, frankkopp commented
Closing - as this is in SimBridge docs now - CoRoutes can still be pulled out after close if required

2022-09-15 09:17 UTC, closed without merging