Docs: Feat holds
flybywiresim/docs pull request #471
Opened 2022-03-01 18:02 UTC by Sven-Janssens

Fixes #450 

## Summary
New guide to holds

### Location
(https://docs.flybywiresim.com/pilots-corner/advanced-guides/holds)

discord: Sven Janssens#6905

2022-03-08 21:51 UTC, Valastiri commented
Can you remove line 41 from `mkdocs.yml`?
This one below:
```yml
      exclude:
        - pilots-corner/advanced-guides/flight-planning/holds.md
```
It'll be needed for the merge anyways and allows quick lookup when checkout ur preview thru vercel. Thanks!

2022-03-17 22:46 UTC, frankkopp requested changes
I'm not a big fan of the tabs component. In my view it makes the page less readable and harder to divide into subsection which could be part of the in-page navigation.

I would especially avoid it for the programming hold part. A bullet point list would be much better in this case.

2022-03-17 22:46 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holding patterns , as they are officialy known, can be used as a delaying tactic for airborn aircraft. Typically holding patterns have a racetrack pattern and can easily be spotted on flight trackers
```suggestion
Holding patterns, as they are officially known, can be used as a delaying tactic for airborne aircraft. Typically holding patterns have a racetrack pattern and can easily be spotted on flight trackers. All holds are made up out of segments, the segments are shown in the figure below. 
```

The last sentence doesn't explain much. Also maybe explain in general that pilots should be able to fly holds manually and know how to correctly enter and fly it them. The AP is just a convenience feature to reduce the pilot's workload.

2022-03-17 22:46 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +### Why hold?
Headlines always with English headline capitalization - this tool helps :)
https://capitalizemytitle.com/

```suggestion
### Why Holds?
```

2022-03-17 22:46 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holdings are typically used to delay aircraft, or less common, to burn of fuel for landing.
There are several additional reasons - e.g. weather, traffic, to loose altitude, etc.

2022-03-17 22:46 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Aircraft can technically hold, if given permission by ATC in advance, at any waypoint. Holds that are published on aviation charts are called published holds. For the purpose of this guide we will on
```suggestion
Aircraft can technically hold at any waypoint, if given permission by ATC in advance. Holds that are published on aviation charts are called published holds. For the purpose of this guide we will only take a published hold into consideration. Holds can be spotted on charts in 2 ways where both options can be applied on the same chart. For example look at the chart below. 
```

2022-03-17 22:46 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> + Eather the inbound course/heading or the reciprocal of the hold is always depicted on the chart.
```suggestion
 Either the inbound course/heading or the reciprocal of the hold is always depicted on the chart.
```

2022-03-17 22:46 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Now all information of the hold is known it is time to create a hold in the FMS via the MCDU. A step by step guide to hold at SKENS as with example chart 6 (above) is provided below.
```suggestion
Now that all information of the hold is known it is time to create a hold in the FMS via the MCDU. A step by step guide to hold at SKENS as with example chart 6 (above) is provided below.
```

2022-03-17 22:49 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holding patterns , as they are officialy known, can be used as a delaying tactic for airborn aircraft. Typically holding patterns have a racetrack pattern and can easily be spotted on flight trackers
will incorporate the comment

2022-03-17 22:50 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holdings are typically used to delay aircraft, or less common, to burn of fuel for landing.
will find a fix for it

2022-03-17 22:51 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Aircraft can technically hold, if given permission by ATC in advance, at any waypoint. Holds that are published on aviation charts are called published holds. For the purpose of this guide we will on
will incorporate the comment

2022-03-17 23:36 UTC, Valastiri reviewed
Small changes

Full feature review would be later just some things I noticed. Other things discussed in DMs for formatting can be done later.

2022-03-17 23:36 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holding patterns, as they are officially known, can be used as a delaying tactic for airborne aircraft. Typically holding patterns have a racetrack pattern and can easily be spotted on flight tracker
```suggestion
Holding patterns, as they are officially known, can be used as a delaying tactic for airborne aircraft. Typically holding patterns have a racetrack pattern that can easily be spotted on flight trackers and navigational charts. All holds are made up out of segments, the segments are shown in the figure below. 
```
suggestion only

2022-03-17 23:36 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holds are always used to 'hold' aircraft roughly on the same place. There are a lot of reasons airplanes might need to hold, some more common examples are:
```suggestion
Holds are always used to delay aircraft near a navigational fix in certain airspace. There are a lot of reasons airplanes might need to hold, some more common examples are:
```

Could mention it's a maneuver as well. Just generally bad to define a word with itself. i.e. "Hold is a Hold"

2022-03-17 23:36 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +4. Length of the legs, eather in time or distance
```suggestion
Now that you know where to hold, you should know how to set up the hold. To do this you will need to find information on the chart and move it into the FMS. The main information you need to have is:

1. Name of the fix/waypoint
2. Inbound course
3. Turning direction
4. Length of the legs, eather in time or distance
```
Need empty space - list broken

2022-03-17 23:36 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> + Below you will find samples of diffrent holds with red dots placed where the information is located.
```suggestion
 Below you will find samples of different holds with red dots placed where the information is located.  
```

2022-03-17 23:37 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holds are always used to 'hold' aircraft roughly on the same place. There are a lot of reasons airplanes might need to hold, some more common examples are:
Could use better phrasing in my suggestion as well just more of an interim change.

2022-04-16 08:51 UTC, Valastiri requested changes
Image optimization noted. See Discord DMs to facilitate.

Heading suggestions as per issues at top of page (can move this around later):

```
# Overview
## Why Hold?
## Identifying Holds
## Hold Standards
## Programming Holds <- this separates the holding stuff from the standards before it
### MCDU Setup (maybe change this later but could come with new formatting)
### Descending in the Hold
### Leaving the Hold
```
Edited above.
Please ensure capitalization as indicated above.

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holds are always used to delay aircraft near a navigational fix in certain airspace. There are a lot of reasons airplanes might need to hold, some more common examples are:
```suggestion
Holds are always used to delay aircraft near a navigational fix in certain airspace. There are a lot of reasons airplanes might need to hold, where common examples would be:
```

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Sometimes holds are used because of topographical constraints, Innsbruck-Kranebitten International Airport (LOWI) is a good example of such constraint because is situated in a vally as can be seen in
```suggestion
Sometimes holds are used because of topographical constraints, Innsbruck-Kranebitten International Airport (LOWI) is a good example of such constraint because it is situated in a valley as can be seen in the picture below.
```

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Aircraft can technically hold at any waypoint, if given permission by ATC in advance. Holds that are published on aviation charts are called published holds. For the purpose of this guide we will onl
```suggestion
Aircraft can technically hold at any waypoint if given permission by or requested from ATC in advance. Holds that are published on aviation charts are called published holds. For the purpose of this guide, we will only take a published hold into consideration. Holds can be identified on charts in 2 different ways, where both options can be applied on the same chart. For example look at the chart below. 
```

You mention example chart below but there's text that follows. Missing example?

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Now that you know where to hold, you should know how to set up the hold. To do this you will need to find information on the chart and move it into the FMS. The main information you need to have is:
```suggestion
Now that you know where to hold, you should know how to program the hold. To do this you will need to find information on the chart and move it into the FMS. The main information you need to have is:
```
Maybe use program by default instead of set up -- check other cases. This is a suggestion.

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +*There are standards for length of legs and airspeeds that have to be respected if no other information is present on the chart. The standards are published in [Hold Standards](#hold-standards).
```suggestion
!!! tip "Standards"
    There are standards for length of legs and airspeeds that have to be respected if no other information is present on the chart. The standards are published in [Hold Standards](#hold-standards).
```
This creates the green "tip" admonition or a green line to identify supporting information. (More of a formatting thing). Note asterisk changes in the list above this.

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +5. Maximum airspeed*
```suggestion
4. Length of the legs, eather in time or distance (see Standards below)
5. Maximum airspeed (see Standards below)
```
If using the admonition in the review comment below - identify here instead of the asterisk.

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        As can be seen in the chart in example 6 above, the hold has a leg length of 10NM. To enter this in the FMS type '/10' in the MCDU and select LSK3 to feed it in the TIME/DIST box.
```suggestion
        As can be seen in the chart in example 6 above, the hold has a leg length of 10NM. To enter this in the FMS type `/10` in the MCDU and select LSK3 to feed it in the TIME/DIST box. 
```

I would also group the same chart here to make more sense and stop reading from having to jump back and forth.

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        ![MCDU](../../assets/advanced-guides/holds/MCDU-hold-7.png)
Possibly draw squares on the images ... just realized this. Would help users quickly identify what to look at in images. See TCAS or other examples throughout docs. (Or ask Mav or me).

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Altitude changes are done with the vertical speed mode set at 1000 ft/min. This is to make sure all aircraft are spaced out enough to comply with spacing safety standards/
Is this automatically commanded by the AP or manually commanded on the FCU? I can't remember. If it is better to state it as such.

2022-04-16 08:51 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +The plane will continue to fly in the hold until a pilot gives the command to the FMS to leave. During the hold the F-PLN page will display IMM EXIT in amber. To leave the hold all a pilot has to do
```suggestion
The plane will continue to fly in the hold until a pilot gives the command to the FMS to leave. During the hold the F-PLN page will display IMM EXIT in amber. To leave the hold the pilot has to press the right LSK next to IMM EXIT. The amber text will now change in RESUME HOLD. The aircraft will complete the remaining hold lap and continue its flightplan when it reaches the hold fix again. 
```
Maybe quickly explain what resume hold does in another paragraph. I removed it because it might be confusing to the user saying it twice.

2022-04-18 13:38 UTC, frankkopp requested changes
I think that is a good guide! Good work.

Some small things as mentioned and all images need to be optimized:
- as small a possible - see table of image size I sent on Discord
- Compressed (see link to tool I sent) 
- most of these should be well below 100kB

2022-04-18 13:38 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +- To burn of fuel
```suggestion
- To burn off fuel
```

2022-04-18 13:38 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        | Fix           | Inbound course   |Turning direction   |Leg distance   |Max speed   |Max alt|Min Alt (MHA)  |
If you transpose these tables it would not show a horizontal navigation bar.
E.g.:
Fix | ARNUM
Inbound Course | 216°
....

2022-04-18 13:38 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +    === "1"
I'm still not a fan of tabs :)

2022-04-29 12:11 UTC, Sven-Janssens commented
> Image optimization noted. See Discord DMs to facilitate.
> 
> Heading suggestions as per issues at top of page (can move this around later):
> 
> ```
> # Overview
> ## Why Hold?
> ## Identifying Holds
> ## Hold Standards
> ## Programming Holds <- this separates the holding stuff from the standards before it
> ### MCDU Setup (maybe change this later but could come with new formatting)
> ### Descending in the Hold
> ### Leaving the Hold
> ```
> 
> Edited above. Please ensure capitalization as indicated above.

2022-04-29 12:22 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Aircraft can technically hold at any waypoint, if given permission by ATC in advance. Holds that are published on aviation charts are called published holds. For the purpose of this guide we will onl
yeah its in there now

2022-04-29 12:24 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Now that you know where to hold, you should know how to set up the hold. To do this you will need to find information on the chart and move it into the FMS. The main information you need to have is:
fixed now. please take a look aswell

2022-04-29 12:26 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +*There are standards for length of legs and airspeeds that have to be respected if no other information is present on the chart. The standards are published in [Hold Standards](#hold-standards).
done

2022-04-29 12:27 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +5. Maximum airspeed*
yeah thanks for that it is fixed now

2022-04-29 12:29 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        As can be seen in the chart in example 6 above, the hold has a leg length of 10NM. To enter this in the FMS type '/10' in the MCDU and select LSK3 to feed it in the TIME/DIST box.
done. please review the placement of the image

2022-04-29 12:30 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Altitude changes are done with the vertical speed mode set at 1000 ft/min. This is to make sure all aircraft are spaced out enough to comply with spacing safety standards/
i don't know, will jump in the sim later to find out. will get back on this

2022-04-29 12:31 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +The plane will continue to fly in the hold until a pilot gives the command to the FMS to leave. During the hold the F-PLN page will display IMM EXIT in amber. To leave the hold all a pilot has to do
great wording! thanks!

2022-04-29 12:33 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        | Fix           | Inbound course   |Turning direction   |Leg distance   |Max speed   |Max alt|Min Alt (MHA)  |
Do you mean just flipping the table from horizontal to vertical? stacking the items instead of next to eachother

2022-04-29 12:34 UTC, Sven-Janssens commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +    === "1"
I know. will think of another solution together

2022-05-03 06:11 UTC, tshomas commented
Val asked for a quick operational review, I’ll stick to the flying aspects on it!

1) Standard Holds, could possibly be added that the standard hold direction is with right hand turns, that’s the normal fmgc setup for a non published hold.

2) MCDU setup (8), wording for green dot speed needs looking at, possibly “green dot speed is the speed that the airbus burns the minimum amount of fuel”.

3) Also on the above page, unsure of the functionality in the addon, you could add a point that says about the “SET HOLD SPEED” if you stay in selected speed while the MCDU wants green dot. Effectively it’s just hit managed speed instead of selected to sort it.

4) Descending in the hold, completely correct, don’t know if with VNAV in now we want to say that DES should maintain -1000ft changing levels in the hold, but personally haven’t tested it yet so don’t know if that functionality is in the addon yet. BLW would be the more common TCAS setting but both would work.

5) Leaving the hold, IMM EXIT is described as being that it will “complete the remaining hold lap”. This shouldn’t be the case as it will actually fly the shortest distance to the original hold waypoint and then exit, such as doing a tight circle or turning early on downwind. Other options to leave the hold are also to CLEAR the HOLD in the FMGC or to do a DIR to the waypoint but these are a bit messy. It can be quite common to either get a heading to leave the hold or be told “next time overhead the waypoint, then do X”, which would require you to wait before pressing anything, and then hit IMM EXIT when inbound to the fix.

6) I was asked about formatting, looks good on mobile which is all I can test it on at this moment, table for the hold examples has a scroll but it’s not too hard to work with.

7) In your notes:
Yeah entry pattern techniques may be a bit advanced and a bit messy to add in.
Titles are a bit messy as you say, rank is a bit odd still as things like Preparing the MCDU is a higher rank with descending in the hold inside of that it looks like, maybe a mix of preparations vs flying to separate them down.

Looks really nice though, love the examples of all different patterns and how to grab the info from the charts as I think that’ll benefit the users really well!

2022-05-05 10:07 UTC, Sven-Janssens commented
> Val asked for a quick operational review, I’ll stick to the flying aspects on it!
> 
> 1. Standard Holds, could possibly be added that the standard hold direction is with right hand turns, that’s the normal fmgc setup for a non published hold.
> 2. MCDU setup (8), wording for green dot speed needs looking at, possibly “green dot speed is the speed that the airbus burns the minimum amount of fuel”. The airbus will also slow down to green dot before the holding waypoint, ready for the hold, and IMM EXIT will appear before entering.
> 3. Also on the above page, unsure of the functionality in the addon, you could add a point that says about the “SET HOLD SPEED” if you stay in selected speed while the MCDU wants green dot. Effectively it’s just hit managed speed instead of selected to sort it.
> 4. Descending in the hold, completely correct, don’t know if with VNAV in now we want to say that DES should maintain -1000ft changing levels in the hold, but personally haven’t tested it yet so don’t know if that functionality is in the addon yet. BLW would be the more common TCAS setting but both would work.
> 5. Leaving the hold, IMM EXIT is described as being that it will “complete the remaining hold lap”. This shouldn’t be the case as it will actually fly the shortest distance to the original hold waypoint and then exit, such as doing a tight circle or turning early on downwind. Other options to leave the hold are also to CLEAR the HOLD in the FMGC or to do a DIR to the waypoint but these are a bit messy. It can be quite common to either get a heading to leave the hold or be told “next time overhead the waypoint, then do X”, which would require you to wait before pressing anything, and then hit IMM EXIT when inbound to the fix.
> 6. I was asked about formatting, looks good on mobile which is all I can test it on at this moment, table for the hold examples has a scroll but it’s not too hard to work with.
> 7. In your notes:
>    Yeah entry pattern techniques may be a bit advanced and a bit messy to add in.
>    Titles are a bit messy as you say, rank is a bit odd still as things like Preparing the MCDU is a higher rank with descending in the hold inside of that it looks like, maybe a mix of preparations vs flying to separate them down.
> 
> Looks really nice though, love the examples of all different patterns and how to grab the info from the charts as I think that’ll benefit the users really well!

point 1,2 and 5 are changed in the doc

2022-05-05 10:12 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        | Fix           | Inbound course   |Turning direction   |Leg distance   |Max speed   |Max alt|Min Alt (MHA)  |
Yup move the identifiers to the left column and supporting information to the right.

2022-05-21 02:01 UTC, dirtyformal commented
Val has asked me to have a quick review of this, with the aim of progressing it soon.

Most of the content itself is awesome, and I think it gives the people reading it a solid footing in how to conduct it properly - nice work.

I second @frankkopp's comments above - the tabs within the admonitions seems a little off to me. I would even suggest putting them under an "Examples" header, and removing them from the admonition. 

**Identifying Holds** - Do we really need ten examples here? Further - I think the notes (Tabs 2, 4, 5 and 10) should be placed underneath the table. This way it doesn't interrupt the viewer's natural reading flow.

**Programming Holds - MCDU Setup** - Same with the above. Remove it from the admonition, and put it under its own 'Examples' header. 

**Video Example** - I would suggest adding another top-level header "Video Example", with a simple link to the video. I don't think an embed is necessary.

**Hold Examples** - I'm unsure what this section achieves, that isn't already achieved in either the Identifying Holds or Programming Holds section. Suggest removal.

**The end "Standards" admonition** - Would suggest moving this out of an admonition and into the "Hold Standards" section. The Hold Standards section could do with this extra context, and having it as an admonition at the bottom of the page isn't the most pertinent location for it.

Happy to discuss through Discord- DF#8008

2022-08-27 16:49 UTC, frankkopp approved these changes

2022-08-28 04:08 UTC, tracernz requested changes

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +The FAA defines the standard hold direction for non-published holds with **right-hand** turns.
The Airbus FMS follows ICAO definitions, not FAA.
```suggestion
The Airbus FMS follows ICAO definitions for default holding pattern parameters. The default leg length for a computed hold is:

| Altitude (ft MSL)  | Leg distance |
|-------------------|--------------|
| <=14000           | 1 minute     |
| > 14000           | 1.5 minutes  |

The managed speed target in a hold is the lowest of:
- maximum endurance (approximately "green dot" speed)
- ICAO speed limit (see table below)
- speed constraint
- speed limit, if below speed limit altitude

The ICAO speed limits are as follows:

| Altitude (ft MSL) | Airspeed (KIAS) |
|-------------------|-----------------|
| < 14000           | 230             |
| 14000 - 20000     | 240             |
| 20000 - 34000     | 265             |
| > 34000           | .83 Mach        |

The default turn direction for a computed hold is **right**, in-line with ICAO specifications. 
```

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +        Before the A320 passes the hold fix for the first time, it will slow down to 'green dot speed'. This is the speed at which the aircraft uses the minimum fuel per hour to ensure it can stay in
```suggestion
        The FMS calculates the holding speed in accordance with [Hold Standards](#hold-standards) to acheive the lowest possible fuel consumption, except in approach phase where the "characteristic" speed for the current configuration is used. A deceleration point is calculated giving enough distance before the hold fix to slow down to the holding speed. From this point IMM EXIT becomes available on the F-PLN page, and pressing it prior to actually reaching the hold fix will cause deletion of the hold. If speed is managed the deceleration will begin automatically; if speed is selected a SET HOLD SPEED prompt will appear, prompting the pilot to set their desired holding speed, or to engage managed speed.
```

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Altitude changes are done with the vertical speed mode set at 1000 ft/min. This is to make sure all aircraft are spaced out enough to comply with spacing safety standards.
```suggestion
Managed descent mode (DES) in the hold will limit the descent rate to a maximum of -1000 ft/min for traffic separation purposes. Open descent (OP DES) will descend at idle thrust as normal.
```

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +RESUME HOLD can be pressed to cancel the hold exit. The aircraft will now stay in the hold, and IMM EXIT is shown again.
```suggestion
```suggestion
The plane will continue to fly in the hold until a pilot gives the command to the FMS to leave by either activating a direct to (DIR TO), or pressing the IMM EXIT prompt on the F-PLN page. During the hold, and prior to the hold after crossing the deceleration point, the F-PLN page will display IMM EXIT prompt in amber. The pilot may press the right LSK next to IMM EXIT to leave the hold. The aircraft will shorten the hold as much as possible, fly around until reaching the hold fix, and then exit, continuing with the subsequent flight plan. At any time prior to reaching the hold fix the RESUME HOLD prompt may be used to re-enable the hold.
```
```

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Holding patterns, as they are officially known, can be used as a delaying tactic for airborne aircraft. Typically holding patterns have a racetrack pattern that can easily be spotted on flight tracke
```suggestion
Holding patterns, as they are officially known, can be used as a delaying tactic for airborne aircraft, for course reversal, and for gaining altitude prior to crossing terrain in some procedures. Typically holding patterns have a racetrack pattern that can easily be spotted on flight trackers. All holds are made up of segments. The segments are shown in the figure below. 
```

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +- To lose energy in the plane (altitude or speed)
```suggestion
- To gain or lose energy in the plane (altitude or speed)
```

2022-08-28 04:08 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +
```suggestion
- To reverse the course of the aircraft prior to entering a final approach

```

2022-08-29 07:58 UTC, frankkopp commented
@tracernz thanks - awesome review!!

Accepted all and will go over everything one more time

2022-08-29 16:40 UTC, Valastiri commented
I would hazard a couple things here:

- Programming holds should really be it's own page. reference maybe the vnav docs. Could add a button at the top of the page in admonition or not to signify this.
- Could also just break the entire thing outside of the admonition with tabs. We already have long pages and the table of contents is there for this specific reason. 
  - Could utilize a top of the page contents table if needed?

2022-08-29 16:44 UTC, Valastiri reviewed
Additional notes

2022-08-29 16:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +```suggestion
Unsure of the use / reason for the code block here that's not closed.

2022-08-29 16:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +<iframe width="826" height="465" src="https://www.youtube.com/embed/NYlSICln1So" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
```suggestion
![video-embed](https://www.youtube.com/embed/NYlSICln1So)
```
Cleaner and utilizes our plugin installed.

2022-09-05 01:37 UTC, tracernz commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +!!! warning "Not available in the Stable Version"
I don't think this is true anymore? [The code is there in v0.8.2](https://github.com/flybywiresim/a32nx/blob/v0.8.2/src/fmgc/src/guidance/lnav/legs/HX.ts).

2022-09-08 10:09 UTC, merged