feat: tcas documentation
flybywiresim/docs pull request #472
Opened 2022-03-03 14:27 UTC by Valastiri

fixes: #294 

## Summary
Expands upon the TCAS page to provide information on how the system works alongside known issues.

Proposed Outline:

- [x] Overview
- [x] TA Description
- [x] RA Description
- [x] AP/FD TCAS Implementation / Description
- [ ] Above Behaviours
- [ ] Pilot actions / commands
- [ ] Additional Considerations?

## TODO
- [ ] Requires Images
- [ ] List behaviours
- [ ] A32NX current capabilities

### Location

- docs/pilots-corner/advanced-guides/flight-guidance/tcas.md

Discord username (if different from GitHub): Valastiri#8902

2022-03-05 18:55 UTC, frankkopp requested changes

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
>  Our TCAS supports online network traffic services (Vatsim / IVAO).
I think Live traffic as well

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Traffic Collision Avoidance System (TCAS) is a system available on Airbus aircraft that help reduce airborne collisions and risks. Numerous improvements have been made to this system over the years t
```suggestion
The Traffic Collision Avoidance System (TCAS) is a system available on Airbus aircraft that helps to reduce the risk of airborne collisions. Numerous improvements have been made to this system over the years that enhance the pilot interface and decrease non-optimum pilot handling of advisories from TCAS. The FlyByWire A32NX uses the AP/FD TCAS mode function developed by Airbus.
```

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +- Traffic Advisory (TA)
Would add short explanation of TA and RA. 
And is "procedures" the right term?

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +
Screenshot of panel?

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +For more information on how ensure TCAS is active for your flight and the corresponding controls please see the [ATC TCAS PANEL](../../a32nx-briefing/flight-deck/pedestal/atc-tcas.md) page.
```suggestion
For more information on how to ensure TCAS is active for your flight and the corresponding controls please see the [ATC TCAS PANEL](../../a32nx-briefing/flight-deck/pedestal/atc-tcas.md) page.
```

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +    The operating flight crew should always be able to take command of hte aircraft manually by disconnecting the autopilot and flight directors to respond to a TCAS RA by flying the verticial speed
```suggestion
    The operating flight crew should always be able to take command of the aircraft manually by disconnecting the autopilot and flight directors to respond to a TCAS RA by flying the aircraft at a verticial speed outside of the red zone in the vertical speed indicator.
```

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Essentially this feature allows the flight crew to resolve TCAS RAs using the autopilot and flight directors engaged. It is also entirely possible to complete a TCAS RA maneuver manually by using the
```suggestion
Essentially this feature allows the flight crew to resolve TCAS RAs using the autopilot. It is also entirely possible to complete a TCAS RA maneuver manually by using the flight director guidance with the autopilot switched off as well. The major benefit of this system is to provide optimal maneuvers when a conflict arises.
```

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +- Visual amber cues on the navigation display (ND providing information about the potential threat
There 4 icons, right? White outline, white, amber abd red.

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +When a traffic advisory becomes a collision threat an RA is generated. AP/FD TCAS shines in this regard allowing for fully automated flight in the case of an RA. Pilots will now have additional infor
```suggestion
When a traffic advisory becomes a collision threat an RA is generated. AP/FD TCAS shines in this regard allowing for fully automated flight in the case of an RA. Pilots will now have additional information provided to them on the primary flight display (PFD) and navigation display (ND) depending on what actions the flight crew needs to perform to clear the conflict. 
```

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +#### Corrective
This might need some rephrasing. I did not understand everything :D

2022-03-05 18:55 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +[Safe Handing of TCAS Alerts](https://safetyfirst.airbus.com/safe-handling-of-tcas-alerts/){.md-button primary}
```suggestion
[Safe Handing of TCAS Alerts](https://safetyfirst.airbus.com/safe-handling-of-tcas-alerts/){.md-button primary target=new}
```

2022-03-08 16:19 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +#### Corrective
i'm assuming it's the audible alert bullet point I've made changes to this

2022-03-08 16:19 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +
I'll pull this from the pilot briefing pages

2022-03-08 16:20 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +- Traffic Advisory (TA)
I added a short description but I am unsure of procedure I'll have it verified when ready_for_review

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Our TCAS supports online network traffic services (Vatsim / IVAO) and the live traffic feature in MSFS.
What does this not support? AI traffic? If so, let's call it out.

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +The Traffic Collision Avoidance System (TCAS) is a system available on Airbus aircraft that helps to reduce the risk of airborne collisions. Numerous improvements have been made to this system over t
Not exclusive to Airbus. It's mandatory on all passenger airliners in the major western countries.

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Essentially this feature allows the flight crew to resolve TCAS RAs using the autopilot. It is also entirely possible to complete a TCAS RA maneuver manually by using the flight director guidance wit
I think structurally this part (both the warning and the AP/FD integration) should come later. Let's first explain what a TA and an RA even is, before we're like "WARNING PILOTS MUST ALWAYS BE ABLE TO MANUALLY FLY TCAS RAs"

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +- "*Traffic, Traffic*" aural warning
The "Traffic, Traffic" callout is clearly the most noticeable and most distinctive part of a TA. I would put it first.

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +
Let's add a paragraph here detailing the outcome, something like this:

> The TA will remain active for as long as the threat remains. A TA will always result in one of two things:
> - Once the predicted flight paths of the aircraft or the aircraft themselves are no longer in proximity, TCAS will issue a "Clear of Conflict"
> - If the threat increases, because the aircraft are predicted to approach too close to each other, TCAS will upgrade the Traffic Advisory to a Resolution Advisory.

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Once a TA is triggered the AP/FD TCAS will arm itself to notify the crew (alongside other visual cues noted above). This ensures that if the intruder would turn into a threat that would trigger an RA
Let's be more specific about all the actions that should be done. You should chat to real pilots about this, but:

- The pilot monitoring should check the ND for the location of the threatening traffic. It may be necessary to increase the zoom level of the ND to below 60nm (double-check this number)
- The pilot monitoring should attempt to establish visual contact with the nearby aircraft, if possible, to assess the flight path visually
- The pilot should check the FMA to check whether AP/FD TCAS is armed. If not, they must be ready to swiftly disengage the autopilot and manually follow the TCAS orders, once the TA upgrades to a Resolution Advisory

2022-03-13 11:38 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +When a traffic advisory becomes a collision threat an RA is generated. AP/FD TCAS shines in this regard allowing for fully automated flight in the case of an RA. Pilots will now have additional infor
Let's first talk about what even a Resolution Advisory is, before talking about how great AP/FD TCAS is. We can do that by adding a second sentence with something like this: "A RA requires the pilot to immediately follow the commanded action by TCAS. RAs always have priority over ATC commands, especially when they conflict with ATC."

2022-03-13 14:45 UTC, beheh commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Our TCAS supports online network traffic services (Vatsim / IVAO) and the live traffic feature in MSFS.
I see now you do it at the end of the document. Maybe that's good enough then? I'm not quite clear on what this sentence tries to do here though. If it's to warn people of cases where it might work, the negative case might be more helpful.

2022-03-13 19:53 UTC, tshomas commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +The Traffic Collision Avoidance System (TCAS) is a system available on Airbus aircraft that helps to reduce the risk of airborne collisions. Numerous improvements have been made to this system over t
Agree with this, the Airbus part makes it sound exclusive whereas it’s been mandatory across airliners for years?

2022-03-13 21:42 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +
I'm adding this almost verbatim as it's already well written :)

2022-03-13 21:55 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +When a traffic advisory becomes a collision threat an RA is generated. AP/FD TCAS shines in this regard allowing for fully automated flight in the case of an RA. Pilots will now have additional infor
Added a little more here based on FCTM

2022-03-13 22:17 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Our TCAS supports online network traffic services (Vatsim / IVAO) and the live traffic feature in MSFS.
Changed the wording to link to the section instead.

2022-03-13 22:18 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +Once a TA is triggered the AP/FD TCAS will arm itself to notify the crew (alongside other visual cues noted above). This ensures that if the intruder would turn into a threat that would trigger an RA
Added two entirely new sections here based on external resources. Will have this verified.

2022-03-13 22:21 UTC, Valastiri commented
Would still need to add / write up a table with the various aural warnings.

2022-03-16 17:26 UTC, Valastiri commented
Added the following:
- Clear of conflict mini section
- Aural Messages Table
- Cleaned up copy / grammar
- Cleaned up Pilot Actions

2022-03-19 01:37 UTC, frankkopp approved these changes
Some minor suggestions. Otherwise LGTM

2022-03-19 01:37 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +The initial implementation of TCAS features the AP/FD TCAS function and is available in the Development version.
```suggestion
The TCAS system is not available in the Stable version at this time.
```

2022-03-19 01:37 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +For more information on how to ensure TCAS is active for your flight and the corresponding controls please see the [ATC TCAS PANEL](../../a32nx-briefing/flight-deck/pedestal/atc-tcas.md) page.
```suggestion
Make sure that the ATC system is on `AUTO` or `ON` and the `ALT RPTG` knob is in position `ON`. The TCAS mode switch should be in position `TA/RA` when entering the runway for takeoff. 

For more information on how to ensure TCAS is active for your flight and the corresponding controls please see the [ATC TCAS PANEL](../../a32nx-briefing/flight-deck/pedestal/atc-tcas.md) page.
```

2022-03-19 01:37 UTC, frankkopp commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +    - A V/S of 0 ft/min is always within the safe zone for a corrective RA which allows for TCAS to capture a targeted flight level if capture conditions are met
I don't understand this sentence. How can 0 ft/min be always in the safe zone?

2022-03-20 14:07 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +    - A V/S of 0 ft/min is always within the safe zone for a corrective RA which allows for TCAS to capture a targeted flight level if capture conditions are met
Discussed in DM's will update copy + add a small graphic to make more clear.

2022-03-21 03:35 UTC, Benjozork requested changes

2022-03-21 03:35 UTC, Benjozork commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +- Vatsim
```suggestion
- VATSIM
```

2022-03-21 11:36 UTC, beheh approved these changes

2022-03-23 21:21 UTC, merged