docs: Update to Texture Docu - bandit, elevator, logo
flybywiresim/docs pull request #513
Opened 2022-03-30 21:00 UTC by frankkopp

Closes #503 
Coses #512

## Summary
UPdated texture documentation

### Location

Discord username (if different from GitHub): Cdr_Maverick#6475

2022-03-30 21:25 UTC, frankkopp commented
@bouveng ready to review :)

2022-03-31 01:59 UTC, Valastiri requested changes
Typo's and a question

2022-03-31 01:59 UTC, Valastiri commented on docs/dev-corner/texture-changes.md
> +The fill and outline color or the elevator trim scale, is configured in the `DECALS_BANDIT_WINDOW_ALBD.PNG.DDS` texture.
```suggestion
The fill and outline color of the elevator trim scale, is configured in the `DECALS_BANDIT_WINDOW_ALBD.PNG.DDS` texture.
```

2022-03-31 01:59 UTC, Valastiri commented on docs/dev-corner/texture-changes.md
> +We have added a mesh between the fwd doors and the cockpit, to ease with high quality logos, stickers, etc.
```suggestion
We have added a mesh between the forward doors and the cockpit, to ease with high quality logos, stickers, etc.
```
I don't understand the "to ease" portion ... does it mean "to easily integrate high quality [...]"?

2022-03-31 07:42 UTC, merged