Add on the on the ground to beginners guide
flybywiresim/docs pull request #54
Opened 2021-04-20 23:06 UTC by Awemeter

Adds on the ground/after landing part of the beginners guide

2021-04-21 02:44 UTC, Awemeter commented on docs/beginner-guide/after-landing-steps.md
> +    * Continue with the [Powering Down](TBD.MD) steps
Who ever makes the parking page you will need to change this the TBD.MD to the file name

2021-04-21 13:31 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    * Continue with the [Powering Down](TBD.MD) steps
This is actually not needed. The mkdocs has a next page function built in.

2021-04-21 14:34 UTC, Awemeter commented on docs/beginner-guide/after-landing-steps.md
> +    * Continue with the [Powering Down](TBD.MD) steps
Ok

2021-04-21 15:01 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    * Set your radio frequency to the one assigned by atc if using atc
```suggestion
  * Set your radio frequency to the one assigned by ATC
    * ATC is set in accordance with airport requirements.
```

2021-04-21 15:03 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    !!! info "Exterior Lights"
The info block is probably not needed here. You haven't used it anywhere else and the bullet points should suffice.

2021-04-21 15:04 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +=== "Turning into gate"
```suggestion
=== "Turning into gate"
=== "Turning Into Gate"
```

2021-04-21 15:06 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    * Turn your ati-ice off if not needed
```suggestion
    * Turn your ati-ice off if not needed
    * Turn off your anti-ice if it is not required
```

2021-04-21 15:12 UTC, Valastiri commented
Ensure all acronyms are capitalized. i.e. ECAM, ATC, etc.

2021-06-14 01:45 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    * Continue with the [Powering Down](TBD.MD) steps
Can you do `[Powering Down](#)` just so there's no strange build errors

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +        * ATC is set in accordance with airport requirements
```suggestion
        * ATC is set in accordance with airport requirements
        
        ![Com panel](../assets/beginner-guide/after-landing-steps/landingLayer-3.png)
```

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +        ![Com panel](../assets/beginner-guide/after-landing-steps/landingLayer-3.png)
Remove this after moving it.

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    * Set your TCAS to STANDBY
```suggestion
    * Set your TCAS to STANDBY

        ![Tcas](../assets/beginner-guide/after-landing-steps/landingLayer-4.png)
```

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +        ![Tcas](../assets/beginner-guide/after-landing-steps/landingLayer-4.png)
Remove this after moving

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    ![landing light positions2](../assets/beginner-guide/after-landing-steps/After Landing-Taxi  Light .png)
```suggestion
    Your lights should look like one of the following:

    ^^**Lights Setup 1**^^

    ![landing light positions](../assets/beginner-guide/after-landing-steps/After landing-Lights.png)

    ^^**Lights Setup 2**^^

    ![landing light positions2](../assets/beginner-guide/after-landing-steps/After Landing-Taxi  Light .png)
```

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +=== "Left Side Overhead Panel"
```suggestion
=== "Overhead Panel"
```

I feel like this should just be overhead panel and move the following up here: 

* Start your APU by clicking the APU master button then the APU start button

* Turn OFF your anti-ice if it is not required

Could do those two first then exterior lights.

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +=== "Right Side Overhead Panel"
```suggestion
=== "Center Instrument Panel"
```

Remove the APU and anti-ice. Keep brake fans here as it's relevant.

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    Continue with the [Powering Down](TBD.MD) steps
```suggestion
    Continue with the [Powering Down](#) steps
```

2021-06-14 02:00 UTC, Valastiri commented on docs/beginner-guide/after-landing-steps.md
> +    * Continue with the [Powering Down](TBD.MD) steps
See updated review

2021-06-14 02:01 UTC, Valastiri requested changes
Some formatting and moving of images required. 

Also some section header changes for overhead panel as you have ECAM information in "right side overhead" see suggestions.

You also have a merge conflict.

2021-06-14 03:16 UTC, Valastiri approved these changes

2021-06-14 04:07 UTC, Valastiri commented
Reviewed by Dan + Imenes. 

Rebased by me. 

Thanks for the work looks good :)

2021-06-14 04:08 UTC, merged