docs(exp): add pause at TOD
flybywiresim/docs pull request #559
Opened 2022-05-09 17:18 UTC by Valastiri

## Summary
Supports A32NX PR for exp testing:
- https://github.com/flybywiresim/a32nx/pull/7165

Additionally makes note that the flyPadOS 3 is now released in Development.

### Location
- docs/fbw-a32nx/support/exp.md

Discord username (if different from GitHub): Valastiri#8902

2022-05-10 03:45 UTC, 2hwk commented
Add known Sim Limitation:

Note that while aircraft simulation is suspended (i.e. fuel consumption, airspeed, altitude, physics), environmental simulation will continue (Notably Live Weather, Live Traffic/AI Traffic). Consequences of this include that TCAS TA/RAs will still be issued and if there is a significant change in the weather over time (say a few hours), your vertical descent profile and performance figures may no longer be accurate, which means that the actual T/D point may now have shifted from the originally calculated value. 

The timestamp issued in the pause pop-up shows your real local system's time (localized to your locale) to help mitigate against this problem. 

This is considered a sim limitation as the pause event we utilize does not affect the MSFS world environment. Along this line of thinking, we speculate that without historical live weather and traffic, it would not possible to inject or restore the state that the world was in when the pause was initiated (the time slider in the weather toolbar only affects lighting and will still reflect live wind and weather data). 

Flying using a weather preset and without AI/live traffic avoids this limitation entirely, but would also be a compromise in other ways.

2022-05-20 12:11 UTC, Valastiri commented
Waiting for multiple EXP PRs to be pushed to development for A32NX

2022-05-31 19:25 UTC, Benjozork requested changes

2022-05-31 19:25 UTC, Benjozork commented on docs/fbw-a32nx/support/exp.md
>  Featured released in Development Version. See our guide for usage and known issues.
```suggestion
Feature released in Development Version. See our guide for usage and known issues.
```

2022-05-31 19:25 UTC, Benjozork commented on docs/fbw-a32nx/support/exp.md
> +Featured released in Development Version. See our guide for usage and known issues.
```suggestion
Feature released in Development Version. See our guide for usage and known issues.
```

2022-05-31 20:19 UTC, Valastiri commented
added sim limitation as admonition

2022-06-02 00:29 UTC, merged