Initial Commit
flybywiresim/docs pull request #603
Opened 2022-07-27 12:18 UTC by Lucky38i

## Summary

This PR aims to provide further documentation on Simbridge
### Location

Discord username (if different from GitHub): Lucky38i

2022-07-28 13:30 UTC, Valastiri commented
Self-note before merging:

Exclude Search:
- Terrain
- Company Routes
- PDF Viewer

Delist from nav temporarily as well

2022-07-28 19:36 UTC, Valastiri requested changes
Some tidbits:

- Since co-routes page is up do you still need that hidden for the time being or will the feature ship since you built the page? I'll make the changes for you if yes.
- We usually append {loading=lazy} to all images a little bandwidth saver.
	- I can do this for you if you need.
- All the images are good! I might run it through my lossy optimization cloud service just in case but the sizes seem fine (could try and shave off more). I'll do this when work on the issues in my previous comment on this PR.

Also is it safe to assume #469 is no longer needed with this PR?

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/autostart.md
> +Autostart is a feature provided by the Flybywire Installer that allows SimBridge to be autostarted upon Windows start. Simbridge will live in the systems tray similiar to Navigraph Simlink.
```suggestion
Autostart is a feature provided by the FlyByWire Installer that allows SimBridge to be autostarted upon Windows start. SimBridge will live in the systems tray similiar to Navigraph Simlink. 
```
Branding :)

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/autostart.md
> +Autostart is a feature provided by the Flybywire Installer that allows SimBridge to be autostarted upon Windows start. Simbridge will live in the systems tray similiar to Navigraph Simlink.
Probably check all mentions of SimBridge in text and replace (I see some on other pages). I commented on some already if it was part of something I was suggesting anyways.

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/autostart.md
> +- You may encounter issues with closing SimBridge in normal circumstance and thus you can kill the `fbw-simbridge.exe` process in Task Manager
```suggestion
- If you encounter issues when closing SimBridge normally, you can kill the `fbw-simbridge.exe` process in Task Manager.
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/configuration.md
> +![configuration](assets/simbridge/simbrideg_config.png)
While minor possibly fix the typo in the filename and update

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/configuration.md
> +    If SimBridge is running make sure to stop and then start the service in order for SimBridge to load the modified settings
add period to the end of sentences

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/configuration.md
> +  - You can modify Simbridge's hosted port
```suggestion
This tab is dedicated to settings regarding the SimBridge server itself.

- Port
  - You can modify Simbridge's hosted port
```

List broken when built.

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/configuration.md
> +  - A simple enable/disable option to enable or disable the printer function as a whole
```suggestion
## Printer Settings
This tab is for modifying settings regarding printing data from the MCDU to your physical printer.

- Enabled
  - A simple option to enable or disable the printer function as a whole
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/coroute.md
> +- Download the `XML Datafile' from simbrief
```suggestion
- Download the `XML Datafile' from simBrief
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/coroute.md
> +- Enter the name of your company route into the `CO RTE` field
```suggestion
- Start a flight at the appropriate departure airport and follow the standard setup procedure.
- When setting up the flight management system in the MCDU you can directly head to the INIT A page.
- Enter the name of your company route into the `CO RTE` field.
```

Rest of the list that follows has periods.

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/coroute.md
> +- **Alternatively** you can enter the FROM/TO pair of routes you have stored which will bring up the co-route selection page
```suggestion
- **Alternatively** you can enter the FROM/TO pair of routes you have stored which will bring up the co-route selection page.
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/index.md
> +|                   Remote Displays                   | Work in Progress (MCDU Built) |
We should probably link the Web MCDU (now remote display) still since we'll be marketing this feature. People might get confused until it's properly adapted (and might think SimBridge things need to be done)?

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/installation.md
> +Please follow the information on this page to install the FlyByWire SimBridge tools for FlyByWire aircraft
```suggestion
Please follow the information on this page to install the FlyByWire SimBridge tools for FlyByWire aircraft.
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/installation.md
> +FBW Installer  introduced the `Uninstall` feature. To perform an automatic clean install:
```suggestion
FBW Installer introduced the `Uninstall` feature. To perform an automatic clean install:
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/remote-displays/architecture.md
> +!!! info Note
```suggestion
!!! info "Note"
```

Admonition titles require "" otherwise it takes the default (in this case was Info)

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/remote-displays/configuration.md
> +A setting in the fylPad EFB Sim Options page has been introduced to allow users to restart the connection attempts or to turn off the attempts to connect to Simbridge completely.
```suggestion
A setting in the flyPad EFB Sim Options page has been introduced to allow users to restart the connection attempts or to turn off the attempts to connect to SimBridge completely.
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +    This window does not need to remain open and can be re-hidden using the system's tray icon
```suggestion
!!! info "Note"
    This window does not need to remain open and can be re-hidden using the system's tray icon.
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +!!! danger Disclaimer
```suggestion
!!! danger "Disclaimer"
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +If the port is indeed already occupied then you need to change the default port in [Simbridge Configuration](configuration.md#server-settings)
```suggestion
If the port is indeed already occupied then you need to change the default port in [Simbridge Configuration](configuration.md#server-settings).
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/autostart.md
> +- By right-clicking the tray icon in your systems tray and selecting `Exit`, you can also stop SimBridge
```suggestion
- By right-clicking the tray icon in your systems tray and selecting `Exit`, you can also stop SimBridge.
```

2022-07-28 19:36 UTC, Valastiri commented on docs/simbridge/remote-displays/architecture.md
> +    Manual configuration is not usually required
```suggestion
    Manual configuration is not usually required.
```

2022-07-28 20:00 UTC, pdellaert commented on docs/simbridge/troubleshooting.md
> +    This window does not need to remain open and can be re-hidden using the system's tray icon.
Suggest to add a warning or extra statement that explains that if the main window is closed using the Window Close button (X), Simbridge will stop entirely and it needs to be manually restarted. 

I suspect users might accidentally do this out of habit, instead of using the system tray icon.

2022-07-28 20:07 UTC, pdellaert commented on docs/simbridge/remote-displays/remote-mcdu.md
> +
Is a section or note needed about combining fullscreen & sound? (can it be done? If so, does `/fullscreen/sound` work as well as `/sound/fullscreen`?

2022-07-28 20:16 UTC, Lucky38i commented on docs/simbridge/configuration.md
> +![configuration](assets/simbridge/simbrideg_config.png)
fixed 40f9425cbb393242c3b8f46b055a3f9bba9ed89a

2022-07-28 20:16 UTC, Lucky38i commented on docs/simbridge/configuration.md
> +    If SimBridge is running make sure to stop and then start the service in order for SimBridge to load the modified settings
fixed 40f9425cbb393242c3b8f46b055a3f9bba9ed89a

2022-07-28 20:16 UTC, Lucky38i commented on docs/simbridge/index.md
> +|                   Remote Displays                   | Work in Progress (MCDU Built) |
added 40f9425cbb393242c3b8f46b055a3f9bba9ed89a

2022-07-28 20:16 UTC, Lucky38i commented on docs/simbridge/troubleshooting.md
> +    This window does not need to remain open and can be re-hidden using the system's tray icon.
added 40f9425cbb393242c3b8f46b055a3f9bba9ed89a

2022-07-28 20:16 UTC, Lucky38i commented on docs/simbridge/remote-displays/remote-mcdu.md
> +
added 40f9425cbb393242c3b8f46b055a3f9bba9ed89a

2022-07-28 20:20 UTC, Lucky38i commented
@Valastiri 
> Some tidbits:
>
>   Since co-routes page is up do you still need that hidden for the time being or will the feature ship since you built the 
>  page? I'll make the changes for you if yes.

Yes keep it hidden until we get https://github.com/flybywiresim/a32nx/pull/6411 merged

> 
>   We usually append {loading=lazy} to all images a little bandwidth saver.     
>   I can do this for you if you need.

sorted [40f9425](https://github.com/flybywiresim/docs/pull/603/commits/40f9425cbb393242c3b8f46b055a3f9bba9ed89a)

> All the images are good! I might run it through my lossy optimization cloud service just in case but the sizes seem fine (could try and shave off more). I'll do this when work on the issues in my previous comment on this PR.

sorted [40f9425](https://github.com/flybywiresim/docs/pull/603/commits/40f9425cbb393242c3b8f46b055a3f9bba9ed89a)

> Also is it safe to assume #469 is no longer needed with this PR?

I don't imagine so, but confirm with @frankkopp (Mav) just to make sure

2022-07-28 22:17 UTC, Valastiri approved these changes

2022-07-29 16:53 UTC, Valastiri commented
check build

2022-07-29 16:55 UTC, merged