Added rejected take-off page
flybywiresim/docs pull request #662
Opened 2022-09-28 21:20 UTC by SweatyCam

## Summary
Rejected take-off page for the advanced guides

### Location

Discord username (if different from GitHub): Sweaty Cam#3177

2022-11-28 14:17 UTC, Valastiri commented
Any update on this PR?

2022-12-04 21:34 UTC, SweatyCam commented
> Any update on this PR?

yes sorry, been way busy with work/uni, barely have time to fly. will update this soon

2022-12-10 12:03 UTC, Valastiri requested changes
some minor changes. Will verify use of `kt` vs `kts`.

2022-12-10 12:03 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +- Above 100 kt and below V1
I believe abbreviation in relation "knots" is `kts` as we've used in various other portions of our documentation. Double check the page and reference accordingly.

2022-12-10 12:03 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +      Because in the simulator most of the time you are on your own, the procedure has been condensed for a single pilot to perform. In real life operations, the procedures are split between the Capt
```suggestion
!!! note

      We have modified and condensed the rejected takeoff procedure to assist a single pilot to perform for simulation purposes. In real life operations, the procedures are split between the Captain and FO. 
```

2022-12-12 13:09 UTC, Valastiri requested changes
Also just to confirm images are all optimized yes?

2022-12-12 13:09 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +It is not possible to list all the factors that could lead to the decision to reject the takeoff. However, in order to help the Captain make a decision, the ECAM inhibits warnings that are not essent
```suggestion
It is not possible to list all the factors that could lead to the decision to reject the takeoff. However, in order to help the Captain make a decision, the ECAM inhibits warnings that are not essential passing 80 kts or 1500 ft (or 2 min after lift-off, whichever occurs first). When this occurs, a magenta T.O INHIBIT memo is displayed in the Upper ECAM (E/WD).
```

Please verify this as the statement is confusing in the original text. "not essential from 80 kt to 1500 ft" are two different units so using "to" is where the confusion happens. 

If the suggestion reads better to you just commit via github.

2022-12-12 13:09 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +    - Full reverse thrust may be used until coming to a complete stop. But, if there is enough runway available at the end of the deceleration, it is preferable to reduce reverse thrust when passing
Is there a thrust setting that is preferrable? i.e. reduce reverse thrust to idle -- or something else?

2022-12-12 22:17 UTC, Valastiri approved these changes

2022-12-12 22:17 UTC, Valastiri commented
check build

2022-12-12 23:30 UTC, merged

2022-12-13 00:21 UTC, donstim commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +The term rejected takeoff (also known as RTO) refers to incidents in which an aircraft's pilots elect to abort their departure before reaching a critical speed. This critical speed is known as 'V1',
Sorry, just finally looked at this, but the relevant distance is the accelerate-stop distance (the distance the airplane actually needs to accelerate and stop in accordance with the regulations). The accelerate-stop distance available (ASDA) is the length of runway and stopway that is available for an accelerate-stop and can be longer than the accelerate-stop distance.

2022-12-13 08:32 UTC, SweatyCam commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +The term rejected takeoff (also known as RTO) refers to incidents in which an aircraft's pilots elect to abort their departure before reaching a critical speed. This critical speed is known as 'V1',
> Sorry, just finally looked at this, but the relevant distance is the accelerate-stop distance (the distance the airplane actually needs to accelerate and stop in accordance with the regulations). The accelerate-stop distance available (ASDA) is the length of runway and stopway that is available for an accelerate-stop and can be longer than the accelerate-stop distance.

Right on, I’ll get that changed tonight

2022-12-13 10:42 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +The term rejected takeoff (also known as RTO) refers to incidents in which an aircraft's pilots elect to abort their departure before reaching a critical speed. This critical speed is known as 'V1',
I can probably correct this quickly. In an hour.

2022-12-13 16:32 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/rejected-take-off.md
> +The term rejected takeoff (also known as RTO) refers to incidents in which an aircraft's pilots elect to abort their departure before reaching a critical speed. This critical speed is known as 'V1',
Had a small snafu in my dev environment :/ corrective PR made already.