docs(simbridge): update remote-mcdu.md documentation to support QoL changes
flybywiresim/docs pull request #675
Opened 2022-11-12 20:16 UTC by Valastiri

## Summary
Supports changes made by SimBridge PR:

- https://github.com/flybywiresim/simbridge/pull/52

Information and images courtesy of @Nufflee and @auroraislunai respectively.

Commented out "how to find your IP Address" temporarily incase it may be required as *additional information* in the future.

### Location
- docs/simbridge/troubleshooting.md
- docs/simbridge/remote-displays/remote-mcdu.md

Discord username (if different from GitHub): Valastiri#8902

2022-11-12 21:03 UTC, Nufflee requested changes

2022-11-12 21:03 UTC, Nufflee commented on docs/simbridge/remote-displays/remote-mcdu.md
>  - Tray Icon
```suggestion
### Option 1: Tray Icon
```

I think this would look nicer, it looks a little confusing when it's a list item.

2022-11-12 21:03 UTC, Nufflee commented on docs/simbridge/remote-displays/remote-mcdu.md
>  - Web browser
```suggestion
### Option 2: Web Browser
```

Same as above.

2022-11-12 21:03 UTC, Nufflee commented on docs/simbridge/troubleshooting.md
> +        A recent update to Windows 11 made `windows terminal` the default console (replacing `console host`). Unfortunately, at this time `windows terminal` does not support being minmized to the tra
nit:
```suggestion
        A recent update to Windows 11 made `Windows Terminal` the default console (replacing `console host`). Unfortunately, at this time `Windows Terminal` does not support being minmized to the tray.
```

2022-11-12 21:03 UTC, Nufflee commented on docs/simbridge/remote-displays/remote-mcdu.md
> +- Open your browser of choice and navigate to http://{[IP Address](../troubleshooting.md#network-configuration)}:{[Port](../configuration.md#server-settings)}/interfaces/mcdu
```suggestion
- Open your browser of choice and navigate to http://{[Computer's Local IP Address](https://support.microsoft.com/en-au/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9)}:{[Port](../configuration.md#server-settings)}/interfaces/mcdu
```

Something along those lines, as discussed in Discord.

2022-11-12 21:39 UTC, Nufflee requested changes

2022-11-12 21:39 UTC, Nufflee commented on docs/simbridge/remote-displays/remote-mcdu.md
> +You can also directly open the Remote MCDU from the system tray by selecting "Open MCDU" in the context menu when using ++"Right Click"++ with your mouse.
```suggestion
You can directly open the Remote MCDU from the system tray by selecting "Open MCDU" in the context menu when using ++"Right Click"++ with your mouse.
```

2022-11-12 21:39 UTC, Nufflee commented on docs/simbridge/remote-displays/remote-mcdu.md
>  - Web browser
```suggestion
```

2022-11-12 21:39 UTC, Nufflee commented on docs/simbridge/remote-displays/remote-mcdu.md
> +- Open your browser of choice and navigate to http://{[Computer's Local IP Address](https://support.microsoft.com/en-au/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9){t
```suggestion
You can also open your browser of choice and navigate to `http://{[Computer's Local IP Address](https://support.microsoft.com/en-au/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9){target=new}}:{[Port](../configuration.md#server-settings)}/interfaces/mcdu`
```

2022-11-12 22:53 UTC, Nufflee requested changes

2022-11-12 22:53 UTC, Nufflee commented on docs/simbridge/troubleshooting.md
> +Your device should typically also have an IP Address starting with `192.168.1.x` in this case. (This is a good way to quickly verify that your remote device is even on the same network.)
```suggestion
Your device should typically have an IP Address starting with the same three sets of numbers (starting with 192.168.1 in this case). This is a good way to quickly verify that your remote device is even on the same network.
```

2022-11-12 22:53 UTC, Nufflee commented on docs/simbridge/troubleshooting.md
> -You can check this in the device's network configuration.
Put these 2 lines back to complement the above information.

2022-11-13 11:13 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> -You can check this in the device's network configuration.
Made the copy a little more verbose. 
![image](https://user-images.githubusercontent.com/1619968/201518790-0bcb9a74-dd34-4f5f-878d-1e55f29dd96a.png)

2022-11-13 17:35 UTC, frankkopp approved these changes
Make sure the image is optimized: 
https://www.websiteplanet.com/webtools/imagecompressor/

2022-11-13 20:00 UTC, Valastiri commented
> Make sure the image is optimized: [websiteplanet.com/webtools/imagecompressor](https://www.websiteplanet.com/webtools/imagecompressor/)

thanks forgot about this!

2022-11-18 13:32 UTC, merged