Simbridge Troubleshoot - FlyPad Settings
flybywiresim/docs pull request #682
Opened 2022-11-24 19:06 UTC by Oyu-De

## Summary

Adds images and guide on how to attempt a new connection to simbridge if it does not connect. "Sim Options - Simbridge Connection - Auto - off - Auto again
### Location

/simbridge/troubleshooting/#firewall-configuration
docs\simbridge\troubleshooting.md

Discord username (if different from GitHub): Oyu#1741

2022-11-24 19:07 UTC, Oyu-De commented
made it as draft rn, just wanna get initial review before making it an actual PR.

2022-11-25 06:54 UTC, Valastiri commented
Suggest highlighting relevant areas with a red box to show user what to click on along side the text. 

An example of the crossed out wifi could be handy as well.

2022-11-27 10:10 UTC, frankkopp approved these changes

2022-11-27 10:10 UTC, frankkopp commented on docs/simbridge/troubleshooting.md
> +    - To attempt connection : Simbridge Connection: Turn "AUTO" to "OFF" and "AUTO" again.
```suggestion
    - To attempt connection : Simbridge Connection: Turn "AUTO" to "OFF" for a few seconds and "AUTO" again.
```

I have noticed if you do it too quickly it sometimes doesn't take.

2022-11-28 13:57 UTC, Oyu-De commented on docs/simbridge/troubleshooting.md
> +    - To attempt connection : Simbridge Connection: Turn "AUTO" to "OFF" and "AUTO" again.
thx for the suggestion. added in https://github.com/flybywiresim/docs/pull/682/commits/5b36dc93da15e120a88306012f3fa283b11e6ef9

2022-11-28 20:36 UTC, Oyu-De commented
realised the "settings and then simbridge" is not the best screenshot/guide ever. will change it tomorrow to include both a
flypad settings -> sim options
simbridge "Auto" "Off" box

2022-11-28 21:53 UTC, frankkopp commented
> realised the "settings and then simbridge" is not the best screenshot/guide ever. will change it tomorrow to include both a flypad settings -> sim options simbridge "Auto" "Off" box

Updated the settings page for SimOptions anyway: https://github.com/flybywiresim/docs/pull/683
You can use the image there (copy) and add your arrow - I also have the original if you need it. 
You need to resize it then to 826px wide and optimize it with https://www.websiteplanet.com/webtools/imagecompressor/

2022-11-29 08:45 UTC, Oyu-De commented
> > realised the "settings and then simbridge" is not the best screenshot/guide ever. will change it tomorrow to include both a flypad settings -> sim options simbridge "Auto" "Off" box
> 
> Updated the settings page for SimOptions anyway: #683 You can use the image there (copy) and add your arrow - I also have the original if you need it. You need to resize it then to 826px wide and optimize it with https://www.websiteplanet.com/webtools/imagecompressor/

ah brilliant, thanks for the heads up and the link :)

2022-12-08 06:18 UTC, Valastiri requested changes
Unfortunately I can't see image sizes on mobile for some reason. I assume they are optimized can check later.

2022-12-08 06:18 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +- To attempt connection : SimBridge Connection: Turn "AUTO" to "OFF" for a few seconds and "AUTO" again.
This looks a little weird to read. Maybe do this instead?
```suggestion
To attempt connection:

- SimBridge Connection: Turn "AUTO" to "OFF" for a few seconds.
- Select "AUTO" again.
```

2022-12-08 06:18 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +Check the connectivity status on FlyPad by checking if the wifi icon on the top is crossed.
```suggestion
Check the connectivity status on the flyPad by checking if the wifi icon on the top is crossed.
```
Using EFB works as well. Branding is "flyPad".

2022-12-08 06:18 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +FlyPad will stop trying to connect to SimBridge after a 5 minute timer.
EFB here if you choose to use EFB on the lines below.

2022-12-08 13:19 UTC, Oyu-De commented
> Unfortunately I can't see image sizes on mobile for some reason. I assume they are optimized can check later.

np
also I just saw it, gotta update the PR so it fits with this https://github.com/flybywiresim/docs/pull/687
didnt realise it got merged

2022-12-15 22:29 UTC, Valastiri approved these changes

2022-12-15 22:29 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +EFB will stop trying to connect to SimBridge after a 5 minute timer.
```suggestion
The EFB will stop trying to connect to SimBridge after a 5 minute timer.
```

2022-12-15 22:29 UTC, Valastiri commented on docs/simbridge/troubleshooting.md
> +- If the wifi / connectivity icon is crossed, head to the flypad Settings --> Sim Options
```suggestion
- If the wifi / connectivity icon is crossed, head to the flyPad Settings --> Sim Options 
```

2022-12-15 22:40 UTC, Valastiri commented
check build

2022-12-15 22:44 UTC, merged