docs: Display "Incorrect Label" label below the image as done in other locations
flybywiresim/docs pull request #700
Opened 2022-12-18 23:27 UTC by auroraisluna

## Summary

This PR moves the "Incorrect Label" label from the bottom of the page, to below the image for consisentcy purposes, as other locations (e.g. [Cargo Smoke panel](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/flight-deck/ovhd/cargo-smoke/)) have this label exactly below the image.
- Potential issues: There are two labels back to back now (the API docs) however they are small enough, they should not be a problem 
- Alternative solution: Move the "Incorrect Label" to the bottom of the page in at least 'Cargo Smoke panel' page as mentioned above.

### Location

/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs

Discord username (if different from GitHub):
Alepouna🌙#9824

2022-12-19 12:37 UTC, Valastiri requested changes
Have two admonitions back to back isn't terrible -- since they are technically different with one having "content" and another being part of the overall title portion of the admonition.

You could opt to:

- Leave it as such
- Combined the two in a fashion
- Change the admonition type for the incorrect label to possibly "warning"

2022-12-19 12:37 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs.md
> +    Please note, the ADIR 1, 2 and 3 labels are incorrect. They should state ADR 1, 2 and 3.
```suggestion
!!! info "Incorrect Label"

    Please note, the ADIR 1, 2 and 3 labels are incorrect. They should state ADIR 1, 2 and 3.
```

Don't know why that works even though the formatting of the admonition was wrong -- also small typo I discovered.

2022-12-19 12:44 UTC, auroraisluna commented
I like the `Change the admonition type for the incorrect label to possibly "warning"` but that mean the other pages will have to modified to be consistent, right? 
Also, what do you mean by `Combined the two in a fashion`?

2022-12-19 13:49 UTC, Valastiri commented
> I like the `Change the admonition type for the incorrect label to possibly "warning"` but that mean the other pages will have to modified to be consistent, right? Also, what do you mean by `Combined the two in a fashion`?

oh like put the text into one admonition instead of having too. And I didn't think of the other pages being modified that's a lot of extra work for one tiny thing.

2022-12-19 14:32 UTC, alepouna commented
I have no problem doing that, just confirming its something you'd like to go through (converting to warnings), if thats okay with you I can mark this as draft, do this later today and @ you when its ready :)

2022-12-19 17:54 UTC, Valastiri requested changes
Sorry another change here to make the text more clear. Read it again and I feel like it makes more sense this way.

If you agree just commit as necessary.

2022-12-19 17:54 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs.md
> +    Please note, the ADIR 1, 2 and 3 labels are incorrect. They should state ADIR 1, 2 and 3.
```suggestion
!!! info "Incorrect Label"

    Please note: Currently the ADIRS are labeled ADIR 1, 3 and 2 which is incorrect. They should be labeled ADIR 1, 2 and 3.
```

2022-12-19 19:10 UTC, Valastiri commented
> I have no problem doing that, just confirming its something you'd like to go through (converting to warnings), if thats okay with you I can mark this as draft, do this later today and @ you when its ready :)

I think it's fine as is -- really just a minor concept in the overall grand scheme of things :P

2023-02-04 08:23 UTC, Valastiri commented
If it's alright with you can I take this over?

2023-02-06 10:04 UTC, Valastiri commented
I have this made to merge this PR in. I also have the local branch rebased as well. 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1619968/216943097-cd46cfb4-6136-4aa8-b8fc-f279e7c48908.png">

Let me know if I can push changes into this PR and get it merged. There's #731 that needs to go in as well since I discovered all that due to this PR.

2023-02-06 10:31 UTC, auroraisluna commented
absolutely feel free, I kinda forgot about it this PR not gonna lie

2023-02-06 12:00 UTC, Valastiri approved these changes

2023-02-07 12:00 UTC, merged