docs(efb): GSX Integration
flybywiresim/docs pull request #714
Opened 2023-01-18 17:59 UTC by Lucky38i

## Summary

- Added required content to pages
- Need to add pictures
### Location

fbw-a32nx/feature-guides/flypados3/settings/
fbw-a32nx/feature-guides/flypados3/ground/

Discord username (if different from GitHub): Lucky38i

2023-01-20 19:19 UTC, Valastiri requested changes
Minor comments.

Thanks for adding /venv/ into the gitignore. I thought I had but realized I named my venv's differently heh. I am under the assumption everything is already tested with GSX?

2023-01-20 19:19 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/ground.md
> +- You won't witness passengers boarding the aircraft until, physical passengers from GSX enter the aircraft. You'll notice this when you request boarding through the GSX menu but nothing appears to h
```suggestion
- You won't witness passengers boarding the aircraft until physical passengers from GSX enter the aircraft. You'll notice this when you request boarding through the GSX menu but nothing appears to happen in the EFB just yet.
```

2023-01-20 19:19 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +// TODO Add an image here
```suggestion
```

2023-01-20 19:19 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +</div>
I guess you wouldn't need this considering how far down the page it. Can also leave it no harm.

2023-01-20 22:24 UTC, Lucky38i commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +</div>
I just did it cause all the other entries did

2023-01-21 22:37 UTC, Valastiri approved these changes

2023-01-22 14:08 UTC, frankkopp requested changes
The image is missing the window frame - check out the other images for comparison.
You need to also exchange the main image of the settings page

2023-01-22 14:57 UTC, frankkopp approved these changes

2023-01-22 16:06 UTC, merged