docs(beginner): include basic instructions entering DCT to waypoint
flybywiresim/docs pull request #721
Opened 2023-01-25 22:07 UTC by Valastiri

## Summary
As discussed in FBW support ops include interim and basic instructions on how to enter a waypoint into the f-pln page when no airway is applicable.

This PR includes basic "example" of how to indentify DCT and use the lat rev page to enter the following waypoint.

### Location
- docs/pilots-corner/beginner-guide/preparing-mcdu.md

Discord username (if different from GitHub): Valastiri#8902

2023-01-25 22:15 UTC, Eearslya reviewed
Minor grammar nits

2023-01-25 22:15 UTC, Eearslya commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    There will be cases where your flight plan have waypoints and no airways or a mix of both. When you go direct from one airway to another it will usually look like the following: `WAYPOINT DCT
```suggestion
    There will be cases where your flight plan has waypoints and no airways or a mix of both. When you go direct from one airway to another it will usually look like the following: `WAYPOINT DCT 
```

2023-01-25 22:15 UTC, Eearslya commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    Below is the currently flight plan we are utilizing:
```suggestion
    Below is the current flight plan we are utilizing:
```

2023-01-25 22:15 UTC, Eearslya commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +        The airway `N864` was replaced with `DCT` indicating from waypoint `BCN` proceed direct to `OKTEM`.
```suggestion
        The airway `N864` was replaced with `DCT` indicating from waypoint `BCN` proceeds direct to `OKTEM`.
```

2023-01-26 04:22 UTC, doosedev requested changes
clarification on an alternate presentation of direct legs in flight plan routings, and a few wording/grammar bits n bobs

2023-01-26 04:22 UTC, doosedev commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    WAYPOINT`.
```suggestion
    WAYPOINT`. You might also see directs represented as two waypoints without a separator, which looks like `WAYPOINT WAYPOINT`.
```

2023-01-26 04:22 UTC, doosedev commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    There will be cases where your flight plan has waypoints and no airways or a mix of both. When you go direct from one airway to another it will usually look like the following: `WAYPOINT DCT
```suggestion
    There will be cases where your flight plan has waypoints and no airways or a mix of both. When you go direct from one waypoint to another it will usually look like the following: `WAYPOINT DCT 
```

2023-01-26 04:22 UTC, doosedev commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +        The airway `N864` was replaced with `DCT` indicating from waypoint `BCN` proceeds direct to `OKTEM`.
```suggestion
        The airway `N864` was replaced with `DCT` indicating from waypoint `BCN`, proceed direct to `OKTEM`.
```

2023-01-26 04:22 UTC, doosedev commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    When you encounter this type of routing there are a couple of ways to input this without the use of the airways page on the MCDU.
```suggestion
    When you encounter this type of routing, there are a couple of ways to input the leg without the use of the airways page on the MCDU.
```

2023-01-26 04:22 UTC, doosedev commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    One of the easiest ways is entering the lateral revision page. To do this simply find the starting waypoint which in this case is `BCN`.
```suggestion
    One of the easiest ways is utilizing the lateral revision page. To do this simply find the starting waypoint which in this case is `BCN`.
```

2023-01-26 09:46 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    When you encounter this type of routing there are a couple of ways to input this without the use of the airways page on the MCDU.
going with "this leg" instead of "the leg"

2023-01-26 09:50 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    One of the easiest ways is entering the lateral revision page. To do this simply find the starting waypoint which in this case is `BCN`.
One of the easiest ways is utilizing the lateral revision page. To do this simply find the starting waypoint **on your F-PLN page**, which in this case is `BCN`.

Added the bit in bold just to be even more clear.

2023-01-26 20:38 UTC, merged