feat: GSX Integration re-structure
flybywiresim/docs pull request #736
Opened 2023-02-10 18:13 UTC by Lucky38i

- Dedicated page to GSX Integration so it's better understood.

## Summary

Dedicates a page for GSX Integration so learning how it works is a lot more seamless.

### Location

docs\fbw-a32nx\feature-guides\gsxintegration

Discord username (if different from GitHub):Lucky38i

2023-02-10 18:28 UTC, pdellaert requested changes
Minor changes and consistency in punctuation. Good documentation for a cool feature!

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/payload.md
> +- Once boarding has started you can no longer, edit the fields in the payload screen.
```suggestion
- Once boarding has started you can no longer edit the fields in the payload screen.
```

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/payload.md
> +      - Before proceeding, ensure you've set *everything*  o your preferences, this is a point of NO return.
```suggestion
      - Before proceeding, ensure you've set *everything* to your preferences, this is the point of NO return. 
```

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +You may notice the fuel page is slightly different with the Play button being greyed out. This is because for the sake of GSX flow, you cannot begin fueling until the fuel host is connected.
```suggestion
You may notice the fuel page is slightly different with the Play button being greyed out. This is because for the sake of GSX flow, you cannot begin fueling until the fuel hose is connected.
```

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +      - The "play" button is disabled until the fuel truck has arrived and the hose is connected
```suggestion
      - The "play" button is disabled until the fuel truck has arrived and the hose is connected.
```

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +      - Select `Request Fueling` from the GSX Menu
```suggestion
      - Select `Request Fueling` from the GSX Menu.
```

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +      - You can witness outside as the fuel truck begins to re-fuel your aircraft
```suggestion
      - You can witness outside as the fuel truck begins to re-fuel your aircraft.
```

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +     - Due to limitations with GSX, this is not supported, disable [Fuel Sync](../flypados3/settings.md#3rd-party-options) temporarily, to defuel.
```suggestion
     - Due to limitations with GSX, this is not supported. To defuel, disable [Fuel Sync](../flypados3/settings.md#3rd-party-options) temporarily.
```
Slightly better wording

2023-02-10 18:28 UTC, pdellaert commented on docs/fbw-a32nx/feature-guides/gsxintegration/payload.md
> +- The aircraft's own boarding sounds are disabled as GSX has it's own sound profile for boarding/deboarding. This excludes passenger ambience sounds
```suggestion
- The aircraft's own boarding sounds are disabled as GSX has it's own sound profile for boarding/deboarding. This excludes passenger ambience sounds.
```

2023-02-10 18:33 UTC, pdellaert approved these changes

2023-02-10 19:22 UTC, Valastiri requested changes
Please double check all images are optimized.

Currently gsx-fuel-start.png needs to be much smaller than 1.86MB.

2023-02-10 19:22 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    This feature is only availble in the [Development Version](../../fbw-versions.md#development-version-recommended) and [Experimental Version](../../fbw-versions.md#experimental-version)
```suggestion
    This feature is only available in the [Development Version](../../fbw-versions.md#development-version-recommended) and [Experimental Version](../../fbw-versions.md#experimental-version)
```

2023-02-10 19:22 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/gsxintegration/index.md
> +    One of the most popular add-on is back with a brand new version, optimized for MSFS 2020.
```suggestion
    One of the most popular add-ons is back with a brand new version, optimized for MSFS 2020. 
```

2023-02-10 19:22 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/gsxintegration/profile.md
> +The follow doors were disabled as they cannot be opened on the current A32NX Model. When we release our custom model this will of course be reflected in the developer profile
```suggestion
The following doors were disabled as they cannot be opened on the current A32NX Model. When we release our custom model this will of course be reflected in the developer profile.
```

2023-02-11 09:53 UTC, Valastiri approved these changes

2023-02-11 09:53 UTC, Valastiri commented
check build

2023-02-11 09:54 UTC, merged