fix: ADIR page warning change
flybywiresim/docs pull request #762
Opened 2023-03-17 13:13 UTC by Oyu-De

## Summary
Statement " ADIR 1, 3 and 2 which is incorrect" is incorrect, 1 - 3 - 2 layout is correct, however, it should asy ADR instead of ADIR, changed the warning message to "It should say "ADR" rather than "ADIR". This will be fixed in a future update."

Source: 
Asked tolip for confirmation of 1-3-2 layout

multiple devs notified me that it should say ADR rather than ADIR (https://discord.com/channels/738864299392630914/791494566058000434/1086268828322898021)
(https://discord.com/channels/738864299392630914/887806920252076053/1086272032481751160)

### Location
/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs/#description

Discord username (if different from GitHub):

2023-03-17 13:21 UTC, Sleinmaster approved these changes

2023-03-17 14:13 UTC, Valastiri requested changes

2023-03-17 14:13 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs.md
> +    Please note: It should say "ADR" rather than "ADIR". This will be fixed in a future update.
```suggestion
    Please note: Currently the ADIRS are labeled ADIR 1, 3 and 2 which is incorrect. The labels should say "ADR" rather than "ADIR". This will be fixed in a future update.
```

Can't start an admonition note with "It" -- subject should be defined or the admonition labeled. Suggestion for defining the subject above.

2023-03-17 14:23 UTC, Sleinmaster commented on docs/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs.md
> +    Please note: It should say "ADR" rather than "ADIR". This will be fixed in a future update.
```suggestion
    Please note: Currently, the ADIRS are labeled ADIR 1, 3 and 2, which is incorrect. The labels should say "ADR" rather than "ADIR". This will be fixed in a future update.
```
Punctuation correction to vals proposal.

2023-03-17 16:50 UTC, Oyu-De commented on docs/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs.md
> +    Please note: It should say "ADR" rather than "ADIR". This will be fixed in a future update.
The 1-3-2 are correct. "Currently, the ADIRS are labeled ADIR 1, 3 and 2, which is incorrect." this should be removed, 1-3-2 IS CORRECT.

2023-03-17 20:16 UTC, Sleinmaster commented on docs/pilots-corner/a32nx-briefing/flight-deck/ovhd/adirs.md
> +    Please note: The labels should say "ADR" rather than "ADIR". This will be fixed in a future update.
```suggestion
    Please note: The labels under the rotary switches should say "ADR" rather than "ADIR". This will be fixed in a future update.
```
Would also be a possibility.

2023-03-18 06:39 UTC, Sleinmaster approved these changes

2023-03-19 13:59 UTC, Valastiri commented
check build

2023-03-19 14:21 UTC, Valastiri commented
oops sorry forgot what branch I was on -- was testing a commit. Pls ignore.

2023-03-19 14:42 UTC, Valastiri approved these changes

2023-03-23 08:26 UTC, merged