fix: first corrections in pilot-corner
flybywiresim/docs pull request #771
Opened 2023-03-23 19:47 UTC by Sleinmaster

## Summary

lingual correction in the pilot corner
### Location

https://docs.flybywiresim.com/pilots-corner/

Discord username (if different from GitHub): Slein#8982

2023-03-23 19:52 UTC, Sleinmaster commented on docs/pilots-corner/abbreviations.md
I am not sure how to handle the capitalization. Sometimes every word is capitalized, sometimes the letters that are used in the abbreviation, and sometimes it's capitalized like a normal sentence.

I think the best way would be to capitalize all and only the letters used in the abbreviation where applicable, and otherwise (mainly where a full sentence is needed) use normal sentence capitalization.

2023-03-24 10:15 UTC, Valastiri commented on docs/pilots-corner/abbreviations.md
I believe your suggestion is good. So essentially:

| *Correct abbreviation here i.e. APU | *Only abbreviation with initial letters capitalized* (Auxiliary Power Unit) then the rest of the sentence if required in lowercase |

2023-03-24 10:44 UTC, Sleinmaster commented on docs/pilots-corner/abbreviations.md
@Valastiri 
Here some expamples:

If the Abreviation contains the first letter of the words, I think it's relatively clear how to handle it:
| ADG            | Air-Driven Generator                                   |

If the Abreviation contains the first several letters of a single word, I would suggest:
| ADD            | ADDition, ADDitional                                   |
To capitalize, the first letter would be an option as well, though it doesn't represent the whole abbreviation.

With Letters used in the middle of a word, I think we should capitalize that letter aswell:
| C/L            | CheckList                                              |

If there is a sentence there are two options, either just write like a normal sentence, or still capitalize the letters according to the Abbreviation. In this example, we could also add a "(V)" after "speed":
| V~REF~        | Reference speed for a normal approach at the 50-foot height. |
| V~REF~        | REFerence speed for a normal approach at the 50-foot height. |

In case the abbreviation is not present in the description at all, I guess it should be like a normal sentence:
| V~LO~         | Maximum gear operating speed, which means the max speed for the gear being down.   

The changes according to the style we agree on I would do in a separate pr, since it might trigger some more discussions as just my usual corrections, and it might take more time.

2023-04-09 17:44 UTC, Valastiri requested changes
Some minor changes and questions

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/a32nx-briefing/ecam/sd/cruise.md
> +| 1      | Fuel Used                   | Green           | Fuel used by the engines (multiplies of 10 kg/20lbs).
```suggestion
| 1      | Fuel Used                   | Green           | Fuel used by the engines (multiplies of 10kg/20lbs).                                                                                                          |
```
would it be the above suggestion or 10 kg/20 lbs

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/overview.md
>  like this:
```suggestion
Using the legacy [Cockpit Interaction System](../../../fbw-a32nx/settings.md#legacy-cockpit-interaction-system), you can push and pull knobs on the FCU like this:
```

haven't looked at this visually but figure it might be good idea to fix the lines

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +TCAS will notify the flight crew via the aural warning "Clear of Conflict" when separation and range from a threat is adequate. At this tim,e the flight crew should perform the following actions:
```suggestion
TCAS will notify the flight crew via the aural warning "Clear of Conflict" when separation and range from a threat is adequate. At this time, the flight crew should perform the following actions:
```

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-guidance/tcas.md
> +| ![tcas other traffic](../../assets/advanced-guides/flight/tcas-arrow-down.png){width=75%} | This arrow represents descending traffic.
Ask me on Discord about this

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/holds.md
> +Now that you know where to hold, you should learn how to program the hold. Next, you will need to find information on the chart to enter into the FMS. The primary informations you need to have is:
```suggestion
Now that you know where to hold, you should learn how to program the hold. Next, you will need to find information on the chart to enter into the FMS. The primary information you need to have is:
```

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/overview.md
> +- Above 2.000ft RA, or
Didn't we use `2,000 ft` elsewhere? or `2,000ft` utilizing a comma? 

This is more of a sanity check question.

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/airliner-flying-guide/approaches.md
> +    **DA** - regarding in the precision approach at which a missed approach must be initiated if the required visual reference to continue the approach has not been established.
```suggestion
    **DA** - regarding in the precision approach at which a missed approach must be initiated if the required visual reference to continue the approach has not been established.
```

the "regarding" here seems out of place but I don't have any concrete suggestions at the moment.

2023-04-09 17:44 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/powering-down.md
> +- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This, of course, is only done if enough lighting is available to sa
```suggestion
- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This, of course, is only done if enough lighting is available to safely park into the gate. Turn them off if they are not going to be used to assist in parking.
```

2023-04-09 20:06 UTC, Sleinmaster commented on docs/pilots-corner/a32nx-briefing/ecam/sd/cruise.md
> +| 1      | Fuel Used                   | Green           | Fuel used by the engines (multiplies of 10 kg/20lbs).
```suggestion
| 1      | Fuel Used                   | Green           | Fuel used by the engines (multiplies of 10 kg/20 lbs).                                                                                                          |
```

2023-04-09 20:06 UTC, Sleinmaster commented on docs/pilots-corner/a32nx-briefing/limitations.md
> +| Maximum taxi speed | When takeoff weight >76 000 kg / 167 550 lb | 20 kt during a turn |
```suggestion
| Maximum taxi speed | When takeoff weight >76,000 kg / 167,550 lb | 20 kt during a turn |
```

2023-04-09 20:10 UTC, Sleinmaster commented on docs/pilots-corner/a32nx-briefing/limitations.md
>  |           | Minimum Weight           | 40 600 kg / 89 508l lb |
```suggestion
|           | Minimum Weight           | 40,600 kg / 89,508 lb  |
```

2023-04-09 20:12 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-guidance/overview.md
>  like this:
Visually it doesn't make a difference, but yes, corrected it in some places already.

2023-04-09 20:14 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/overview.md
> +- Above 2.000ft RA, or
```suggestion
- Above 2,000ft RA, or
```

2023-04-09 20:19 UTC, Sleinmaster commented on docs/pilots-corner/airliner-flying-guide/approaches.md
> +    **DA** - regarding in the precision approach at which a missed approach must be initiated if the required visual reference to continue the approach has not been established.
```suggestion
    **DA** - the altitude in a precision approach at which a missed approach must be initiated if the required visual reference to continue the approach has not been established.
```

2023-04-09 20:22 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/powering-down.md
> +- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This, of course, is only done if enough lighting is available to sa
```suggestion
- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This, of course, is only done if enough lighting is available to safely park into the gate. Turn them off if they were used to while parking.
```

Considering the page this is probably a better version since the plane will already at the gate or parking stand.

2023-04-09 20:47 UTC, Valastiri approved these changes

2023-04-09 20:47 UTC, Valastiri commented
tysm for the great work Slein! It's really appreciated.

2023-04-09 20:49 UTC, merged