docs: New Screenshots for Flypad Boarding Page
flybywiresim/docs pull request #778
Opened 2023-03-31 15:36 UTC by Luz5020

Fixes #755
## Summary

Retook all Screenshots where the old Boarding Page was shown, changed Docs slightly wherever it was necessary
Removed some Legacy screenshots that where living in production unused
### Location

https://docs.flybywiresim.com/fbw-a32nx/feature-guides/flypados3/ground/
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/loading-fuel-weight/

Discord username (if different from GitHub):

2023-03-31 23:40 UTC, frankkopp requested changes
Two comments on the flyPad Ground page images.
All images, esp. on the loading-fuel-weight.md page could be a bit smaller - the previous ones where larger but smaller - did you use the tool I recommended on High compression setting?
Otherwise dimensions and images on that page look ok.

2023-03-31 23:40 UTC, frankkopp commented on docs/fbw-a32nx/assets/flypados3/flypad-ground-payload.png
Please redo this one - exactly as the others on the same page. Try to also have the same window frame (blue) - esp. the title bar needs to be smaller - this is why the click map does not match. 
As this is standard Win11 you should be able to reproduce this. Otherwise pls ping me.

2023-03-31 23:40 UTC, frankkopp commented on docs/fbw-a32nx/assets/flypados3/flypad-ground-payload-values.png
This is too large - this should be 50% or 413px - get blurry if you stretch it other the whole width.

2023-04-01 09:26 UTC, Luz5020 commented on docs/fbw-a32nx/assets/flypados3/flypad-ground-payload-values.png
Resized to 413px, should work now

2023-04-01 09:28 UTC, Luz5020 commented
> Two comments on the flyPad Ground page images. All images, esp. on the loading-fuel-weight.md page could be a bit smaller - the previous ones where larger but smaller - did you use the tool I recommended on High compression setting? Otherwise dimensions and images on that page look ok.

I did use the tool, I have no idea why the file size went up tbf

2023-04-02 15:46 UTC, frankkopp approved these changes

2023-04-02 15:55 UTC, Valastiri commented
check build

2023-04-02 19:34 UTC, Luz5020 commented
You can go ahead and Merge it

2023-04-03 10:02 UTC, merged