feat: Documentation for Alternate Law
flybywiresim/docs pull request #782
Opened 2023-04-03 18:30 UTC by Luz5020

fixes #640 
## Summary

Provides Documentation for the Airbus Alternate Law Flight condition
### Location

https://docs.flybywiresim.com/pilots-corner/advanced-guides/protections/overview/

Discord username (if different from GitHub):

2023-04-03 18:30 UTC, Luz5020 commented
This is a very rough draft, currently thinking about what more to add. Feedback appreciated

2023-04-04 16:01 UTC, Valastiri commented
check build

2023-04-04 17:56 UTC, Valastiri requested changes
Preliminary review and suggestions as well. 

There are some things that need to be checked that personally, I'm not aware of such as if it's `ECAM Warning` or `ECAM warning` for example.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Alternate Law is activated when the plane looses certain computers, avionics or sensors, you can tell Alternate Law is in effect by the ECAM Message: "ALTN LAW" and associated Messages detailing the
```suggestion
Alternate Law is activated when the plane loses certain computers, avionics or sensors. You can tell Alternate Law is in effect by the ECAM Message: "ALTN LAW" and associated Messages detailing the failure that led to Alternate Law becoming active.
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Following failures will lead to the activation of [Alternate Law with reduced protection](#Alternate-Law-with-Reduced-Protection)
```suggestion
Following failures will lead to the activation of [Alternate Law with reduced protection](#alternate-law-with-reduced-protection):
```
Please check that the internal anchor links are correct.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Following failures will lead to the activation of [Alternate Law with reduced protection and mechanical yaw control](#Alternate-Law-with-Reduced-Protection)
```suggestion
Following failures will lead to the activation of [Alternate Law with reduced protection and mechanical yaw control](#alternate-law-with-reduced-protection):
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Failure of 2 ADRs (Failure of second ADR not self detected **and** Disagreement related to calculated airspeed (CAS) or Mach speed)
```suggestion
- Failure of 2 ADRs (Failure of second ADR not self-detected **and** disagreement related to calculated airspeed (CAS) or Mach speed)
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Failure of 2 ADRs (self detected)
```suggestion
- Failure of 2 ADRs (self-detected)
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +??? info "Self Detection"
```suggestion
!!! info "Self Detection"
```
Optional -- i don't think this needs to be collapsed -- pretty neat information.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    The flight computer can compare the data across systems, when detecting an abnormality it ignores the corresponding system. This is known as a "non-self-detected failure".
```suggestion
    All flight systems are continuously monitored by the flight computers, when a peripheral system detects a fault it will inform the flight computers or shut down (self detected failure). 
    Some faults can not be detected by the peripheral system itself because it can only see its own data. 
    The flight computer can compare the data across systems, when detecting an abnormality it ignores the corresponding system. 
    
    This is known as a "non-self-detected failure".     
```
**Suggestion**
Adding a break would render the line separately might look nicer than a wall of text (although small wall of text.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    Loss of all protections on final approach should be anticipated, and the flight crew should prepare to take over pitch trimming for landing.
```suggestion
!!! warning "Approach and Landing with Alternate Law"
    When deploying the Landing Gear under Alternate Law **and** the Autopilot is disconnected
    the controls switch directly to [Direct Law](#Direct-Law), this is done to provide necessary force feedback to the pilot as the "FLARE" Mode that usually provides feedback to the sidestick is inoperable in alternate law.
    
    Loss of all protections on final approach should be anticipated, and the flight crew should prepare to take over pitch trimming for landing.  
```
Same as the suggestion above.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Following failures will lead to the activation of [Direct Law](#Direct-Law)
internal link check

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Following failures will lead to the activation of [Alternate Law without Protection](#Alternate-Law-without-Protection)
link check

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Some failure conditions are caused by a combination or factors and can cause abnormal failure modes, some may allow recovery to a more stable state
```suggestion
Some failure conditions are caused by a combination or factors and can cause abnormal failure modes, some may allow recovery to a more stable state:
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +This is the standard fallback mode.
```suggestion
- When the Radio Altimeters fail with Gear down **or** the plane is in CONF 2 and the LGCIUs have a data disagreement, Direct Law will be used. Abnormal from Direct Law Yaw Control will be kept in alternate.

## Alternate Law with Reduced Protection
This is the standard fallback mode.
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Load Factor Protection is available, over stressing the airframe should not be possible
```suggestion
- Load Factor Protection is available, over stressing the airframe should not be possible.
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +This fallback mode is triggered when multiple flight critical redundant systems have failed
```suggestion
This fallback mode is triggered when multiple flight-critical redundant systems have failed:
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Autotrim and Speed Stability are lost.
I'm unsure of the capitalization speed stability here -- just making a note.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
Another note -- do the laws need to be capitalized here.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +likely disconnected.
```suggestion
to subsidize all the systems that are suddenly unavailable. The highest priority should be taking control of the airplane since the AP is likely disconnected.
```

unsure if it's worth writing out autopilot here

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    ![img.png](../../assets/advanced-guides/vnav/goldenrules.png)
```suggestion
    ![golden rules image](../../assets/advanced-guides/vnav/goldenrules.png)
```

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    It is the sole responsibility of the pilot to conduct proper flight planning and execution. It is not sufficient
Please remove the `<p/>` html.

If you require line breaks just leave an empty line between the text you want to break.

2023-04-04 17:56 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +To rectify issues with the plane, work through the ECAM Actions and refer to the "STS" ECAM Page.
```suggestion
Recovering to Normal Law is not guaranteed and may not be possible depending on the type of failure.
In general, when the failure that caused Alternate Law is fixed, normal law should be operational again. 
To rectify issues with the plane, work through the ECAM Actions and refer to the "STS" ECAM Page. 
```

2023-04-04 18:21 UTC, Luz5020 commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Following failures will lead to the activation of [Alternate Law with reduced protection](#Alternate-Law-with-Reduced-Protection)
is it always not capitalized? I thought it was the same spelling as the title that is referenced

2023-04-04 18:37 UTC, Luz5020 commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
No Idea, if it's a proper name maybe? But in that case what is capitalized? The Word before and Law? Just one of them? Idk

2023-04-04 18:38 UTC, Luz5020 commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +likely disconnected.
Can't really think what would work better, assuming people in advanced guides know what an AP is

2023-04-04 18:45 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
Will get more eyes on this no worries. Same with the other comment.

2023-04-04 19:32 UTC, Luz5020 commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
Links were fixed, it's bascially just this and then verifying the docs are actually what is needed

2023-04-04 20:29 UTC, Sleinmaster requested changes

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Alternate Law is activated when the plane loses certain computers, avionics or sensors. You can tell Alternate Law is in effect by the ECAM Message: "ALTN LAW" and associated Messages detailing the f
```suggestion
Alternate Law is activated when the plane loses certain computers, avionics, or sensors. You can tell Alternate Law is in effect by the ECAM Message: "ALTN LAW" and associated Messages detailing the failure that led to Alternate Law becoming active.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +On the PFD, indications for protective limits are replaced by amber "x" indication when the associated system is unavailable.
```suggestion
On the PFD, indications for protective limits are replaced by an amber "x" indication when the associated system is unavailable.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Some failure conditions are caused by a combination or factors and can cause abnormal failure modes, some may allow recovery to a more stable state:
```suggestion
Some failure conditions are caused by a combination of factors and can cause abnormal failure modes, some may allow recovery to a more stable state:
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- When the plane is in "Emergency Electrical Configuration (On Batteries)" Alternate Law with reduced protections is active, although yaw control is switched to the mechanical backup, after emergency
```suggestion
- When the plane is in "Emergency Electrical Configuration (On Batteries)" Alternate Law with reduced protections is active, although yaw control is switched to the mechanical backup, after emergency power becomes available, resetting FAC 1 allows recovery to alternate control over yaw.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- When 2 IRs fail with the second not being self detected the flight crew has to identify and switch off the faulty IR before resetting **both** ELAC 1 and 2, the plane will recover to Alternate Law
```suggestion
- When 2 IRs fail with the second not being self detected, the flight crew has to identify and switch off the faulty IR before resetting **both** ELAC 1 and 2, the plane will recover to Alternate Law with reduced protection.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Stall and over speed **are** possible in Alternate Law, audio warnings should be taken seriously and the plane stabilized immediately.
```suggestion
- Stall and over speed **are** possible in Alternate Law, audio warnings should be taken seriously, and the plane stabilized immediately.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    With fly-by-wire flight controls the sidestick usually doesn't affect the avionics directly, instead being translated into a load demand order that tells the flight computers to change the curren
```suggestion
    With fly-by-wire flight controls, the sidestick usually doesn't affect the avionics directly, instead being translated into a load demand order that tells the flight computers to change the current flight situation, the computers then generate commands for the avionics to achieve the necessary movement introduced.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Unlike normal alternate law, abnormal alternate law(also known as abnormal attitude law) is activated when the plane is far outside the normal flight envelope and reaches abnormal attitudes (even whe
```suggestion
Unlike normal alternate law, abnormal alternate law (also known as abnormal attitude law) is activated when the plane is far outside the normal flight envelope and reaches abnormal attitudes (even when in normal law).
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Autotrim and Speed Stability are lost.
I think it's correct since it's the feature with that name that's lost, not the stability in general.

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
As far as I understand it, Abnormal and Law should both be capitalized, though with the capitalization, I'm not too secure either. And I think it's wrong in many places.
Though I'm just learning about the capitalization myself, maybe a native English-speaking user can check that.

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
```suggestion
Abnormal law is triggered when one of the following conditions is met:
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Speed above 440 kts / MAch above 0.91
```suggestion
- Speed above 440 kt / Mach above 0.91
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Speed below 60-90 kts (exact value dependent on pitch)
```suggestion
- Speed below 60-90 kt (exact value dependent on pitch)
```
The official icao abbreviation doesn't have the s (still wrong in many places in our docs). ISO abbreviation would be kn but in aviation kt is usually used.

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +In Abnormal, autotrim is turned off and roll control is switched to direct law under which 4 spoilers are used for control instead of 2.
```suggestion
In Abnormal, autotrim is turned off and roll control is switched to direct law, under which 4 spoilers are used for control instead of 2.
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Should the "LAND ASAP" ECAM Warning be displayed the plane has to be landed as quickly and safely as possible, otherwise it's your call as the capitan to decide,
```suggestion
Should the "LAND ASAP" ECAM Warning be displayed, the plane has to be landed as quickly and safely as possible; Otherwise it's your call as the captain to decide,
```

2023-04-04 20:29 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +diverting, returning or pressing on, in any case the rest of the flight will take full concentration and a lot of airmanship.
```suggestion
diverting, returning or pressing on, in any case, the rest of the flight will take full concentration and a lot of airmanship.
```

2023-04-04 20:39 UTC, Sleinmaster commented
> Preliminary review and suggestions as well.
> 
> There are some things that need to be checked that personally, I'm not aware of such as if it's `ECAM Warning` or `ECAM warning` for example.

In their Safetyfirst documents, Airbus writes ECAM **w**arning. Features line Autoland, they write with capital letters. 

But in general, they are not consistent with it at all. In one magazine they wrote once "Alternate law" and otherwise "alternate law", in another one they consistently wrote "Direct Law" with both first letters capitalized, which, I think, is the correct version.

2023-04-04 22:49 UTC, Valastiri commented
> > Preliminary review and suggestions as well.
> > There are some things that need to be checked that personally, I'm not aware of such as if it's `ECAM Warning` or `ECAM warning` for example.
> 
> In their Safetyfirst documents, Airbus writes ECAM **w**arning. Features line Autoland, they write with capital letters.
> 
> But in general, they are not consistent with it at all. In one magazine they wrote once "Alternate law" and otherwise "alternate law", in another one they consistently wrote "Direct Law" with both first letters capitalized, which, I think, is the correct version.

thanks for the research that's indeed frustrating -- will ask some of our team as well for insight probably.

2023-04-05 08:08 UTC, Luz5020 commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Abnormal law is triggered when one of the following conditions are met:
Capitalizing both Abormal/Normal and Direct as well as Law is porbably right, it's a name Airbus gave those flight conditions, should be consistent now

2023-04-05 08:21 UTC, Sleinmaster reviewed
Some more capitalization changes as far as I understand it should be.

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Alternate Law is activated when the plane loses certain computers, avionics, or sensors. You can tell Alternate Law is in effect by the ECAM Message: "ALTN LAW" and associated Messages detailing the
```suggestion
Alternate Law is activated when the plane loses certain computers, avionics, or sensors. You can tell Alternate Law is in effect by the ECAM message: "ALTN LAW" and associated messages detailing the failure that led to Alternate Law becoming active.
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Loss of all Spoilers
```suggestion
- Loss of all spoilers
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +Following failures will lead to the activation of [Alternate Law without Protection](#alternate-law-without-protection)
```suggestion
Following failures will lead to the activation of [Alternate Law without protection](#alternate-law-without-protection)
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    the controls switch directly to [Direct Law](#direct-law), this is done to provide necessary force feedback to the pilot as the "FLARE" Mode that usually provides feedback to the sidestick is ino
```suggestion
    the controls switch directly to [Direct Law](#direct-law), this is done to provide necessary force feedback to the pilot as the "FLARE" mode that usually provides feedback to the sidestick is inoperable in Alternate Law.
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    the controls switch directly to [Direct Law](#direct-law), this is done to provide necessary force feedback to the pilot as the "FLARE" Mode that usually provides feedback to the sidestick is ino
```suggestion
    the controls switch directly to [Direct Law](#direct-law), this is done to provide necessary force feedback to the pilot as the "FLARE" mode that usually provides feedback to the sidestick is inoperable in Alternate Law.
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Stall/&alpha;~floor~ and Over speed/V~MO~ Protections are unavailable.
```suggestion
- Stall/&alpha;~floor~ and Overspeed/V~MO~ Protections are unavailable.
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Speed stability is enabled, this function pushes the nose down when the airspeed gets too low (about 5kts before reaching V~SW~) and pulls the nose up when speed is getting too high.
```suggestion
- Speed Stability is enabled, this function pushes the nose down when the airspeed gets too low (about 5kts before reaching V~SW~) and pulls the nose up when speed is getting too high.
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +- Speed stability is **no** protection, its commands are overruled by the sidestick, it's only used to maintain a safe speed when the pilot is not actively monitoring the speed.
```suggestion
- Speed Stability is **no** protection, its commands are overruled by the sidestick, it's only used to maintain a safe speed when the pilot is not actively monitoring the speed.
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +    This also inhibits unsafe flight conditions like stalls, inverted flight or exceeding of the load limit (G Limit), provided the Aircraft is in [Normal Law](overview.md).
```suggestion
    This also inhibits unsafe flight conditions like stalls, inverted flight or exceeding of the load limit (G Limit), provided the aircraft is in [Normal Law](overview.md).
```

2023-04-05 08:21 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +In Abnormal, autotrim is turned off and roll control is switched to Direct Law, under which 4 spoilers are used for control instead of 2.
```suggestion
In Abnormal, Autotrim is turned off and roll control is switched to Direct Law, under which 4 spoilers are used for control instead of 2.
```

2023-04-07 09:46 UTC, Luz5020 commented
LMK if it's good now, maybe double check with reviewers, but I'm positive I got all the changes.
Also this isn't strict build safe because of an Issue detailed in the Discord, awaiting a reply there.

2023-04-08 12:18 UTC, Valastiri requested changes

2023-04-08 12:18 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/protections/altnlaw.md
> +diagnosed by finding the related system. If displayed work the ECAM Actions, if successful you may [recover to Normal Law](recovering-to-normal-law).
```suggestion
diagnosed by finding the related system. If displayed work the ECAM Actions, if successful you may [recover to Normal Law](#recovering-to-normal-law).
```

2023-04-08 12:58 UTC, Valastiri approved these changes

2023-04-08 13:34 UTC, merged