refactor-rmv-exp
flybywiresim/docs pull request #850
Opened 2023-06-27 04:10 UTC by Valastiri

## Summary
Supports the discontinuation of the Experimental Version

### Location
- Multiple Locations based on references

### TODO

Working top level directories to tackle:

- [ ] fbw-a32nx
- [ ] dev-corner
- [ ] pilots-corner
- [ ] release-notes
- [ ] simbridge

Check when complete.

Discord username (if different from GitHub): valastiri

2023-06-27 17:29 UTC, Valastiri commented
Updated the config to kill the redirects

2023-06-27 18:26 UTC, Lauvaan requested changes
Some minor things. Not 100% sure about the capital "V"'s, as in those instances, that were changed they were not capital previously, but in some other places they were.

2023-06-27 18:26 UTC, Lauvaan commented on docs/fbw-a32nx/faq.md
> +    We have two versions: Stable and Development
Missing dot(not actually sure if it needs one, but the previous text had one)

2023-06-27 18:26 UTC, Lauvaan commented on docs/pilots-corner/advanced-guides/flight-guidance/vertical-guidance/managed-modes.md
> +!!! warning "Managed CLB or DES (VNAV) is currently only available in the Development version."
"version" should have a capital "V", to be in line with other instances in the docs

2023-06-27 18:26 UTC, Lauvaan commented on docs/pilots-corner/advanced-guides/flight-guidance/vertical-guidance/managed-modes.md
> +!!! warning "Managed CLB or DES (VNAV) is currently only available in the Development version."
"version" should have a capital "V", to be in line with other instances in the docs

2023-06-27 18:26 UTC, Lauvaan commented on docs/pilots-corner/beginner-guide/descent.md
> +    The TOD (top of descent) marker on the `ND` is available in the Development version.
"version" should have a capital "V", to be in line with other instances in the docs

2023-06-27 18:26 UTC, Lauvaan commented on docs/pilots-corner/beginner-guide/descent.md
> +        VNAV is currently only supported in our Development version of the A32NX.
"version" should have a capital "V", to be in line with other instances in the docs

2023-06-27 19:05 UTC, Sleinmaster commented
> Some minor things. Not 100% sure about the capital "V"'s, as in those instances, that were changed they were not capital previously, but in some other places they were.

Actually, the first letter of development and stable should be lowercase.

2023-06-27 19:16 UTC, Lauvaan commented
> Actually, the first letter of development and stable should be lowercase.

So the word "development" should be lowercase? Or the "version" should be lowercase?

2023-06-27 19:36 UTC, frankkopp commented
> > Some minor things. Not 100% sure about the capital "V"'s, as in those instances, that were changed they were not capital previously, but in some other places they were.
> 
> 
> 
> Actually, the first letter of development and stable should be lowercase.

Stable, Development and Experimental are edition names, and therefore capitalized.

2023-06-27 19:40 UTC, Lauvaan commented
Well, no need to worry about the capitalization in this pr imo. Looking a bit more carefully through the docs, it seems that there are many places where neither the edition name nor "version(s)" have been capitalized, and then many occasions where both of them or only on of them is capitalized. This could be a thing for another pr sometime somewhen.

2023-06-27 19:53 UTC, frankkopp commented
> Well, no need to worry about the capitalization in this pr imo. Looking a bit more carefully through the docs, it seems that there are many places where neither the edition name nor "version(s)" have been capitalized, and then many occasions where both of them or only on of them is capitalized. This could be a thing for another pr sometime somewhen.

That's fine. But they should be capitalized. If not it is an error. I always tried to make sure to be consistent with it.

2023-06-27 20:30 UTC, Sleinmaster commented
> > > Some minor things. Not 100% sure about the capital "V"'s, as in those instances, that were changed they were not capital previously, but in some other places they were.
> > 
> > 
> > Actually, the first letter of development and stable should be lowercase.
> 
> Stable, Development and Experimental are edition names, and therefore capitalized.

Yeah, looking at it this way that's probably right, although I didn't really find any rules about it. 
Versions with the s at the end should definitely be lowercase, probably without the s as well.

So I would say the ones commented on by lauvaan are correct, if there are other capitalizations somewhere they should at some point be corrected.

2023-06-28 03:50 UTC, Valastiri commented
Ah yea sorry was super rushed -- as Mav said as a team we decided edition names are captilalized but in terms of the word version I think I'll take lauvan's recommendation for now and we can look at it in another PR

2023-06-28 04:48 UTC, Valastiri commented
returned exp.md with a simple statement to support the marketing website's "expOnHold" copy that links back to our documentation.

2023-06-28 11:34 UTC, merged