docs: add routes and files
flybywiresim/docs pull request #852
Opened 2023-07-01 15:22 UTC by D0m1nu2

## Summary
Add A380 active routes overview for FBW website. Currently I've only made few of them to see if it's ok like this, once I got confirmation, I will finish the rest of them.
I've used FlightRadar24 for route length and average flight time, then Planespotter for fleet info.

### Location
docs/fbw38nx/xxx

Discord username (if different from GitHub): D0m1nuZ @D0m1nu2

2023-07-02 04:49 UTC, Valastiri requested changes
A few things but to start thanks for continuing work on this.

## Minor Notes
- We have a WIP directory that includes some A380 flight ops information. If you can move the entirety of your PR's contents to that folder and keep your structure for easy moving later that would be great as we aren't ready to publish this info just yet but I would gladly have this on the repo. 
- If you'd like to refactor / update the existing information alongside yours that would be helpful otherwise we can leave that for a later time.

## Critical
- Your images are too large and do not conform to our standards. 
- See [Image Assets Process](https://docs.flybywiresim.com/dev-corner/development-projects/documentation/?h=documentation+project#image-assets-process) on our guide.

2023-07-02 04:56 UTC, Valastiri commented on docs/fbw-a380x/routes/operating/QTR.md
> +| Departure ICAO/IATA | Arrival ICAO/IATA | Flight Number | Lenght | Distance |
```suggestion
| Departure ICAO/IATA | Arrival ICAO/IATA | Flight Number | Length | Distance |

```

2023-07-02 04:56 UTC, Valastiri commented on docs/fbw-a380x/routes/operating/QTR.md
> +| Departure ICAO/IATA | Arrival ICAO/IATA | Flight Number | Lenght | Distance |
Although I would suggest changing "Length" -> "Duration" // as that would make more sense in aviation to me.

Additionally, length is misspelled in each document.

2023-07-02 06:02 UTC, Sleinmaster requested changes
You'll have to correct the units. I can make a review with suggestions in the coming days, but here is essentially what has to be changed.

- Between the numbers and the respective units you should insert a non-breakable space (alt+0160 on windows).
- the unit for nautical miles is upper case, so NM.

2023-07-04 06:13 UTC, Sleinmaster requested changes
This as an example, please change the others accordingly and don't forget to format the tables.

2023-07-04 06:13 UTC, Sleinmaster commented on docs/fbw-a380x/routes/operating/AAR.md
> +Asiana Airways has 6 A380s in it's fleet first delivered in December 2013 and last on August 2016
```suggestion
Asiana Airways has 6 A380 in its fleet first delivered in December 2013 and last on August 2016

```

2023-07-04 06:13 UTC, Sleinmaster commented on docs/fbw-a380x/routes/operating/AAR.md
> +Asiana is currently operating their A380s on 3 routes around the world.
```suggestion
Asiana is currently operating their A380 on 3 routes around the world.

```

2023-07-04 06:13 UTC, Sleinmaster commented on docs/fbw-a380x/routes/operating/AAR.md
> +| KLAX/LAX | RKSI/ICN | OZ201 | 12h55m | 5210nm |
```suggestion
| Departure ICAO/IATA | Arrival ICAO/IATA | Flight Number | Length | Distance |
|:--------|:--------|:------|:------|:-----|
| RKSI/ICN | VTBS/BKK | OZ741 | 5 h 15 m   | 1980 NM |
| VTBS/BKK | RKSI/ICN | OZ742 | 4 h 40 m   | 1980 NM |
| RKSI/ICN | YSSY/SYD | OZ601 | 10 h 00 m | 4550 NM |
| YSSY/SYD | RKSI/ICN | OZ602 | 10 h 10 m | 4550 NM |
| RKSI/ICN | KLAX/LAX | OZ202 | 10 h 10 m | 5210 NM |
| KLAX/LAX | RKSI/ICN | OZ201 | 12 h 55 m | 5210 NM |

```

2023-07-25 19:46 UTC, Valastiri commented
@D0m1nu2 is there any update on this PR?

2023-07-28 17:50 UTC, D0m1nu2 commented
> @D0m1nu2 is there any update on this PR?

I'm sorry for my recent inactivity, I did not have much time to look into this due to big amount of work. I will try to find some more time in the upcoming weeks so I fix and add all the mentioned things.

2023-07-29 01:41 UTC, Valastiri commented
> > @D0m1nu2 is there any update on this PR?
> 
> I'm sorry for my recent inactivity, I did not have much time to look into this due to big amount of work. I will try to find some more time in the upcoming weeks so I fix and add all the mentioned things.

No worries -- just wanted to check in! I have updated my review regarding the WIP directory and whenever you are ready for review I might simply add a few commits to ensure your documentation is appropriately setup if it's out of scope for you.

Either way thanks again for doing this good stuff.

2024-10-08 15:41 UTC, Valastiri commented
Outdated

2024-10-08 15:41 UTC, closed without merging