docs(new page): javascript.md
flybywiresim/docs pull request #88
Opened 2021-06-22 22:32 UTC by Valastiri

Will require some additional information + other concepts to include. 

## Todo
- [ ] Introduction
- [ ] Other relevant information regarding javascript usage in a32nx repo

2021-06-23 07:38 UTC, davidwalschots requested changes

2021-06-23 07:38 UTC, davidwalschots commented on docs/a32nx-dev/javascript.md
> +## Intoduction
```suggestion
## Introduction
```

2021-06-23 07:38 UTC, davidwalschots commented on docs/a32nx-dev/javascript.md
> +[need some text]
Pick between this or the `Introduction` typo fix suggestion 😉.
```suggestion
```

2021-06-23 07:38 UTC, davidwalschots commented on docs/a32nx-dev/javascript.md
> +Don't reassign function parameters
Use `###` header for these texts?

Make sure to consistently end sentences with a `.`, unless they're a header.

2021-06-23 07:38 UTC, davidwalschots commented on docs/a32nx-dev/javascript.md
> +```js linenums="1"
linenums aren't really necessary for short code examples without the text referring to a certain line.

2021-06-23 07:38 UTC, davidwalschots commented on docs/a32nx-dev/javascript.md
> +```
Consider splitting this example up, and adding a regular text, such as "Do not" and "Do".

2021-07-02 13:59 UTC, Valastiri commented on docs/a32nx-dev/javascript.md
> +Don't reassign function parameters
![image](https://user-images.githubusercontent.com/1619968/124285643-af671f80-db80-11eb-966a-8d241a3a7eca.png)

I can keep the info block as seen here. Otherwise, I can just match the format against the rest of the document.

2021-07-20 20:09 UTC, davidwalschots commented on docs/a32nx-dev/javascript.md
> +Don't reassign function parameters
I don't think using an info block makes sense. That way all text on this page that isn't a title will be an info block. I'd expect regular text.

2021-07-21 17:07 UTC, Valastiri commented on docs/a32nx-dev/javascript.md
> +Don't reassign function parameters
Very reasonable! Changed.

2021-07-21 17:14 UTC, davidwalschots approved these changes

2021-08-23 11:39 UTC, merged