docs: add keyboard input documentation for the mcdu remote display in browser mode
flybywiresim/docs pull request #887
Opened 2023-09-08 19:44 UTC by ozgend

## Summary
- add keyboard input documentation for the mcdu remote display in browser mode / ref pr: https://github.com/flybywiresim/simbridge/pull/86

### Location
[simbridge/simbridge-feature-guides/remote-displays/remote-mcdu/](https://docs.flybywiresim.com/simbridge/simbridge-feature-guides/remote-displays/remote-mcdu/)

2023-09-08 19:48 UTC, Sleinmaster commented
Simbridge pr is ready and waiting for this review.

2023-09-08 20:01 UTC, Sleinmaster requested changes

2023-09-08 20:01 UTC, Sleinmaster commented on docs/simbridge/simbridge-feature-guides/remote-displays/remote-mcdu.md
> +The supoorted list of keyboard inputs and shortcuts are available for the MCDU Remote Display in a desktop browser.
```suggestion
The list shows the supported keyboard inputs and shortcuts for the MCDU Remote Display in a desktop browser.
```

2023-09-08 20:01 UTC, Sleinmaster commented on docs/simbridge/simbridge-feature-guides/remote-displays/remote-mcdu.md
> +| `F1`-`F6`            | LSK1-LSK6 |
Use ++ ++ to encase keys, e.g. ++F1++

Check out this documentation for the exact key names: https://facelessuser.github.io/pymdown-extensions/extensions/keys/

2023-09-09 03:31 UTC, Valastiri approved these changes

2023-09-09 06:10 UTC, Sleinmaster approved these changes

2023-10-25 08:18 UTC, Valastiri commented
check build

2023-10-25 08:28 UTC, Valastiri commented
check build

apologies pushed a commit to make sure strict tests pass

2023-10-25 14:35 UTC, merged