feat: crossbleed engine start documentation
flybywiresim/docs pull request #889
Opened 2023-09-11 11:59 UTC by Valastiri

## Summary
This PR provides information on performing the crossbleed engine start procedure.

Creates a new directory in advanced guides titled "Engines". While this PR does not include an index.md, this new director will support other advance topics like single engine taxi out in the future. 

### Location
- docs/pilots-corner/advanced-guides/engines/crossbleed-start.md

Discord username (if different from GitHub):
 valastiri

2023-09-11 12:25 UTC, Valastiri commented
Wait for FBW Marketing b4 merging

2023-09-11 12:32 UTC, Sleinmaster requested changes
The engine page always shows the pressure in PSI AFAIK. In that case, the text is, except for the proposed corrections, good for me. 
If the PSI can be switched to kPa the values should be mentioned in that unit as well.

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +It may be prudent to inform ATC that you will be performing a crossbleed start as the procedures and process may take longer than a normal start and carry certain risks both
```suggestion
It may be prudent to inform ATC that you will be performing a crossbleed start, as the procedures and process may take longer than a normal start and carry certain risks both 
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +To explain this procedure we will assume that `ENG 1` is running and the flight crew will start `ENG 2` using the crossbleed procedure.
```suggestion
To explain this procedure, we will assume that `ENG 1` is running, and the flight crew will start `ENG 2` using the crossbleed procedure.
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +    Currently the A32NX does not have the capability to air start the engines. This procedure is included for completeness and will be updated when the feature is implemented.
```suggestion
    Currently, the A32NX does not have the capability to air start the engines. This procedure is included for completeness and will be updated when the feature is implemented.
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +     - Crucially that the bleeds on both sides are connected via the `X BLEED` valve and that the `ENG 2 BLEED` valve is closed (indicated by the amber line above IP for ENGINE 2).
```suggestion
     - Crucially, that the bleeds on both sides are connected via the `X BLEED` valve and that the `ENG 2 BLEED` valve is closed (indicated by the amber line above IP for ENGINE 2).
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +    If thrust required approachs 40% N1 to maintain at least 25 PSI, ensure the surrounding area continues to be clear of obstructions. If you exceed 40% N1 there maybe issues
```suggestion
    If thrust required approaches 40 % N1 to maintain at least 25 PSI, ensure the surrounding area continues to be clear of obstructions. If you exceed 40 % N1 there maybe issues 
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +Once both engines are started ensure the following in order:
```suggestion
Once both engines are started, ensure the following in order:
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +    It is common to lose pressure during the start sequence. Advance the `THR LEVERS` of the supplying engine (`ENG 1` in this scenario) to maintain at least 25 PSI.
```suggestion
    It is common to lose pressure during the start sequence. Advance the `THR LEVERS` of the supplying engine (`ENG 1` in this scenario) to maintain at least 25 PSI.
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +4. Switch `ENG MASTER 2` to the ON position. **Maintain at least 25 PSI during the entire start procedure**.
```suggestion
4. Switch `ENG MASTER 2` to the ON position. **Maintain at least 25 PSI during the entire start procedure**.
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +     - It is not unusual on the NEO to see the pressure be at or above 30 PSI at IDLE power. If the pressure is below 30 PSI, increase the thrust of the running engine.
```suggestion
3. Ensure that the IGN Bleed PSI for `ENG 2` is at or above 30 PSI before attempting to start the engine. 
     - It is not unusual on the NEO to see the pressure be at or above 30 PSI at IDLE power. If the pressure is below 30 PSI, increase the thrust of the running engine.
```

2023-09-11 12:32 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +    For now you would have to start a single engine normally (`APU ON` and `APU BLEED ON`) before carrying on with a crossbleed start.
```suggestion
    For now, you would have to start a single engine normally (`APU ON` and `APU BLEED ON`) before carrying on with a crossbleed start.
```

2023-09-11 15:55 UTC, Sleinmaster reviewed
One More, otherwise lgtm

2023-09-11 15:55 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +    The following procedure is included for completeness and will be updated when the feature is implemented.
The above Feature?

2023-09-11 18:26 UTC, BlueberryKing reviewed
Reads great! Just a few things that stood out to me

2023-09-11 18:26 UTC, BlueberryKing commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +1. Begin by verifying the bleed page on the upper ECAM display.
```suggestion
1. Begin by verifying the bleed page on the lower ECAM display. 
```

2023-09-11 18:26 UTC, BlueberryKing commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +     - This should display the ENGINE page on the upper ECAM display.
```suggestion
     - This should display the ENGINE page on the lower ECAM display.
```

2023-09-11 18:26 UTC, BlueberryKing commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +2. Deselect the Bleeds page and turn the `ENG MODE` to `IGN/START`.
I'd use "Bleed page" or "BLEED page" 

```suggestion
2. Deselect the Bleeds page and turn the `ENG MODE` to `IGN/START`. 
```

2023-09-12 01:23 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +    The following procedure is included for completeness and will be updated when the feature is implemented.
```suggestion
    The following procedure is included for completeness and will be updated when the above feature is implemented.
```

2023-09-12 01:23 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/engines/crossbleed-start.md
> +2. Deselect the Bleeds page and turn the `ENG MODE` to `IGN/START`.
```suggestion
2. Deselect the BLEED page and turn the `ENG MODE` to `IGN/START`. 
```

2023-09-12 01:29 UTC, Valastiri commented
check build

2023-09-13 12:24 UTC, merged