docs(release): v0.11.0 release notes
flybywiresim/docs pull request #904
Opened 2023-10-24 07:08 UTC by Valastiri

## Summary
WIP

### TODO

- [ ] Remove Stable Versioning Docs
    - Navigraph 

### Location
- /release-notes

Discord username (if different from GitHub):

2023-10-27 12:03 UTC, Valastiri commented
@Sleinmaster a pre-review would be appreciated -- I don't have much more to add in general beyond possible the simbridge stuff (which there might not be enough for it's own section) since this is sorta a tandem release. 

But no worries if you don't have time. Cheers!

2023-10-27 13:06 UTC, Sleinmaster requested changes

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +instruments, bolstered the FMS with comprehensive updates, and introduced new realistic simulations of systems involving cross bleed engine starts and air conditioning.
```suggestion
Immerse yourself with advanced navigational capabilities as we introduce vertical navigation to the Stable Version of the A32NX. We have refined various crucial flight 
instruments, bolstered the FMS with comprehensive updates, and introduced new realistic simulations of systems involving cross bleed engine starts and air conditioning. 
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +    We have streamlined the the authentication process with Navigraph services (SimBrief included). Please note any changes on the following page:
```suggestion
    We have streamlined the authentication process with Navigraph services (SimBrief included). Please note any changes on the following page:
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +    Automatic Call Outs are now selectable in the flyPad. The basic configruation offered by Airbus is set as the default.
```suggestion
    Automatic Call-Outs are now selectable in the flyPad. The basic configuration offered by Airbus is set as the default.
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +    We've added a few notable functional changes such as a "Pause at T/D" function. SimBridge connectivity issues have also been addressed.
```suggestion
    We've added a few notable functional changes, such as a "Pause at T/D" function. SimBridge connectivity issues have also been addressed.
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +    Main dashboard and landing calculator have been refined to use your selected METAR source for a consistent weather information feed.
```suggestion
    The main dashboard and landing calculator have been refined to use your selected METAR source for a consistent weather information feed.
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +    our future aircraft releases maintaining versatility between our products.
```suggestion
    We've rolled out aesthetic updates to the throttle configuration settings, while also expanding support for multiple airframes. This ensures our flyPad is compatible with 
    our future aircraft releases, maintaining versatility between our products.
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +dedicated [Crossbleed Engine Start](#) page.
```suggestion
Pilots are now able to initiate an engine start from crossbleed air. This procedure is normal performed when the APU Bleed start is not possible. For more information, visit our 
dedicated [Crossbleed Engine Start](#) page.
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +- System Failures: A crucial aspect of any simulation is the unpredictability and the challenges it presents. Pilots can now set failures in various compontents. See our
```suggestion
- System Failures: A crucial aspect of any simulation is the unpredictability and the challenges it presents. Pilots can now set failures in various components. See our 
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +For the purposes of simulation we use it for providing technical support to our users and analyzing the same parameters and events. It allows us to troubleshoot issues like a drifting flight stick or
```suggestion
For the purposes of simulation, we use it for providing technical support to our users and analyzing the same parameters and events. It allows us to troubleshoot issues like a drifting flight stick or if the aircraft was stalled by pilot error or a bug in the flight model.
```

2023-10-27 13:06 UTC, Sleinmaster commented on docs/release-notes/v0110.md
> +enhancements include the transmission of annunciator light state, display, integral light brightness, and support for BRT/DIM keys. A few bugs, such as the FMGC annunciator light not illuminating and
```suggestion
enhancements include the transmission of annunciator light state, display, integral light brightness, and support for BRT/DIM keys. A few bugs, such as the FMGC annunciator light not illuminating and demanding QNH and TEMP readings when distant from the destination, have been addressed. The ZFW/ZFWCG autofill feature has been optimized to use desired values during the boarding process.
```

2023-10-27 13:14 UTC, Benjozork commented on docs/release-notes/v0110.md
> +Our latest flyPadOS brings forward server key enhancements and fixes that pilots can now enjoy.
```suggestion
Our latest flyPadOS brings forward serveral key enhancements and fixes that pilots can now enjoy.
```

2023-10-27 13:27 UTC, Valastiri commented on docs/release-notes/v0110.md
> +dedicated [Crossbleed Engine Start](#) page.
self note to fix the hyperlink here

2023-10-27 15:39 UTC, beheh commented on docs/fbw-a32nx/feature-guides/flypados3/index.md
> +    If you use the FlyByWire Stable version, you might not all features available. This will be appropriately flagged throughout our documentation.
Typo around "all". Missing a "have".

2023-10-27 15:41 UTC, beheh commented on docs/pilots-corner/beginner-guide/engine-start-taxi.md
> +    !!! warning "The CG scale available in the Asobo model of the flight deck is not entirely accurate for the A320neo. This is corrected in the [All Versions](https://docs.flybywiresim.com/fbw-a32nx
Don't we just cute this note?

2023-10-27 15:41 UTC, beheh commented on docs/pilots-corner/beginner-guide/landing.md
> +    You might ask what the blue dashed line is. It is part of the new FIX INFO feature which allows drawing distance rings or radial lines from navigation fixes. For this illustration, it helps us to
You could cut "new" here. I believe fix info has been a feature for 1-2 years.

2023-10-28 02:02 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/engine-start-taxi.md
> +    !!! warning "The CG scale available in the Asobo model of the flight deck is not entirely accurate for the A320neo. This is corrected in the [All Versions](https://docs.flybywiresim.com/fbw-a32nx
Ah yes I actually didn't read all the versioning info just changed them on the fly good catch!

2023-10-30 06:25 UTC, auroraisluna commented
Pasting from Discord: 
- under "Air Conditioning Simulation" you mention "ACSC (Air Conditioning System Controller)" shouldn't this just be like the MCDU text where it has the little underline and if you hover it explains the abbreviation? 
- ^ above section - "ARINC" same as above
- ^ - "TAPRV (Trim Air Pressure Regulating Valve) and TAV (Trim Air Valves)" same as above
perhaps for consistency with the later "PFD" section where its mentioned as "Navigation Display (__ND__)" follow this scheme instead?
- "ISIS" section does not have any abbreviation for what ISIS is
- also for consistency, shouldn't both the "SD" and "ISIS" have the little underline abbreviation explanation thingy as well? (see pic 1)   

otherwise LGTM

2023-10-30 06:57 UTC, Sleinmaster commented
> Pasting from Discord:
> 
> * under "Air Conditioning Simulation" you mention "ACSC (Air Conditioning System Controller)" shouldn't this just be like the MCDU text where it has the little underline and if you hover it explains the abbreviation?
> * ^ above section - "ARINC" same as above
> * ^ - "TAPRV (Trim Air Pressure Regulating Valve) and TAV (Trim Air Valves)" same as above
>   perhaps for consistency with the later "PFD" section where its mentioned as "Navigation Display (**ND**)" follow this scheme instead?
> * "ISIS" section does not have any abbreviation for what ISIS is
> * also for consistency, shouldn't both the "SD" and "ISIS" have the little underline abbreviation explanation thingy as well? (see pic 1)
> 
> otherwise LGTM

https://github.com/flybywiresim/docs/blob/primary/includes/abbreviations.example
For the examples, which can be copied.

I added the Arinc one as an example (might need some expansion), the other ones seem to be completely missing on our abbreviations page.

2023-10-30 06:57 UTC, auroraisluna commented
Also I think it should be mentioned a little bit more that the SimBrief Integration has changed (perhaps in addition to the FlyPad OS changes as well?) Im aware its mentioned at the start of the changes, but we both know if its not flashy with many arrows and circles, users (and users that will go to the #support channels mostly) will not read it :P

2023-10-30 14:14 UTC, Valastiri commented
> Also I think it should be mentioned a little bit more that the SimBrief Integration has changed (perhaps in addition to the FlyPad OS changes as well?) Im aware its mentioned at the start of the changes, but we both know if its not flashy with many arrows and circles, users (and users that will go to the #support channels mostly) will not read it :P

I think what i'll do is make sure it's highlighted at the top in better fashion (as it is the "start") where we'd capture the attention

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +    - Weather is inoperable as we wait for Asobo implementations.
Suggest changing "Weather is inoperable..." to "Weather radar is inoperable..."

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +    - MSFS Built-in ATC and VFR maps are on limited support. [Guides Here](#)
Suggest changing "..are on limited support" to something like "...are partially supported" or "are supported on a limited basis" or something like that

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +We are thrilled to introduce the foundational layer of the vertical navigation capabilities (VNAV) in the A32NX. This release incorporates the rudimentary vertical prediction and
To me the use of the word "rudimentary" here sounds like something that is barely thought out or functional. How about using a word like "basic," which works well with the mention of "advanced" later in the same sentence, and I think is what is meant here?

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +guidance functions, laying the groundwork for advance functionalities in future updates.
"advance" should be "advanced"

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +- Capability to set cruise steps directly in the MCDU.
What is the difference between this bullet (Capability to set cruise steps directly in the MCDU) and the one below it (Set cruise steps directly in the MCDU)?

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +    For an in-depth look at utilizing vertical guidance in the A32NX including what features are still in the pipeline see our dedicated advance guide below!
Suggest adding a comma between "A32NX" and "including"

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +    Additionally, our system can utilize MSFS METAR data, moving away from the older FSX cloud data original provided through the FBW API. This will ensure a more synchronized
"original provided" should be "original**ly** provided"

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +        Please note that due to Asobo model issues the animation of the left aft door will not be visible. Use the EFB or lower ECAM to verify the door status of the aircraft.
Is it worth adding that we intend to rectify this in the future with our own model?

2023-10-30 18:50 UTC, donstim commented on docs/release-notes/v0110.md
> +For the purposes of simulation, our support teams use it for providing technical support to our users and analyzing the same parameters and events. It allows us to troubleshoot issues like a drifting
Don't think the stall example is the best since we don't encounter an actual stall very often. Also, it would be very unlikely to have been caused by a flight model issue. Suggest something more like, "or if abnormal aircraft or display behavior is caused by pilot error, a hardware issue, an MSFS issue, or a bug in our simulation." (In fact, you can probably replace the whole sentence after "issues like a" with this.)

2023-10-31 02:40 UTC, Valastiri commented on docs/release-notes/v0110.md
> +    - MSFS Built-in ATC and VFR maps are on limited support. [Guides Here](#)
self note: realized there's no link here - fixed

2023-10-31 02:40 UTC, Valastiri commented on docs/release-notes/v0110.md
> +        Please note that due to Asobo model issues the animation of the left aft door will not be visible. Use the EFB or lower ECAM to verify the door status of the aircraft.
Definitely -- added thanks

2023-10-31 02:41 UTC, Valastiri commented on docs/release-notes/v0110.md
> +For the purposes of simulation, our support teams use it for providing technical support to our users and analyzing the same parameters and events. It allows us to troubleshoot issues like a drifting
used your suggested and stripped sentence after "troubleshoot"

2023-10-31 10:36 UTC, Valastiri commented
check build

2023-10-31 19:57 UTC, merged