docs(Getting Started): Performance Tips
flybywiresim/docs pull request #91
Opened 2021-06-23 13:04 UTC by benw202

This page features a series of optimisations to gain a simulator wide performance increase.

- [ ]  Windows Settings
- [ ] GeForce Experience
- [ ] Nvidia Control Panel
- [ ] MSFS

2021-06-23 13:37 UTC, Valastiri commented
Consider this in MSFS settings -> https://forums.flightsimulator.com/t/how-to-graphics-settings-and-performance-guide-3-16-2021/132407

2021-06-24 01:49 UTC, Valastiri requested changes
- Some typos addressed
- Formatting changes
- Small suggestions

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +- Under the `Gaming` tab in Windows settings, navigate to `Captures`. I would recomend turning off `Background Recording`.
```suggestion
- Under the `Gaming` tab in Windows settings, navigate to `Captures`. We would recommend turning off `Background Recording`.
```
Change to "we" and typo. 

Assume entire document is FBW authored

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +        You can now close Windows Settings.
```suggestion
        - Open Windows settings and search for `Graphics Settings`.

        - Under 'Choose an app to set preference, select `Microsoft Store App`. 

        - In the dropdown below, find and select `Microsoft Flight Simulator`, then add.

        - Click options, then select `High Performance`, save your selection.

        You can now close Windows Settings.
```

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +        You can now close Windows Settings.
```suggestion
        - Open Windows settings and search for `Graphics Settings`.

        - Under 'Choose an app to set preference, select `Desktop App` and click Browse

        You will need to locate the Microsoft Flight Simulator executable.

        The default location for steam is:

        - `C:\Program Files (x86)\Steam\steamapps\common\MicrosoftFlightSimulator\FlightSimulator.exe`

        (If you have it installed in another location, point it there instead)

        - Click options, then select `High Performance`, save your selection.

        You can now close Windows Settings.
```

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +- Lastly, I would recomend closing any programs running in the background that you don't need. This can be done in your system tray (the upwards pointing arrow to the right side of the task bar). Rig
```suggestion
- Lastly, we would recommend closing any programs running in the background that you don't need. This can be done in your system tray (the upwards pointing arrow to the right side of the taskbar). Right-click the icon of the program you would like to close and close it. 
```

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +    - You may have a lot of programs open here that you don't use often but start with Windows. You can stop them automatically runing by going to task manager, navigating to the `Start-up` tab and d
```suggestion
    - You may have a lot of programs open here that you don't use often but start with Windows. You can stop them automatically running by going to task manager, navigating to the `Start-up` tab and disabling programs you don't want to start with Windows.
```

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +    After an update in MSFS, it isn't unheard of that your graphics drivers may become 'out of date' and cause some performance issues.
```suggestion
    After an update to MSFS, it isn't unheard of that your graphics drivers may become 'out of date' and cause some performance issues.
```

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +    If this happens and you notice a decrease in performance, you can try rolling back your graphics driver until a new one is available.
Bit confused here. If the user's drivers are "out of date", why rollback after an update.

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +Alternatively, if you do want to use the overlay, you can leave it on, but turn off ShadowPlay individually by pressing `Alt + Z` and making sure `Instant Replay` is set to off. I would recommend dis
```suggestion
Alternatively, if you do want to use the overlay, you can leave it on, but turn off ShadowPlay individually by pressing ++alt+z++ and making sure `Instant Replay` is set to off. We would recommend disabling the overlay entirely though if you don't plan on using it.
```

Creates a key 
![image](https://user-images.githubusercontent.com/1619968/123189120-d3b36400-d4cf-11eb-94d7-6088f2935887.png)

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +(The less overlays you have running, the better performance you will get. Examples of overlays are the Steam Overlay, Windows Game Bar etc.)
```suggestion
(The fewer overlays you have running, the better performance you will get. Examples of overlays are the Steam Overlay, Windows Game Bar etc.)
```
This one is up 2 you. Just a grammatical word swap idea.

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +    I would also recommend having Vertical Sync set to `Use the 3D application setting` if choosing to apply these settings globally. This is because most games handle V-Sync well on their own, where
```suggestion
    We would also recommend having Vertical Sync set to `Use the 3D application setting` if choosing to apply these settings globally. This is because most games handle V-Sync well on their own, whereas MSFS doesn't currently.
```

2021-06-24 01:49 UTC, Valastiri commented on docs/start/perf-tips.md
> +    I would also recommend restarting your PC each time you experiment and change graphics settings from within Microsoft Flight Simulator.
So you can either remove the `---` here and leave the note **as is** OR try the suggestion below and see how it looks.

```suggestion

!!! note "Note"

    After applying all off these settings it is essential that you restart your PC for some of them to take effect.

    I would also recommend restarting your PC each time you experiment and change graphics settings from within Microsoft Flight Simulator.

[MSFS Settings Guide](https://forums.flightsimulator.com/t/how-to-graphics-settings-and-performance-guide-3-16-2021/132407){ .md-button }
```

2021-06-24 01:53 UTC, Valastiri commented on docs/start/perf-tips.md
> +- Lastly, I would recomend closing any programs running in the background that you don't need. This can be done in your system tray (the upwards pointing arrow to the right side of the task bar). Rig
Oh for this... shouldn't it be "end task" after the right-click?

2021-06-24 07:29 UTC, benw202 commented on docs/start/perf-tips.md
> +- Lastly, I would recomend closing any programs running in the background that you don't need. This can be done in your system tray (the upwards pointing arrow to the right side of the task bar). Rig
For closing things in the system tray? No, there are multiple variations of the wording so I thought I would just type close. For example, discord says 'Close Discord', Nvidia stuff just says 'Close'

2021-06-24 07:32 UTC, benw202 commented on docs/start/perf-tips.md
> +    If this happens and you notice a decrease in performance, you can try rolling back your graphics driver until a new one is available.
Sometimes after a major update, the older driver is actually better for you than the newer driver. Nvidia might release a newer driver but it can cause a performance hit. In this case, it would then be best to roll back to the driver you were on until a new one comes out.

We can either re word this or get rid of it as it is one of the more advanced steps

2021-06-24 07:35 UTC, davidwalschots submitted a review, later dismissed

2021-06-24 07:35 UTC, davidwalschots commented on docs/start/perf-tips.md
> +!!! warning "Disclaimer"
Use the warning icon instead of !!!. Here and elsewhere.
```suggestion
⚠ Disclaimer ⚠
```

2021-06-24 07:35 UTC, davidwalschots commented on docs/start/perf-tips.md
> +Author Credit: *BenW on Discord*
Usually the writer of a piece is called "Author", not "Author Credit".
Note that someone else also uses the name BenW on Discord, there's no way of knowing which BenW wrote this. If you want people to be able to send you messages, include the numeric ID of the Discord name.
```suggestion
Author: BenW on Discord
```

2021-06-24 07:35 UTC, davidwalschots commented on docs/start/perf-tips.md
> +    **Please note, this is for Nvidia Graphics cards only**
On any code block, the formatting inside the code block won't work.
I wouldn't make anything a code block, because you're not writing code.
Make everything a regular text block.

Decrease the usage of paragraphs.

I'll make a suggestion for this block, but the same applies elsewhere.

```suggestion
This guide is for a simulator wide performance increase. Your results may vary depending on your hardware and other outside factors. This means you may experience no performance increase so please make a note of existing settings in case you need to revert.

**This guide is for Nvidia graphics cards only.**
```

2021-06-24 07:35 UTC, davidwalschots commented on docs/start/perf-tips.md
> +    After an update in MSFS, it isn't unheard of that your graphics drivers may become 'out of date' and cause some performance issues.
of? 😀

2021-06-24 07:41 UTC, benw202 commented on docs/start/perf-tips.md
> +Author Credit: *BenW on Discord*
Ahh okay. I was following the format from another page! https://docs.flybywiresim.com/airliner-flying-guide/overview/

2021-06-24 07:42 UTC, benw202 commented on docs/start/perf-tips.md
> +    I would also recommend restarting your PC each time you experiment and change graphics settings from within Microsoft Flight Simulator.
Line 131 needs a 'we' too

2021-06-24 07:45 UTC, davidwalschots commented on docs/start/perf-tips.md
> +Author Credit: *BenW on Discord*
I understand. Maybe @tshomas or someone else can also change their "Author Credit" 😀.

2021-06-24 08:22 UTC, benw202 commented on docs/start/perf-tips.md
> +!!! warning "Disclaimer"
Will this still provide the same format as before?

![image](https://user-images.githubusercontent.com/67422707/123228767-a1a10280-d4cd-11eb-8bbd-f51ccc009185.png)

2021-06-24 09:09 UTC, davidwalschots commented on docs/start/perf-tips.md
> +!!! warning "Disclaimer"
Hmmm. Interesting. It seems we're not really using Markdown then 😅?

2021-06-24 09:11 UTC, davidwalschots commented on docs/start/perf-tips.md
> +    **Please note, this is for Nvidia Graphics cards only**
Given that we're not using markdown. I guess my comment here also doesn't make sense (other than that I think having less paragraphs is better).

2021-06-24 15:00 UTC, Valastiri commented on docs/start/perf-tips.md
> +- Lastly, I would recomend closing any programs running in the background that you don't need. This can be done in your system tray (the upwards pointing arrow to the right side of the task bar). Rig
Oh for some reason I was thinking you were in task manager. Carry on :P

2021-06-24 15:19 UTC, Valastiri commented on docs/start/perf-tips.md
> +Author Credit: *BenW on Discord*
> I understand. Maybe @tshomas or someone else can also change their "Author Credit" 😀.

Didn't realize this initially. I'll update the airliner guide accordingly as this is a good idea.

2021-06-24 15:25 UTC, Valastiri commented on docs/start/perf-tips.md
> +    I would also recommend restarting your PC each time you experiment and change graphics settings from within Microsoft Flight Simulator.
Oh can you change the `!!! note "Note"` to -> `!!! info "Note"`

the `!!! note` isn't styled with our colors :P and it's a bit of a pain to go fix that when info already is and achieves the same function.

2021-06-25 06:18 UTC, Valastiri approved these changes

2021-06-25 08:25 UTC, Valastiri commented
lgtm!

2021-06-25 08:25 UTC, merged