docs(beginner-guide): Descent page
flybywiresim/docs pull request #92
Opened 2021-06-25 23:16 UTC by frankkopp

First draft/version:

- [ ] Basic structure
- [ ] Descent Planning
- [ ] Starting the Descent
- [ ] Flying the STAR and Approach
- [ ] Intercepting ILS

Needs pilot review for accuracy.

2021-07-02 13:24 UTC, Valastiri requested changes
Some suggestions left open to discussion // grammar issues.

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +    Find a commented ILS approach chart here: [Approach Chart](../airliner-flying-guide/navigation.md#chart-sample-1)
```suggestion
    Find an overview of ILS approach charts here: [Approach Chart](../airliner-flying-guide/navigation.md#chart-sample-1)
```

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +    Find a commented ILS approach chart here: [Approach Chart](../airliner-flying-guide/navigation.md#chart-sample-1)
Actually I get what you are saying here, could also say
"Understand important ILS approach chart features here:"

Your discretion.

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +    Find a commented ILS approach chart here: [Approach Chart](../airliner-flying-guide/navigation.md#chart-sample-1)
See previous comment

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +    There are several good sources for charts - free or subscription based. A good free solution is [Chartfox](https://chartfox.org/) which only requires a free VATSIM account. One of the most known
```suggestion
    There are several good sources for charts - free or subscription based. A good free solution is [Chartfox](https://chartfox.org/) which only requires a free VATSIM account. One of the most known subscription based sources for charts is [Navigraph](https://navigraph.com/home). It is planned to integrate both solutions into the FlyByWire A32NX flyPad in the future.
```

Official branding is lowercase

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +    It is the sole responsibility of the pilot to conduct proper flight planning and especially proper descent planning. It is not at all ATC's task to do descent planning for pilots by giving descen
```suggestion
    It is the sole responsibility of the pilot to conduct proper flight planning and especially proper descent planning. It is not at all ATC's task to do descent planning for pilots by giving descent instructions. On the other hand ATC often actually gives descent instructions, especially on common routes, as they want the aircraft in their responsibility to be at certain altitudes when approaching the destination airport. Nevertheless pilots must know when passing approaching their planned top of descent and if necessary need to pro-actively request clearance to descend from ATC.
```

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +- **Cruise Flight Level:** The higher we fly the earlier we need to start descending. Also for short flights a too high cruising altitude can make it impossible to actually descent to the destination
```suggestion
- **Cruise Flight Level:** The higher we fly the earlier we need to start descending. Also for short flights a too high cruising altitude can make it impossible to actually descend to the destination airport in time. Therefore verify your flight plan if overall distance and flight level makes sense.
```

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +5. Use the MCDU PROG page's DIST function to read out the current distance to this waypoint. It is also possible to use the ECAM flight plan, maps or the NDs distance rings to help determining the cu
Shouldn't this be MCDU flight plan page? Unless pilot's said otherwise and I'm not aware of a feature on the ECAM. 
```suggestion
5. Use the MCDU PROG page's DIST function to read out the current distance to this waypoint. It is also possible to use the MCDU flight plan page, maps or the NDs distance rings to help determining the current distance.
```

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +!!! warning "Advanced arrival planning"
```suggestion
!!! warning "Important Notice"
```
Or variation thereof, so the warning + title isn't the same

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +- **Aircraft capability and passenger comfort:** Although not a big concern in the A320, general aircraft capabilities and passenger comfort also come into play. Descending with -4000ft/min is no fun
```suggestion
- **Aircraft capability and passenger comfort:** Although not a big concern in the A320neo, general aircraft capabilities and passenger comfort also come into play. Descending with -4000ft/min is no fun for a passenger.
```

You used neo elsewhere, possibly keep standard? Or choose one throughout the document. (Will check this across the entire guide later).

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +If we used Simbrief for flight planning we can also see METAR information on the FlyPad after importing the Simbrief plan to the FlyPad.
```suggestion
If we used Simbrief for flight planning we can also see METAR information on the flyPad after importing the Simbrief plan to the FlyPad.
```
Change all flyPad.

2021-07-02 13:24 UTC, Valastiri commented on docs/beginner-guide/descent.md
> +- Distance to descent point is calculated (= TOD - top of descent)
```suggestion
- Distance to descent point is calculated = TOD (top of descent)
```
Usually defining acronyms is formatted as: `Acronym` (Definition)

2021-07-03 08:50 UTC, frankkopp commented on docs/beginner-guide/descent.md
> +    It is the sole responsibility of the pilot to conduct proper flight planning and especially proper descent planning. It is not at all ATC's task to do descent planning for pilots by giving descen
I assume you meant either passing or approaching

2021-07-03 08:56 UTC, frankkopp commented on docs/beginner-guide/descent.md
> +- Distance to descent point is calculated (= TOD - top of descent)
Distance to descent point is calculated, which is called TOD (top of descent)

2021-07-03 08:57 UTC, frankkopp commented on docs/beginner-guide/descent.md
> +- **Cruise Flight Level:** The higher we fly the earlier we need to start descending. Also for short flights a too high cruising altitude can make it impossible to actually descent to the destination
Haha - I do this all he time - hard for me. Maybe you as a native speaker immediately hear or see this. I have to think every time if it is a noun or verb.

2021-07-04 14:18 UTC, Valastiri approved these changes

2021-07-05 04:32 UTC, Valastiri commented
Reviewed by Tarek + Shomas

2021-07-05 04:33 UTC, merged