docs: Rudder/pedal instructions
flybywiresim/docs pull request #929
Opened 2024-01-14 11:20 UTC by tohoku

## Summary
Having spent a lot of time trying to get to the bottom of my rudder pedal settings, I suggest adding a page to the FBW documentation page to save other people the headache. Initially I thought this was a problem with the FBW A320 flight model which stopped me from taxiing properly.

The FS2020 forums contain a lot of contradicting information, and I have yet to find a post which describes the correct settings.

I am hoping others can chime in with settings for other pedals than the Thrustmaster ones.

### Location

docs/fbw-a32nx/rudder.md
docs/fbw-a32nx/assets/rudder/*.jpg

Discord username (if different from GitHub):

2024-01-14 11:33 UTC, Sleinmaster requested changes

2024-01-14 11:33 UTC, Sleinmaster commented on docs/fbw-a32nx/rudder.md
> +If the Joystick L-Axis X/Y indicators only move from the center of the graphs to the left bottom, you will need to calibrate your pedals.
Should probably apply for any state where it doesn't go from 0 to 100, no matter the direction.

2024-01-14 13:01 UTC, frankkopp commented
I'm not really sure we need this. The A32NX does NOT need any special rudder configuration.
It works as any other aircraft in the sim in regards to rudder. 
Only difference is to disable Assistance Functions (Auto Rudder) which should be off anyway as per our recommendations.
Even when enabling the Tiller the configuration of the rudder still works but will be limited to 6° of turn (see Tiller docs). 

I would rather not start documenting standard MSFS stuff. 
If at all this could be under Support Reported Issues (https://docs-git-fork-tohoku-ruddersettings-flybywire.vercel.app/fbw-a32nx/support/reported-issues/) as a solution to rudder not working properly even if Assistance is turned off.

2024-01-14 18:20 UTC, Valastiri commented
I think there is a use case for this if it lives under recommended settings. If we can agree on that I'll provide further review as it's not setup appropriately currently anyways.

We do recommend some basic settings be enabled for rudder pedal compatibility but that's for racing pedals. I don't mind further documentation as just makes us more complete in a sense.

2024-01-14 21:27 UTC, frankkopp commented
> I think there is a use case for this if it lives under recommended settings. If we can agree on that I'll provide further review as it's not setup appropriately currently anyways.
> 
> 
> 
> We do recommend some basic settings be enabled for rudder pedal compatibility but that's for racing pedals. I don't mind further documentation as just makes us more complete in a sense.
> 
> 
> 
> > Think along the lines of "additional considerations" 

I see it more under the issue section as normally this the default setting anyway. And recommended settings document thing which are not default. Might even confuse people there.

2024-01-15 06:15 UTC, Valastiri commented
> > I think there is a use case for this if it lives under recommended settings. If we can agree on that I'll provide further review as it's not setup appropriately currently anyways.
> > We do recommend some basic settings be enabled for rudder pedal compatibility but that's for racing pedals. I don't mind further documentation as just makes us more complete in a sense.
> > > Think along the lines of "additional considerations"
> 
> I see it more under the issue section as normally this the default setting anyway. And recommended settings document thing which are not default. Might even confuse people there.

Oh if it's more of a default setting then yea issues would be more appropriate. However, would be pretty bulky considering how much text is in this PR in general.

@tohoku Give us a bit to consider where is the best place to live but thanks for the PR nonetheless.

2024-01-15 08:01 UTC, tohoku commented
Everyone, thank you for your kind feedback,

I should probably tell you the reason why I went down this rabbit hole in the first place: I have been an enthusiast since MSFS 5.0, but I only installed the FBW A32NX for the first time last week.

I immediately ran into problems with taxiing. I could push back and start taxiing, but as soon as I hit the brakes I couldn't get the plane to move again. Initially I thought there was a problem with the FBW flight model and uninstalled all add-ons, but the problem consisted. (I did check that I had all the Assistance Functions set to off.)

Then I switched back to the default Asobo A320 but did not notice any problems with taxiing. (It seems like the Asobo A320 is more forgiving with the toe brake settings when taxiing?)

I can put the info in this PR up on a forum, but my impression from reading all the MSFS forums is that this (taxiing and toe brakes) is a challenge people mostly run into after moving from the Asobo A320 to a more advanced plane.

Based on the above, I would argue that the lack of concise info out there may be stopping new users from enjoying the FBW A32NX, leading them to give up.

2024-01-16 04:47 UTC, Valastiri commented
@tohoku We ran this buy our support team for some additional input. I believe there's a general consensus to add this into the docs but not where it is currently. 

There were two choices:

1. As an issue in the reported issues with a link to the pages you made.
2. As a subpage or included in the `Common Hardware` section in the API and Hardware as an additional reference. 

We are leaning towards the second choice. If you need help setting this up please let us know or we can access the PR and move the files around for you.

2024-01-16 07:34 UTC, tohoku commented on docs/fbw-a32nx/rudder.md
> +If the Joystick L-Axis X/Y indicators only move from the center of the graphs to the left bottom, you will need to calibrate your pedals.
@Sleinmaster The instructions have been updated to be more generic.

2024-01-16 07:42 UTC, tohoku commented
@Valastiri - thanks for the suggestions. I have updated the page as suggested in alternative 2 with a subpage for detailed settings.

![rudder-update](https://github.com/flybywiresim/docs/assets/932621/7f2a166e-46b9-4bd8-9283-ddcf7a167043)

2024-01-16 07:59 UTC, Valastiri commented
> @Valastiri - thanks for the suggestions. I have updated the page as suggested in alternative 2 with a subpage for detailed settings.
> 
> ![rudder-update](https://private-user-images.githubusercontent.com/932621/296968227-7f2a166e-46b9-4bd8-9283-ddcf7a167043.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTIxNjcsIm5iZiI6MTcwNTM5MTg2NywicGF0aCI6Ii85MzI2MjEvMjk2OTY4MjI3LTdmMmExNjZlLTQ2YjktNGJkOC05MjgzLWRkY2Y3YTE2NzA0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwNzU3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTMzNTlkZTlkMzMzNWYwMzM4Nzk0OWEwMDQ3MzdiMDYyNDU5ZTI2MTU3ZmRkYTJkNzViNGFjNTExZTQ5M2Y4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7tui_-yxsR5Q1-8S34P_BU2YKF-qLW8CO6sOX5nPbws)

That's great -- we're still going through some discussion on where exactly this should live and if it's alright with you a maintainer might move things around for ya. Just so we logically have this in the right place.

2024-01-16 08:08 UTC, tohoku commented
@Valastiri Sure, no worries at all.

2024-01-16 08:46 UTC, frankkopp commented
I moved the page to the support section and added a "Rudder Operation Issue".

![image](https://github.com/flybywiresim/docs/assets/16833201/0896d885-7e8c-464c-b833-fb45da385c1a)

![image](https://github.com/flybywiresim/docs/assets/16833201/e77443d1-213a-4028-aff7-858b239a92c6)

@tohoku could you please double check all your images - her are some links to discord for how to do this:
https://discord.com/channels/738864299392630914/791494566058000434/907228632206962738
https://discord.com/channels/738864299392630914/791494566058000434/1121099138369605723

2024-01-16 09:24 UTC, tohoku commented
@frankkopp Thanks for the directions. I have updated the images to be max 826px wide and < 100 KB.

2024-01-16 09:27 UTC, tohoku commented
One more thing, maybe adding a link to the "Rudder Operation Issues" section on the support page from the "Unable to Move and Taxi" section is appropriate?

https://docs-pivophukd-flybywire.vercel.app/fbw-a32nx/support/reported-issues/#unable-to-move-or-taxi

2024-01-16 09:36 UTC, frankkopp commented
> One more thing, maybe adding a link to the "Rudder Operation Issues" section on the support page from the "Unable to Move and Taxi" section is appropriate?
> 
> [docs-pivophukd-flybywire.vercel.app/fbw-a32nx/support/reported-issues/#unable-to-move-or-taxi](https://docs-pivophukd-flybywire.vercel.app/fbw-a32nx/support/reported-issues/#unable-to-move-or-taxi)

Good idea - was thinking about this as well. Go ahead!

Thanks for your contribution - really well done.

2024-01-16 11:24 UTC, Sleinmaster reviewed
Some small corrections and then it's good to go from my side.

2024-01-16 11:24 UTC, Sleinmaster commented on docs/fbw-a32nx/support/detail-pages/rudder.md
> +2. Your game controllers should be displayed. Select your pedals (i.e. **`T-Rudder`**) from the list. Click the **`Properties`** button. ![USB Controller Settings](../../assets/rudder/GameControllers
```suggestion
2. Your game controllers should be displayed. Select your pedals (i.e., **`T-Rudder`**) from the list. Click the **`Properties`** button. ![USB Controller Settings](../../assets/rudder/GameControllersThrustmaster.jpg "USB Controller Settings"){loading=lazy}
```

2024-01-16 11:24 UTC, Sleinmaster commented on docs/fbw-a32nx/support/detail-pages/rudder.md
> +4. Click on the **`Test`** tab to confirm the settings. The cursor should be displayed in the bottom right corner (0% brakes applied) or top left corner (100% brakes applied), while the Z-Axis indica
```suggestion
4. Click on the **`Test`** tab to confirm the settings. The cursor should be displayed in the bottom-right corner (0% brakes applied) or top-left corner (100% brakes applied), while the Z-Axis indicator should be at 50% if the rudder is centered. ![Calibrated Settings](../../assets/rudder/GameControllersRudderSettings.jpg "Calibrated Settings"){loading=lazy}
```

2024-01-16 11:31 UTC, tohoku commented
> > One more thing, maybe adding a link to the "Rudder Operation Issues" section on the support page from the "Unable to Move and Taxi" section is appropriate?
> > [docs-pivophukd-flybywire.vercel.app/fbw-a32nx/support/reported-issues/#unable-to-move-or-taxi](https://docs-pivophukd-flybywire.vercel.app/fbw-a32nx/support/reported-issues/#unable-to-move-or-taxi)
> 
> Good idea - was thinking about this as well. Go ahead!
> 
> Thanks for your contribution - really well done.

@frankkopp Thank you. I am just happy to contribute to the FS2020 and FBW community!

2024-01-17 05:39 UTC, Valastiri commented
check build

2024-01-17 06:55 UTC, Valastiri commented
lgtm - was just checking due to the amount of moving files around in case anything was broken. 

If there are no other issues will merge today and thanks for the PR!

2024-01-19 17:54 UTC, merged