docs(bg): update sample flight in preparing-mcdu.md
flybywiresim/docs pull request #939
Opened 2024-02-05 16:45 UTC by Valastiri

## Summary
As indicated through our #docs channel on Discord the routing on the beginners guide is no longer applicable to the current AIRAC 2401. 

This PR updates that.

Current Changes
- Updated the PDF
- Updated the screenshots from PDF
- Completed initial text changes (requires final review)

### To Do
- [ ] Requires new in-sim MCDU Photos
- [ ] Confirm that the text matches the imagery.

### Location
- docs/pilots-corner/beginner-guide/preparing-mcdu.md
- docs/pilots-corner/assets/beginner-guide/mcdu/[...]

Discord username (if different from GitHub):
 valastiri

2024-02-11 02:33 UTC, frankkopp requested changes
Initial review - I'll work through it with the aircraft tomorrow.

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Input the desired cruise flight level in this field. On our OFP, this is listed as `0190` or `FL190`.
```suggestion
Input the desired cruise flight level in this field. On our OFP, this is listed as `0240` or `FL240`.
```

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +`EGFF/30 BCN1A BCN P69 DIZIM N864 MONTY AXCIS1M EGCC/23R`
```suggestion
`EDDM/08L GIVMI6Q GIVMI Y101 ERNAS T161 DEBHI DEBHI1C EDDF/07L`
```

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +        The airwayS `Y101` and `T161` was replaced with `DCT` indicating from waypoint `GIVMI` proceed direct to `ERNAS` and after that proceed direct to `DEBHI`.
```suggestion
        The airways `Y101` and `T161` was replaced with `DCT` indicating from waypoint `GIVMI` proceed direct to `ERNAS` and after that proceed direct to `DEBHI`.
```

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Find `EDDF` in green in the flight plan OR select `EDFF` in white under `DEST` using the corresponding LSK.
```suggestion
Find `EDDF` in green in the flight plan OR select `EDDF` in white under `DEST` using the corresponding LSK.
```

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by ATC). The preceding legs are called MANUAL legs.In this flight plan we have a
```suggestion
    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by 
    ATC). The preceding legs are called MANUAL legs. These cannot and should not be deleted. See below link on how to 
    handle these. 
    
    In this flight plan we have a discontinuity between the STAR and approach procedure as shown below.
```

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +* We can also set the desired course to track `080` and press LSK2L to input it. (This is for a departure on runway 08L)
```suggestion
```

I would leave that out as we have autotuning now. Doing this manually is not something a beginner should do.

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Our departure runway is EDDM/08l (runway 08 left) which has a frequency of `109.50`. When inputting a frequency, and we are in range of the ILS, it will autopopulate the identifier and course. There
```suggestion
Our departure runway is EDDM/08L (runway 08 left) which has a frequency of `109.50`. When inputting a frequency, and we are in range of the ILS, it will auto populate the identifier and course. You could also enter the identifier `IMNE` and it would automatically fill in the frequency. You cannot enter both at the same time as this would result in a `FORMAT ERROR`. 
```

2024-02-11 02:33 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Remember, our arrival airport/rwy is `EDDF/07l` with ILS07l having a frequency of `110.30`. When inputting a frequency, and we are in range of the ILS, it will autopopulate the identifier and course.
```suggestion
Remember, our arrival airport/rwy is `EDDF/07L` with ILS07L having a frequency of `110.30`. When inputting a frequency, and we are in range of the ILS, it will auto populate the identifier and course. There is no need to fill these fields. You could also enter the identifier `IFEL` and it would automatically fill in the frequency. You cannot enter both at the same time as this would result in a `FORMAT ERROR`. 
```

2024-02-11 05:21 UTC, Valastiri commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by ATC). The preceding legs are called MANUAL legs.In this flight plan we have a
I'm on GitHub but I might have forgotten to include it (and also forgot the title) -- but I meant to show a photo here of a MANUAL and F-PLN Disco just before we offload the user to a new page.

2024-02-11 10:09 UTC, Sleinmaster requested changes

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
>  * Select the runway we are departing from. In this case `30` using LSK3L
```suggestion
* Select the runway we are departing from. In this case `08L` using LSK3L
```

The LSK should also be corrected, didn't see a screenshot for it.

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
>      Let's imagine for this example that there was no airway between `BCN` and `OKTEM`. The flight plan would look like the following:
```suggestion
    Let's imagine for this example that there was no airway between `GIVMI` and `ERNAS`, as well as between `ERNAS` and `DEBHI`. The flight plan would look like the following:
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +        The airways `Y101` and `T161` was replaced with `DCT` indicating from waypoint `GIVMI` proceed direct to `ERNAS` and after that proceed direct to `DEBHI`.
```suggestion
        The airways `Y101` and `T161` were replaced with `DCT` indicating from waypoint `GIVMI` proceed direct to `ERNAS` and after that proceed direct to `DEBHI`.
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +  * A designator such as Y or Z may be present. This suffix is to distinguish in the navigation database a difference between approaches to the same runway. While similar in nature they may have diff
```suggestion
  * A designator such as Y or Z may be present. This suffix is to distinguish in the navigation database a difference between approaches to the same runway. While similar in nature, they may have different minimums, allowed equipment, or other differences.
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +* For the approach VIA Select `DF454` using the appropriate LSK. On the following page we can choose transitions if available, but for this flight we don't.
```suggestion
* For the approach VIA, select `DF454`, using the appropriate LSK. On the following page, we can choose transitions, if available, but for this flight, we don't.
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by ATC). The preceding legs are called MANUAL legs.In this flight plan we have a
```suggestion
    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by ATC). The preceding legs are called MANUAL legs. In this flight plan, we have a discontinuity between the STAR and approach procedure, as shown below.
```

or add this correction accordingly to mavs suggestion.

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +On this departure SID, we have routing instructions that rely on the Munich VOR `DMN` with a frequency of `116.0`
```suggestion
On this departure SID, we have routing instructions that rely on the Munich VOR `DMN` with a frequency of `116.0`.
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Our departure runway is EDDM/08L (runway 08 left) which has a frequency of `109.50`. When inputting a frequency, and we are in range of the ILS, it will auto populate the identifier and course. You c
```suggestion
Our departure runway is EDDM/08L (runway 08 left), which has a frequency of `109.50`. When inputting a frequency, and we are in range of the ILS, it will autopopulate the identifier and course. You could also enter the identifier `IMNE` and it would automatically fill in the frequency. You cannot enter both at the same time, as this would result in a `FORMAT ERROR`. 
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Remember, our arrival airport/rwy is `EDDF/07L` with ILS07L having a frequency of `110.30`. When inputting a frequency, and we are in range of the ILS, it will auto populate the identifier and course
```suggestion
Remember, our arrival airport/rwy is `EDDF/07L` with ILS07L having a frequency of `110.30`. When inputting a frequency, and we are in range of the ILS, it will autopopulate the identifier and course. There is no need to fill these fields. You could also enter the identifier `IFEL` and it would automatically fill in the frequency. You cannot enter both at the same time, as this would result in a `FORMAT ERROR`. 
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Look at the upper ECAM and note the FOB indicated. Let's say that amount is `4631 kg`. When inputting the block fuel into the MCDU, it is referenced in "Tons" and we should round to the closest decim
```suggestion
Look at the upper ECAM and note the FOB indicated. Let's say that amount is `4631 kg`. When inputting the block fuel into the MCDU, it is referenced in "tons", and we should round to the closest decimal point.
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +Our SID chart mentions that the TRANS ALT for this departure is 5000ft.
```suggestion
Our SID chart mentions that the TRANS ALT for this departure is 5000 ft.
```

2024-02-11 10:09 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +We can use the planned block fuel stated on the OFP, which in this case is `4631 kg`.
```suggestion
We can use the planned block fuel stated on the OFP, which in this case is `4631 kg`.
```

2024-02-11 13:46 UTC, frankkopp requested changes

2024-02-11 13:46 UTC, frankkopp commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by ATC). The preceding legs are called MANUAL legs. In this flight plan we have
```suggestion
    Sometimes discontinuities are also part of a procedure to indicate that manual input is required (mostly clearance by ATC). The preceding legs are called MANUAL legs.  These cannot and should not be deleted. See below link on how to 
    handle these. 
    
    In this flight plan we have a discontinuity between the STAR and approach procedure as shown below.
```

2024-02-11 13:46 UTC, frankkopp approved these changes

2024-02-13 12:25 UTC, Sleinmaster approved these changes
One minor suggestion, else good to go.

2024-02-13 12:25 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    **Discontinuities after a MANUAL leg cannot and should not be deleted. See below link on how to
```suggestion
    **Discontinuities after a MANUAL leg can not and should not be deleted. See below link on how to 
```
I would separate the cannot to emphasize the not.

2024-02-17 09:24 UTC, Valastiri commented
I missed the approvals on this apologies. Thanks for the assist :)

2024-02-17 09:26 UTC, merged