docs(beginner-guide): Final Approach and ILS Llanding
flybywiresim/docs pull request #94
Opened 2021-06-29 10:07 UTC by frankkopp

- [ ] Basic structure
...

Needs pilot review for accuracy.

2021-07-06 11:46 UTC, tareksabet commented
LGTM

2021-07-07 12:10 UTC, Valastiri requested changes
Single typo + one suggestion.

2021-07-07 12:10 UTC, Valastiri commented on docs/beginner-guide/landing.md
> +# Final Appraoch and ILS Landing
```suggestion
# Final Approach and ILS Landing
```

2021-07-07 12:10 UTC, Valastiri commented on docs/beginner-guide/landing.md
> +We let the front gear settle gently on the runway (don't slam it down) and hold the center line of the runway while we are reducing speed. The speed reduction should be monitored on the `PFD` speedba
is speedband one word? or two words? "speed bank". If Airbus moniker leave as is

2021-07-07 12:21 UTC, Valastiri approved these changes

2021-07-07 12:21 UTC, merged