feat(flypad-settings): Move Simbrief Import section & introduce navigraph section
flybywiresim/docs pull request #946
Opened 2024-03-04 02:34 UTC by alepouna

## Summary

Moves the Simbrief Import description from ATSU/AOC to 3rd Party Settings, as it is being moved with https://github.com/flybywiresim/aircraft/pull/8548. 

This PR also introduces a section for Navigraph in the '3rd Party Settings' as it was missing. Please add reviews for the text, as I am not sure how correct it is in terms of grammar and sense. 

I am also attaching here my screenshots for replacement in settings.md Lines 223 & 265 but I am unsure if they are fine, LMK. 

![FlightSimulator_nj5Hm5gSVd](https://github.com/flybywiresim/docs/assets/98479040/32fbe7b4-a542-4a6b-8878-0e48330058f3)
![FlightSimulator_TWiUTRO3iK](https://github.com/flybywiresim/docs/assets/98479040/c4a7caa4-cade-4dc9-84f1-8796f3cf4606)

### Location

docs/fbw-a32nx/feature-guides/flypados3/settings.md 

Discord username (if different from GitHub): alepouna

2024-03-04 16:06 UTC, Valastiri submitted a review, later dismissed
Should be prudent to double check the SimBrief integration page here https://docs.flybywiresim.com/fbw-a32nx/feature-guides/simbrief/#setup-a32nx-simbrief-integration

Since it's a dedicated page and the flypad is more of a brief overview of the features shown on a page.

Your images are fine just make sure to optimize them for the web. Thanks for this!

2024-03-04 16:06 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    - Wizard to connect your Navigraph Account with the flypad.
```suggestion
    - Setup wizard to connect your Navigraph Account with the flypad.
```

2024-03-04 16:06 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    - Allows you use a custom Simbrief User ID if do not with to connect your Navigraph account or override the existing account link.
```suggestion
    - Allows users to input custom Simbrief User ID. For more information see [A32NX simBrief Integration](../simbrief/#setup-a32nx-simbrief-integration).
```
You might need to check the link here. (Most of the information is already described on the page). The main issue is that we don't have a specific header for this as it's in an admonition. Could implement this if required within the scope of this PR.

Reference page:
[fbw-a32nx/feature-guides/simbrief/#setup-a32nx-simbrief-integration]

2024-03-04 16:06 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    - Imports latest SimBrief flight automatically when starting the flyPad.
```suggestion
    - Imports the latest SimBrief flight automatically when powering on the flyPad.
```

2024-03-08 13:26 UTC, Sleinmaster requested changes, later dismissed

2024-03-08 13:26 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    - Allows you use a custom Simbrief User ID if do not with to connect your Navigraph account or override the existing account link.
```suggestion
    - Allows users to input a custom SimBrief User ID. For more information see [A32NX simBrief Integration](../simbrief/#setup-a32nx-simbrief-integration).
```
One additional correction based on Vals.

2024-03-08 13:26 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    - Choose which Terminal Area Forecast (TAF) service should be used.
```suggestion
    - Choose, which Terminal Area Forecast (TAF) service should be used.   
```

2024-03-09 12:44 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +    - Allows you use a custom Simbrief User ID if do not with to connect your Navigraph account or override the existing account link.
Ah thanks. Hid my review on this part. Please use Slein's

2024-03-10 06:30 UTC, alepouna commented
Review comments added, I will optimize the images and upload them. Thanks @Valastiri & @Sleinmaster

2024-03-15 13:15 UTC, Valastiri commented
@2hwk I'm a little confused why a review is requested when the A32NX PR is on do not merge. Please advise here or feel free ping me in Discord :)

2024-03-15 16:18 UTC, 2hwk commented
> @2hwk I'm a little confused why a review is requested when the A32NX PR is on do not merge. Please advise here or feel free ping me in Discord :)
> 
> Edit: This PR is also missing images cc: @alepouna

I think I meant to hit dismiss review not re-request, my bad

2024-03-15 17:02 UTC, Valastiri commented
Affirm thanks!

2024-03-23 06:32 UTC, alepouna commented
> Edit: This PR is also missing images cc: @alepouna

Images updated to an optimized version of those found in the PR description.

2024-04-02 12:01 UTC, merged