docs: add <meta> tags (group 2)
flybywiresim/docs pull request #951
Opened 2024-03-10 18:27 UTC by marcpicaud

Hey there!

## Summary
This PR adds `<meta>` tags to the pages listed as "Group 2" in #791 .

I kept the descriptions under 150 chars to avoid them being truncated, and I tried to keep them as descriptive, catchy and SEO friendly as possible. Feedback welcome if something can get improved !

### Location

- [Feature Guides](https://docs.flybywiresim.com/fbw-a32nx/feature-guides/) and all sub-pages within
- [API and Hardware](https://docs.flybywiresim.com/fbw-a32nx/a32nx-api/) and all the sub-pages within

2024-03-12 05:54 UTC, Valastiri requested changes
some suggestions and branding of our flyPadOS 3 changes

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/cFMS.md
> +description: Dive into the A32NX's custom FMS and stay informed with the latest known issues. Get tips for effective flight planning and troubleshooting.
```suggestion
description: Dive into the A32NX's custom FMS and stay informed with the latest known issues and troubleshooting tips.
```

Just to note there isn't much flight planning tips here and more of just information. Hence the suggestion.

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flight-planning.md
> +description: Discover how to load a flight plan into the FlyByWire A32NX across various methods, and seamlessly integrate it with your chosen ATC service.
```suggestion
description: Discover how to load a flight plan into the FlyByWire A32NX across various methods, and integrate it with your chosen ATC service.
```

More notes: the MSFS linking isn't very seamless and has it's own issues just removing that would help.

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/charts.md
> +description: Learn how to access and utilize charts on FlyPadOS3 with a Navigraph account or local files.
```suggestion
description: Learn how to access and utilize charts on flyPadOS 3 with a Navigraph account or local files.
```

branding

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/dashboard.md
> +description: A comprehensive guide on how to use the Dashboard widgets in FlyPadOS3 for the FlyByWire A32NX.
```suggestion
description: A comprehensive guide on how to use the Dashboard widgets in flyPadOS 3 for the FlyByWire A32NX.
```

branding

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/dispatch.md
> +description: Information about the Dispatch menu provided by FlyPadOS3 in the FlyByWire A32NX.
```suggestion
description: Information about the Dispatch menu provided by flyPadOS 3 in the FlyByWire A32NX.
```

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/ground.md
> +description: A comprehensive guide on how to use the ground services provided by FlyPadOS3 in the FlyByWire A32NX.
```suggestion
description: A comprehensive guide on how to use the ground services provided by flyPadOS 3 in the FlyByWire A32NX.
```

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/online-atc.md
> +description: Discover how to use online ATC services such as VATSIM or IVAO with FlyPadOS3 for the FlyByWire A32NX.
```suggestion
description: Discover how to use online ATC services such as VATSIM or IVAO with flyPadOS 3 for the FlyByWire A32NX.
```

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +description: A comprehensive guide covering the descent and landing performance calculators provided by FlyPadOS3 in the FlyByWire A32NX.
```suggestion
description: A comprehensive guide covering the descent and landing performance calculators provided by flyPadOS 3 in the FlyByWire A32NX.
```

2024-03-12 05:54 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/settings.md
> +description: Learn how to configure various aspects of flyPadOS3 itself in the FlyByWire A32NX, from aircraft options to 3rd party settings.
```suggestion
description: Learn how to configure various aspects of flyPadOS 3 itself in the FlyByWire A32NX, from aircraft options to 3rd party settings.
```

2024-03-17 18:12 UTC, marcpicaud commented
Hi there,

Appreciate the time you took to review the texts, thank you!
I've pushed the suggestions just now, sorry for the delay :)

Cheers

2024-03-20 11:46 UTC, Valastiri commented
No worries and lgtm! Appreciate it.

2024-03-20 11:46 UTC, Valastiri approved these changes

2024-03-20 11:48 UTC, merged