docs(beginner-guide): Powering Down page
flybywiresim/docs pull request #96
Opened 2021-07-02 08:29 UTC by frankkopp

- [ ] Basic structure
- [ ] Parking at the gate
- [ ] Disembarking passenger and luggage
- [ ] Securing the Aircraft

Needs pilot review for accuracy.
- [ ] Pilot Review

2021-07-04 14:13 UTC, Valastiri requested changes
Just minor typo things and one suggestion on the use of periods after the bullet points early in the document.

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This of course is only done if enough lighting is available to safe
Two options here (small typo):
```suggestion
- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This of course is only done if enough lighting is available to safely park into the gate.
```
```suggestion
- `NOSE TAXI` and `RWY TURN OFF` lights are usually turned off even before we turn into the gate to not blind the ground personnel. This of course is only done if enough lighting is available to safely park into the gate. Turn them off if they were used to assist in parking.
```

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +- Turn on `APU BLEED` before we turn off the engines
```suggestion
- Turn on `APU BLEED` before we turn off the engines.
```

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +- Turn on `APU BLEED` before we turn off the engines
Consider periods at the end of each checklist OR no periods. I think we've been standardizing periods for "text" and no periods for "instructions."

Author's choice (I didn't look at the previous PR's).

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +If external power is available the ground crew would have connected it by now and we can turn on `EXT PWR`. If we would turn off the APU depends on the turn around time. For a shutdown we do this aft
Switch to passive voice. Less of a question, more of a statement.

```suggestion
If external power is available the ground crew would have connected it by now and we can turn on `EXT PWR`. Turning off the APU depends on the turn around time. For a shutdown we do this after the passengers have disembarked to still have airflow in the cabin. See last chapter.
```

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +In real life there a many things starting automatically after parking at the gate. The jetway is connected to the aircraft, doors are opened, passengers disembark, cargo is unloaded, etc. The pilots
Grammatical suggestion / typo. Switch to "happen". Could also use "many things that start". Author's choice.

```suggestion
In real life, there are many things that happen automatically after parking at the gate. The jetway is connected to the aircraft, doors are opened, passengers disembark, cargo is unloaded, etc. The pilots don't have to do much to trigger these steps.
```

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +Taking care of passengers and luggage with the FlyByWire FlyPad:
```suggestion
Taking care of passengers and luggage with the FlyByWire flyPad:
```
Branding on flyPad for the rest need adjustment.

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +## Disembarking passengers and baggage
Capitalize since it's an h2 element

```suggestion
## Disembarking Passengers and Baggage
```

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +This concludes *Disembarking passengers and baggage*.
capitalize title here as well

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +- Turn of `NAV & LOGO` lights (as aircraft no longer has power)
```suggestion
- Turn off `NAV & LOGO` lights (as aircraft no longer has power)
```

2021-07-04 14:13 UTC, Valastiri commented on docs/beginner-guide/powering-down.md
> +- Turn off `APU MASTER` (expect the APU to still be AVAIL for a few minutes)
Maybe explain that APU AVAIL remaining is if you just recently turned off APU Bleeds within the last few minutes. Would require the APU to cooldown. If you feel like it's too much then ignore this. 

I asked it in the docs channel [here](https://discord.com/channels/738864299392630914/791494566058000434/861246919392231462) in case it gets lost.

2021-07-04 20:00 UTC, frankkopp commented on docs/beginner-guide/powering-down.md
> +- Turn on `APU BLEED` before we turn off the engines
I want to do them but sometimes forget

2021-07-05 05:04 UTC, Valastiri approved these changes

2021-07-05 05:04 UTC, merged