refactor: Multiple Aircraft Restructure
flybywiresim/docs pull request #964
Opened 2024-04-04 23:46 UTC by frankkopp

## Summary
TBD

### Location
TBD

Discord username (if different from GitHub): cdr-maverick

2024-10-29 07:10 UTC, donstim requested changes

2024-10-29 07:10 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +    !!! Note "Practically, it's only realistic to load a maximum of 220000 kg of fuel, as otherwise the take of weight would be above the MTOW"
This note is incorrect. With an empty airplane (that is, no passengers or cargo, the maximum amount fuel that can be loaded to not result in a weight above the maximum takeoff weight would be 510,000 - 300007 = 209993 kg, or just under 210,000 kg of fuel. Loading 220,000 kg of fuel will result in a weight of 520,007 kg, exceeding the MTOW (though not the maximum ramp weight of 562,000 kg). 

If anything, the note should say "Note: The actual maximum fuel load for any given flight will be less than the maximum fuel capacity. The fuel load at takeoff cannot be any greater than 510,000 kg (1,124,400 lb) minus the payload for the airplane's takeoff weight not to exceed the MTOW."

2024-10-29 07:10 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
The quantities quoted above are incorrect. The outers are 8301 kg (18301 lb each, the mids are 29,272 kg (64534 lb), the inners are 37,045 kg (81,669 lb), feeds 1&4 are 22,184 kg (48,907 lb) feeds 2&3 are 23,562 kg (51,946 lb), and the trim is 19,026 kg (41,944 lb),

2024-10-29 12:56 UTC, Valastiri commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
Both your comments have now been corrected thanks don

2024-10-30 18:45 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +    An acceptable range for takeoff CG in the A380X is between 15-45%. The CG is balanced during the passenger loading process.
Forward and aft cg limits for the A380X are 28-44%

2024-10-30 18:45 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +    Anything less than 25 % CG is considered FWD load, and anything more than 25 % is considered an AFT load. While opting to choose between either CG configuration (aft/fwd), please consider the inf
This cg value from the A32NX obviously does not apply to the A380X since the A380X's forward limit is 28%. I don't know that any such value has been defined for the A380. I recommend just deleting this sentence.

2024-10-30 18:45 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +    Most operators would favor an AFT CG loading for fuel consumption benefits when considering the lifetime of the fleet and how easy the benefits can be obtained.
Automatic fueling in the A380 targets a CG of approximately 39.5%. In-flight, the automatic fuel transfer system will transfer fuel from the trim tank to keep the CG forward of the aft limit.

(Check with 2cas to see if the first sentence is accurate for the A380X fueling system.

2024-10-30 18:45 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
This doesn't appear to be working in the A380X...

2024-10-30 18:45 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
Should it be stated that this value is in U.S. gallons? (At least that is what units I assume these values are in since that is what MSFS uses as its base unit value for fuel quantity.)

2024-10-30 18:45 UTC, donstim commented on docs/aircraft/a380x/index.md
> +    We aim for the outmost accuracy with our projects, and as such we want to hold on making a performance calculator that could potentially provide bad data.
"hold **off** on making..."?

2024-10-30 21:51 UTC, frankkopp commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +    Most operators would favor an AFT CG loading for fuel consumption benefits when considering the lifetime of the fleet and how easy the benefits can be obtained.
@2hwk - could you have a look - I leave it for now - we can also change this after publication

2024-10-30 22:06 UTC, frankkopp commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
Created an issue - will keep it in

2024-10-30 22:08 UTC, frankkopp commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
Did you check? If so we can mention it in case users want to manually modify. But why should they?

2024-10-30 23:08 UTC, donstim commented on docs/aircraft/a380x/feature-guides/loading-fuel-weight.md
> +
Yes, these numbers are in units of U.S. gallons. I only suggest mentioning this to be complete. Not a problem if you don't want to add it.

2024-10-31 11:50 UTC, Valastiri commented
check build

2024-10-31 13:30 UTC, Valastiri commented
check build

2024-10-31 13:36 UTC, merged