Mar bg ch6
flybywiresim/docs pull request #972
Opened 2024-04-13 16:14 UTC by Popespice

## Summary
Updates to chapter 6 of the Beginner Guide.

### Location
docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md

Discord username (if different from GitHub): Popespice

2024-04-13 16:19 UTC, Popespice reviewed
Not sure why this thinks i touched Chapter 3, i made sure to leave it alone during editing.

2024-04-14 15:11 UTC, frankkopp requested changes
Instead of the A32NX bg use the SOP as your template - e.g. you could even remove all the A320 stuff and build it up new (you can always copy stuff over)

2024-04-14 15:11 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/03_preparing-fms.md
these will be overwritten by straks

2024-04-14 15:11 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
> +    The level of detail in this guide is meant to get a FlyByWire A380X beginner safely from cruise level down to the ILS glideslope.
```suggestion
    The level of detail in this guide is meant to get a FlyByWire A380 beginner safely from cruise level down to the ILS glideslope.
```

2024-04-14 15:11 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
> +??? tip "Basics"
I would combine this into one collapsible  
Base Knowledge: Route, Star, Approach and ILS

2024-04-14 15:11 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
> +!!! note "Important Data Points for Descent Planning:"
```suggestion
!!! tip "Important Data Points for Descent Planning:"
```

2024-04-16 07:12 UTC, brocky120 commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
Never used Github before so apologies if this wrong place etc but noticed a typo here:

tip "VNAV in the FlyByWire A830X"

2024-04-16 07:12 UTC, 2hwk requested changes

2024-04-16 07:12 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
> +??? tip "VNAV in the FlyByWire A830X"
```suggestion
??? tip "VNAV in the FlyByWire A380X"
```

2024-04-18 01:39 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/.pages
> +    - 06_descent.md: 06_descent.md
![image](https://github.com/flybywiresim/docs/assets/15316958/eba86fb7-97db-436f-b1e4-fc0071969d60)

2024-04-18 01:40 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/03_preparing-fms.md
> +    Unfortunately, A380 performance data for FLEX temp performance calculators alongside other various tools are not publicly available and are guarded by Airbus. For the purposes of simulation, it's
```suggestion
    Unfortunately, A380 performance data for FLEX temp performance calculators alongside other various tools are not publicly available and are guarded by Airbus. For the purposes of simulation, it's important to note the following:
```

Will have to check with don etc to see the status of this, might be different from the 20n

2024-04-18 01:41 UTC, Popespice commented on docs/pilots-corner/a380x/a380x-beginner-guide/03_preparing-fms.md
> +    Unfortunately, A380 performance data for FLEX temp performance calculators alongside other various tools are not publicly available and are guarded by Airbus. For the purposes of simulation, it's
Let me know and i can apply it to the guide.

2024-04-18 01:44 UTC, 2hwk requested changes

2024-04-18 01:44 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
> +    There are several good sources for charts - free or subscription based. A good free solution is [ChartFox](https://chartfox.org/), which only requires a free VATSIM account. One of the most known
```suggestion
    There are several good sources for charts - free or subscription based. A good free solution is [ChartFox](https://chartfox.org/), which only requires a free VATSIM account. One of the most known subscription-based sources for charts is [Navigraph](https://navigraph.com/home). It is planned to integrate both solutions into the FlyByWire A380X flyPad in the future.
```

Perhaps could be updated as navigraph has been available for a while. So only Chartfox is TBD

2024-04-18 01:44 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
> +    There are several good sources for charts - free or subscription based. A good free solution is [ChartFox](https://chartfox.org/), which only requires a free VATSIM account. One of the most known
Also in A32NX bg

2024-04-18 01:44 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/06_descent.md
The second sentence of this may not apply (definitely no MCDU in the A380)

2024-04-29 12:11 UTC, merged