feat: update bg chapter 8
flybywiresim/docs pull request #976
Opened 2024-04-19 00:33 UTC by Popespice

## Summary
Updates to chapter 8 of the MAR BG

### Location
docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md

Discord username (if different from GitHub): Popespice

2024-04-21 10:02 UTC, frankkopp requested changes

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
> +    The level of detail in this guide is meant to get a FlyByWire A380X beginner from the runway to the designated destination gate.
```suggestion
    The level of detail in this guide is meant to get a Airbus A380 beginner from the runway to the designated destination gate.
```

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
>  [Download FlyByWire Checklist](../assets/sop/A32NX%20Documentation/FBW%20A32NX%20Checklist.pdf){ .md-button }
```suggestion
[Download FlyByWire Checklist](../assets/sop/A32NX%20Documentation/FBW%20A32NX%20Checklist.pdf){ .md-button }
<p style="color:yellow; font-size:18px;">TODO: update link</p>
```

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
>      ![EDDM ATC frequencies](../assets/beginner-guide/after-landing/EDDM-frequency-chart.png "EDDM ATC frequencies"){ loading=lazy }
needs to be changed to EDDF

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
the below should go into an admon

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
Same as in the review for chapter 9 - please use the A380 SOP as your guide not the "old" A32NX bg pages.
Remove all this floating text and use the SOP lines as much as you can. 
Use the "How and Where" admon below the sections. 

I will not repeat this comment throughout the whole page as it is the same for most of the sections. 

Example:
![image](https://github.com/flybywiresim/docs/assets/16833201/a7810567-088e-46df-a353-b250c2b4cc69)

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
> +`GROUND SPOILERS ...................................................... OFF`<br/>
![image](https://github.com/flybywiresim/docs/assets/16833201/5ef43934-6ab3-490a-a114-fbd72ea32a5d)
```suggestion
`GROUND SPOILERS ................................................... DISARM`<br/>
```

2024-04-21 10:02 UTC, frankkopp commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
in the A380 SOP the next item would be "Flaps", then APU

2024-04-23 13:19 UTC, 2hwk requested changes

2024-04-23 13:19 UTC, 2hwk commented on docs/pilots-corner/a380x/a380x-beginner-guide/08_after-landing.md
> +??? note "Starting the APOU"
```suggestion
??? note "Starting the APU"
```

2024-05-01 13:53 UTC, merged