feat: takeoff performance documentation
flybywiresim/docs pull request #986
Opened 2024-06-28 17:52 UTC by Valastiri

## Summary
In support of A32NX PR
- https://github.com/flybywiresim/aircraft/pull/8678

Utilizes doc from @donstim with populated data.

### Notes
I have split the pages into the general flypadOS 3 performance page AND a new advanced guide detailing how to use the calculator appropriately.

The EFB performance page has what the calculator is capable of and details on what each field is used for.

I'm not sure if we should include the entire example provided by Don on the EFB performance page or not. I have a use case to add this as an admonition with the entirety of the content and remove the advanced guides page.

## TODO

- [ ] Add media
- [ ] Spruce up media
- [ ] Organization
- [ ] Add rest of content from doc
- [ ] Utilize mkdocs material formula features 

### Location
- docs/fbw-a32nx/feature-guides/flypados3/performance.md
- docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md

Discord username (if different from GitHub): valastiri

2024-06-28 20:18 UTC, donstim requested changes

2024-06-28 20:18 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +1.	Determine if their airplane can take off at the intended takeoff weight from a designated runway at a specified temperature, wind, and QNH setting using a specified airplane configuration and blee
Suggest changing "Determine if their airplane" to "Determine if your airplane" to be consistent with "With this calculator, you can:"

2024-06-28 20:18 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +  performance page on the right side of the calculator. This is for information only at this point. You should not try to enter this value into the actual MCDU.
Probably should delete the last sentence and replace the preceding sentence with, "This is for information only at this point since the TO Shift entry in the MCDU Takeoff Perf Page is not yet implemented."

2024-06-28 20:18 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +has been loaded in the EFB](dashboard.md), airport and runway information (including runway bearing, TORA, runway elevation, and runway slop) as well as environmental data
"slope" is missing the "e" at the end in line 37

2024-06-28 20:18 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +Takeoff Weight: This is the weight at which the airplane begins the takeoff (after taxying to the runway). It can either be automatically entered from the OFP as described above or entered manually.
Need a header for the "Takeoff Weight" entry

2024-06-28 21:42 UTC, Meqolo commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +All input fields must be filled before the "Calculate" button becomes available. There are two ways in which certian inputs fields can be automatically filled. If [SimBrief data
Misspelled certain

2024-06-29 07:34 UTC, alepouna reviewed
Leaving some comments. For the `10-9A` remarks on the `performance.md` I feel like after one mention its enough, but perhaps alternatively we could add some 'on hover' mention of the 10-9A (or just reference it once as is), this is up to you - please note to not ignore the mention in `takeoff-perf-calc.md` regardless of previous choice

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +    To see more about how to plan and identify required information to input into the flyPad takeoff performance calculator, see our guide:
```suggestion
    To learn more about how to plan and identify the required information to input into the flyPad takeoff performance calculator, see our guide:
```

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +This will load the environment data used by your SimBrief flight plan. You can either change/update the environment data, or load it from scratch automatically without having
```suggestion
This will load the environmental data used by your SimBrief flight plan. You can either change/update the environmental data, or load it from scratch automatically without having 
```

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +from the MSFS 2020 runway length data and may not always be accurate. We recommend that you check the TORA distance with the airport 10-9 (or 10-9A) chart as shown in the examples that follow, especi
```suggestion
from the MSFS 2020 runway length data and may not always be accurate. We recommend checking the TORA distance with the airport 10-9 (or 10-9A) chart as shown in the examples that follow, especially if you plan an intersection departure. You should also reduce the TORA if you start on the runway, as MSFS 2020 typically places the airplane well forward of the beginning of the TORA.
```

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- If you enter a TORA that is less than the MSFS 2020 runway length, the difference will be shown at a TO Shift (takeoff shift) value in the replica of the MCDU takeoff
Two suggestions, choose whichever sounds better
```suggestion
- If you enter a TORA that is less than the MSFS 2020 runway length, the difference will be shown at the TO Shift (takeoff shift) value in the replica of the MCDU takeoff 
```
2
```suggestion
- If you enter a TORA that is less than the MSFS 2020 runway length, the difference will be shown at the TO Shift (takeoff shift) value in the replica of the MCDU performance page
```

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- This is the angle of the taxiway to the runway. An input is needed to allow the calculator to reduce the TORA distance by the distance that is used to align the airplane on
```suggestion
- This is the angle of the taxiway to the runway. An input is needed to allow the calculator to reduce the TORA distance by the distance used to align the airplane on 
```

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the runway for takeoff (since the runway behind the airplane should not be used to calculate takeoff performance). The entry angle can be determined from the airport 10-9 chart as shown in the exampl
```suggestion
the runway for takeoff (since the runway behind the airplane should not be used to calculate takeoff performance). The entry angle can be determined from the airport 10-9 (or 10-9A) chart as shown in the examples that follow.
```
added for consistency

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the airport 10-9 chart as shown in the examples that follow.
```suggestion
the airport 10-9 (or 10-9A) chart as shown in the examples that follow.
```

2024-06-29 07:34 UTC, alepouna commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +It can be automatically entered from either the OFP or the METAR as described above. If you enter the wind yourself, be sure you are entering the wind in terms of a magnetic direction rather than the
```suggestion
It can be automatically entered from either the OFP or the METAR as described above. If you enter the wind yourself, be sure you are entering the wind in terms of a magnetic direction rather than the true direction. ATIS winds will be provided in terms of a magnetic direction, but METAR winds are in terms of true direction. If you enter the METAR winds yourself, consult the airport 10-9 (or 10-9A) chart to determine the magnetic variation and convert the direction to magnetic as shown the examples that follow. If you choose to automatically enter the winds from the METAR, this conversion will be done automatically.
```

2024-06-29 07:34 UTC, alepouna commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +This is an advanced guide on how to calculate takeoff performance in the A32nx. This is to supplement information provided in our flyPadOS 3 documentation and usage guide.
```suggestion
This is an advanced guide on how to calculate takeoff performance in the A32NX. This is to supplement information provided in our flyPadOS 3 documentation and usage guide.
```

2024-06-29 07:34 UTC, alepouna commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +Information that can be obtained from Airport 10-9 charts
```suggestion
Information that can be obtained from Airport 10-9 (or 10-9A) charts
```

2024-06-29 08:08 UTC, Sleinmaster reviewed
First part of the Review, will check the advanced guide next.

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +3.	Determine the appropriate takeoff speeds, V1, VR, and V2 for the conditions specified.
```suggestion
This calculator lets the pilots:

1.	Determine if the airplane can take off at the intended takeoff weight from a designated runway at a specified temperature, wind, and QNH setting using a specified airplane configuration and bleed settings (A/I and A/C);
2.	Determine the Flex temperature if a reduced thrust setting (Flex) can be used; 
3.	Determine the appropriate takeoff speeds, V1, VR, and V2, for the conditions specified.
```

Consistency with the other sections.

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +data from**.
```suggestion
All input fields must be filled before the "Calculate" button becomes available. There are two ways in which certain input fields can be automatically filled. If [SimBrief data 
has been loaded into the EFB](dashboard.md), airport and runway information (including runway bearing, TORA, runway elevation, and runway slope), as well as environmental data 
(wind, temperature, and QNH), can be automatically filled in by selecting "OFP" in the upper right drop-down selection box and clicking on **Fill data from**.

This will load the environment data used by your SimBrief flight plan. You can either change/update the environment data or load it from scratch automatically without having 
loaded it from the OFP by ensuring the Airport input field in the calculator is filled, then selecting "METAR" in the upper right drop-down selection box and clicking on **Fill 
data from**.
```
The Buttons "Calculate" and "Fill data from" should be shown in the same way. Either both encapulated in " or printed bold (there might be other options).

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- Enter the ICAO code for the airport. See the examples that follow.
```suggestion
- Enter the ICAO code for the airport. See the following examples.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- This is the magnetic direction of the runway. It will be entered automatically after entering the runway number.
```suggestion
- This is the direction of the runway referenced to magnetic North. It will be filled automatically after entering the runway number.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +    This is for information only at this point since the TO Shift entry in the MCDU Takeoff Perf Page is not yet implemented.
```suggestion
- This is the length of the portion of the runway available for takeoff. It will be filled automatically after entering the runway number. Be aware that this information comes 
from the MSFS 2020 runway length database and may not always be accurate. We recommend that you check the TORA distance with the airport 10-9 (or 10-9A) chart as shown in the following examples, especially if you plan an intersection departure. You should also reduce the TORA if you start on the runway, since MSFS 2020 typically places the airplane well forward of the beginning of the TORA.
- If you enter a TORA that is less than the MSFS 2020 runway length, the difference will be shown as a TO Shift (takeoff shift) value in the replica of the MCDU takeoff 
  performance page on the right side of the calculator. 

!!! warning "TO Shift - Not Yet Implemented"
    This is for information only at this point, since the TO Shift entry in the MCDU Takeoff Perf Page is not yet implemented.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the airport 10-9 chart as shown in the examples that follow.
```suggestion
- This is the elevation of the runway at the beginning of the TORA. It will be automatically filled after entering the runway number. It can also be determined or checked from 
the airport 10-9 chart, as shown in the following examples.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the runway for takeoff (since the runway behind the airplane should not be used to calculate takeoff performance). The entry angle can be determined from the airport 10-9 chart as shown in the exampl
```suggestion
- This is the angle of the taxiway to the runway. An input is needed to allow the calculator to reduce the TORA distance by the distance that is used to align the airplane on 
the runway for takeoff (since the runway behind the airplane should not be used to calculate takeoff performance). The entry angle can be determined from the airport 10-9 chart as shown in the following examples.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the airport 10-9 chart, but requires a little calculation, as shown in the examples that follow. A negative slope is downhill, while a positive slope is uphill.
```suggestion
- This is the gradient of the runway in the direction of takeoff. It will be automatically filled after entering the runway number. It can also be determined or checked from 
the airport 10-9 chart, but requires a calculation from the data present on Jeppesen charts, as shown in the following examples. A negative slope is downhill, while a positive slope is uphill.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +for other runway conditions, be aware that MSFS 2020 currently does not simulate these surface conditions properly.
```suggestion
- This allows input of runway conditions, including dry, wet, and numerous types of runway contamination. It defaults to a dry runway. Although the calculations are provided 
for other runway conditions, be aware that MSFS 2020 currently does not simulate these surface conditions properly.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +It can be automatically entered from either the OFP or the METAR as described above. If you enter the wind yourself, be sure you are entering the wind in terms of a magnetic direction rather than the
```suggestion
- The wind can be input simply as the headwind component (a single positive number) or tailwind component (a single negative number), or it can be input in the form of degrees/kts. 
It can be automatically entered from either the OFP or the METAR as described above. If you enter the wind yourself, be sure you are entering the wind in terms of a magnetic direction rather than the true direction. ATIS winds will be provided in terms of a magnetic direction, but METAR winds are in terms of true direction. If you enter the winds from METAR, consult the airport 10-9 chart to determine the magnetic variation and convert the direction to magnetic, as shown in the following examples. If you choose to enter the winds automatically from the METAR, this conversion will be done automatically.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +based on either the active ATIS or METAR.
```suggestion
- This is the sea-level atmospheric pressure at the airport. It can be automatically filled from either the OFP or the METAR as described above. It can also be entered manually 
based on either the active ATIS or METAR.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +manually.
```suggestion
- This is the weight at which the airplane starts the takeoff (after taxiing to the runway). It can either be automatically entered from the OFP as described above or entered 
manually.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +calculator will inform you and perform the calculation with TOGA thrust.
```suggestion
- This is the thrust rating that will be used for takeoff. Flex (a reduced thrust) is the default, but TOGA can be selected. If Flex is selected but TOGA must be used, the 
calculator will inform you and perform the calculation with TOGA thrust.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +reduce the takeoff thrust.
```suggestion
- This refers to the setting of the anti-ice bleeds. It defaults to off. Select engine or engine + wing anti-ice if anti-ice will be used for takeoff. Using anti-ice will 
reduce the takeoff thrust.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +be off for takeoff. Turning the air conditioning packs off will allow the engines to produce more takeoff thrust.
```suggestion
- This refers to whether the air conditioning packs will be on for takeoff. It defaults to on, but can be changed to off if the air conditioning packs will 
be off for takeoff. Turning the air conditioning packs off allows the engines to produce more takeoff thrust.
```

2024-06-29 08:08 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +*[QNH]: sea level atmospheric pressure
```suggestion
*[TORA]: Take-Off Run Available
*[QNH]: sea level atmospheric pressure
*[OFP]: Operational Flight Plan
```

2024-06-29 08:14 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +This is an advanced guide on how to calculate takeoff performance in the A32NX. This is to supplement information provided in our flyPadOS 3 documentation and usage guide.
```suggestion
This is an advanced guide on how to calculate takeoff performance in the A32NX. This is meant to supplement information the provided in our flyPadOS 3 documentation and usage guide.
```

2024-06-29 08:14 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- Enter the ICAO code for the airport. See the examples that follow.
Replace with reference to the advanced guide.

2024-06-29 08:14 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +  performance page on the right side of the calculator.
```suggestion
- This is the length of the portion of the runway available for takeoff. It will be entered automatically after entering the runway number. Be aware that this information comes 
from the MSFS 2020 runway length data and may not always be accurate. We recommend checking the TORA distance with the airport 10-9 (or 10-9A) chart as shown in the examples that follow, especially if you plan an intersection departure. You should also reduce the TORA if you start on the runway, as MSFS 2020 typically places the airplane well forward of the beginning of the TORA.
- If you enter a TORA that is less than the MSFS 2020 runway length, the difference will be shown at the TO Shift (takeoff shift) value in the replica of the MCDU performance page
  performance page on the right side of the calculator. 
```
Replace "examples that follow" with reference to the advanced guide.

2024-06-29 08:14 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the runway for takeoff (since the runway behind the airplane should not be used to calculate takeoff performance). The entry angle can be determined from the airport 10-9 (or 10-9A) chart as shown in
```suggestion
- This is the angle of the taxiway to the runway. An input is needed to allow the calculator to reduce the TORA distance by the distance used to align the airplane on 
the runway for takeoff (since the runway behind the airplane should not be used to calculate takeoff performance). The entry angle can be determined from the airport 10-9 (or 10-9A) chart as shown in the examples that follow.
```
Replace "examples that follow" with reference to the advanced guide.

2024-06-29 08:14 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the airport 10-9 (or 10-9A) chart as shown in the examples that follow.
Replace "Examples that follow" with reference to the advanced guide.

2024-06-29 08:14 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +the airport 10-9 chart, but requires a little calculation, as shown in the examples that follow. A negative slope is downhill, while a positive slope is uphill.
Replace following examples with reference to the advanced guide.

2024-06-29 08:14 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +It can be automatically entered from either the OFP or the METAR as described above. If you enter the wind yourself, be sure you are entering the wind in terms of a magnetic direction rather than the
```suggestion
- The wind can be input simply as the headwind component (a single positive number) or tailwind component (a single negative number), or it can be input in the form degrees/kts. 
It can be automatically entered from either the OFP or the METAR as described above. If you enter the wind yourself, be sure you are entering the wind in terms of a magnetic direction rather than the true direction. ATIS winds will be provided in terms of a magnetic direction, but METAR winds are in terms of true direction. If you enter the METAR winds yourself, consult the airport 10-9 (or 10-9A) chart to determine the magnetic variation and convert the direction to magnetic as shown the examples that follow. If you choose to automatically enter the winds from the METAR, this conversion will be done automatically.
```
Replace following examples with reference to the advanced guide.

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +- Item 4 shows a common 90-degree entry from the taxiway to the runway, which requires a portion of the runway to align the airplane in the direction of the runway for takeoff.
```suggestion
- Item 1 is the elevation for a takeoff from Runway 09L. 
- Item 2 shows an example of a relatively rare zero-degree turn-on angle from the taxiway to the runway. This is denoted by the gray taxiway extending far enough after the turn 
  to align the airplane with the runway direction before it gets to the beginning of the runway (indicated by the beginning of the black runway diagram). 
- Item 3 is the elevation for a takeoff from Runway 27R. 
- Item 4 shows a common 90-degree entry from the taxiway to the runway, which requires a portion of the runway to align the airplane in the direction of the runway for takeoff.
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +Since the elevation of both end of the runway are the same, the slope for takeoffs from both Runway 09L and 27R is zero.
```suggestion
Since the elevations of both ends of the runway are the same, the slope for takeoffs from both Runway 09L and 27R is zero. 
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +    The magnetic varation for this airport is show by the arrow on the lower right side of the chart.
```suggestion
    The magnetic variation for this airport is shown by the arrow on the lower-right side of the chart. 
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +intersection takeoffs is provided on the 10-9A chart. For a Runway 09L full length takeoff, the TORA is 12,001 feet or 3901 meters.
```suggestion
For a large airport like EGLL, there is not enough space to add the additional runway information on the 10-9 chart. In this case, TORA distance for each runway and for 
intersection takeoffs is provided on the 10-9A chart. For a Runway 09L full-length takeoff, the TORA is 12,799 feet, or 3901 meters.
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +entering the black runway area. In MSFS 2020, however, the taxiway meets the runway end at a 90-degree angle.
```suggestion
Be aware that some runways for which the airport 10-9 chart shows a zero-degree runway entry angle, MSFS 2020 has the taxiway aligned such that a 90-degree entry angle is 
required. One example of this is SBRF/Recife, Brazil. The marked area in the airport 10-9 chart below shows that the airplane can be aligned in the direction of takeoff before 
entering the black runway area. In MSFS 2020, however, the taxiway meets the runway end at a 90-degree angle.
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +    You can also round this off to the nearest ten degrees 260/10, which will probably be what ATIS would give you.
```suggestion
    You can also round this off to the nearest ten degrees, 260/10, which will probably be what ATIS would give you.
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +intersections (where a 90-degree entry angle would apply) are listed in the Additional Runway Information section.
```suggestion
This airport’s 10-9 chart has all the information on one chart. This is an example where both runways have a 180-degree entry angle; that is, the airplane must use the runway 
to taxi to the runway end and then turn around to use the full runway length for takeoff. TORA values for the full runway length as well as from the taxiway 
intersections (where a 90-degree entry angle would apply) are listed in the Additional Runway Information section.
```

2024-06-29 08:36 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +to magnetic North for LOWI.
```suggestion
For LOWI, the magnetic variation is 4 degrees East. When the magnetic variation is to the East, subtract the variation from the true wind value to determine winds referenced to the 
magnetic North. If the winds are 240/10 true from the METAR, adjust it to 236/10 when entering it into the takeoff performance calculator. 

Since the magnetic variation is only 4 degrees and winds are normally rounded to the nearest ten degrees, you can also just skip converting the wind reference from true North 
to magnetic North for LOWI.
```

2024-06-29 08:37 UTC, Sleinmaster commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +to magnetic North for LOWI.
```suggestion
to magnetic North for LOWI.

*[TORA]: Take-Off Run Available
```

2024-06-29 13:21 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- This is the magnetic direction of the runway. It will be entered automatically after entering the runway number.
To be consistent, should the text "entered automatically" be changed to "filled automatically" in the other instances as well?

2024-06-29 13:24 UTC, donstim commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +to magnetic North for LOWI.
Also, the "e" in "slope" is missing in line 70.

2024-06-29 13:29 UTC, donstim commented
Should remove the waiting on a32nx pr label

2024-06-29 13:30 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- This is the magnetic direction of the runway. It will be entered automatically after entering the runway number.
You're right, I changed the other ones in my suggestions as well.
It's mainly to not have two entered/entering straight after euch other.

2024-06-29 17:23 UTC, donstim requested changes
Otherwise all suggested edits LGTM

2024-06-29 17:23 UTC, donstim commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- This is the magnetic direction of the runway. It will be entered automatically after entering the runway number.
Suggested change: Replace "This is the magnetic direction of the runway" with "This is the direction of the runway with respect to magnetic North" (or "referenced to magnetic North") or similar.

2024-06-29 17:23 UTC, donstim commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +The magnetic variation for SBRF is 21 degrees West. For a magnetic variation in the West direction, add the magnetic variation to the true wind direction number to get the
"to the wind direction referenced to true North"

2024-06-29 17:23 UTC, donstim commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +magnetic wind direction. For example, if the winds are 240/10 from the METAR, then input 261/10 into the takeoff calculator (240+21).
"wind direction referenced to magnetic North"

2024-06-29 17:46 UTC, Sleinmaster requested changes

2024-06-29 17:46 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    Unfortunately, A320neo performance data for FLEX temp performance calculator alongside other various tools are not publicly available and are guarded by Airbus.
```suggestion
    Unfortunately, it is not yet available on the stable version.
```

It seems strange to me to write that there's no perf calculator in the stable version because the data is not available and at the same time we have a calculator in Dev.

2024-06-29 17:46 UTC, Sleinmaster commented on docs/pilots-corner/beginner-guide/preparing-mcdu.md
> +    clicking the LSK next to the V-Speed you want to calculate.
```suggestion
    V-Speeds are normally calculated by a company EFB or other tools. This feature is not yet available in the stable version.
    Instead you can simply click the LSK next to the V-Speed you want to calculate, to get V-Speeds from a simplified calculation.
```

2024-06-30 10:48 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/flypados3/performance.md
> +- This is the magnetic direction of the runway. It will be entered automatically after entering the runway number.
modified Slein's suggest to accommodate the 2nd option here.

2024-06-30 12:15 UTC, Valastiri commented on docs/pilots-corner/advanced-guides/flight-planning/takeoff-perf-calc.md
> +to magnetic North for LOWI.
noted and fixed

2024-06-30 13:43 UTC, merged