refactor(dev corner): Improve template & information in QA Process page
flybywiresim/docs pull request #998
Opened 2024-08-23 17:54 UTC by alepouna

## Summary

Changes to the wording & display in the PR template, improve readability and information found on the QA template.
Additionally, I added descriptions and details on some sections of the template for better detail as I've had questions regarding these sections.

### Location

/dev-corner/qa-process

2024-08-26 06:16 UTC, Sleinmaster requested changes

2024-08-26 06:16 UTC, Sleinmaster commented on docs/dev-corner/qa-process.md
> +    You may notice of the section for "Awaiting Actions", this section typically means the PR has been approved and is waiting to be merged. You do not have to test these PRs as they will find their
```suggestion
    You may notice of the section for "Awaiting Actions", this section typically means the PR has been approved and is waiting to be merged. You do not have to test these PRs as they will find their way to the development version of the aircraft shortly.
```

2024-08-26 06:16 UTC, Sleinmaster commented on docs/dev-corner/qa-process.md
> +Multiple tests in PRs are always welcome, and so it is good practice if you are starting a test on a certain PR to announce it on the Discord "quality-assurance" channel so that QA team is aware of p
```suggestion
Multiple tests in PRs are always welcome. It is still good practice to announce it on the Discord "quality-assurance" channel  , if you are starting a test on a certain PR, so that the QA team is aware of progress in testing.<br/>
```

2024-08-26 06:16 UTC, Sleinmaster commented on docs/dev-corner/qa-process.md
> +This section should be filled with details about your report. Please ensure this section is unaltared as our GitHub action read this area. This section is required.
```suggestion
This section should be filled with details about your report. Please ensure this section is unaltered as our GitHub action read this area. This section is required.
```

2024-08-26 06:16 UTC, Sleinmaster commented on docs/dev-corner/qa-process.md
> +Fill this section with details about the testing process. Though there isn't a specific format to use, it's recommend to include a list of each task (as described in the PR testing instructions) and
```suggestion
Fill this section with details about the testing process. Though there isn't a specific format to use, it's recommended to include a list of each task (as described in the PR testing instructions) and a note of any part that failed to pass. Common information, such as how you downloaded the PR or if your community folder was empty, should not be included in this section. 
```

2024-08-26 12:10 UTC, Sleinmaster requested changes

2024-08-26 12:10 UTC, Sleinmaster commented on docs/dev-corner/qa-process.md
> +Multiple tests in PRs are always welcome. It is still good practice to announce it on the Discord "quality-assurance" channel  , if you are starting a test on a certain PR, so that the QA team is awa
Something gone wrong with the spaces.
```suggestion
Multiple tests in PRs are always welcome. It is still good practice to announce it on the Discord "quality-assurance" channel, if you are starting a test on a certain PR, so that the QA team is aware of progress in testing.<br/>
```

2024-08-26 20:10 UTC, Valastiri requested changes
Changes :)

2024-08-26 20:10 UTC, Valastiri commented on docs/dev-corner/qa-process.md
> +    Text wrapped with `<!-- -->` (a.k.a. html comments) in the template will not be visible on your report. You may remove these comments as long as the required one at the top of the report.
```suggestion
    Text wrapped with `<!-- -->` (a.k.a. html comments) in the template will not be visible on your report. You may remove these comments except for the required one at the top of the report. 
```

Seems like just a grammatical error here.

2024-08-26 20:10 UTC, Valastiri commented on docs/dev-corner/qa-process.md
> +!!! warning ""
I would suggest adding in a "no title" admon that indicates this is a required section at the top of the copy since it's placed haphazardly in this section. Just to standardize. 

### Example Admon

```
!!! danger ""
	This section is required.
```
Copy would go below this admonition.

I would suggest a `!!! warning` admonition for the other sections.

### Reasonings

I would structure much more nicely in a readability manner that sections:

- Required would start at the top below the header with "Section is Required" admonition.
- Not Required/May be omitted has an admonition reading "Section may be Omitted"

2024-08-26 20:10 UTC, Valastiri commented on docs/dev-corner/qa-process.md
> +You can ommit this section if no negatives are found.
```suggestion
You can omit this section if no negatives are found.
```
This is spelled wrong in both the template and in this PR

2024-08-26 20:10 UTC, Valastiri commented on docs/dev-corner/qa-process.md
> +Any notes you may have, the positives in the PR, and anything extra you would like to note for your report. You can ommit this section.
```suggestion
Any notes you may have, the positives in the PR, and anything extra you would like to note for your report. You can omit this section.
```
This is spelled wrong in both the template and in this PR

2024-08-26 20:10 UTC, Valastiri commented on docs/dev-corner/qa-process.md
> +If you have any media to be included in the report, make sure to include them in this section. Images, videos, YouTube links or Streamable links are welcome. Please ensure externally linked media is
```suggestion
If you have any media to be included in the report, make sure to include them in this section. Images, videos, YouTube links or Streamable links are welcome. Please ensure externally linked media is unlisted/public and available for at least 4 weeks from the date you post the report.
```

2024-08-26 20:10 UTC, Valastiri commented on docs/dev-corner/qa-process.md
> +In general, to maintain your QA Team status, a minimum of one test every few weeks is required. You can message a QA Team lead on Discord if you need to take a break from testing to retain your statu
```suggestion
In general, to maintain your QA Team status, a minimum of one test every few weeks is required. You can message a QA Team lead on Discord if you need to take a break from testing to retain your status, if you are not able to submit any test reports for an extended period of time.
```

2024-08-26 20:26 UTC, alepouna commented on docs/dev-corner/qa-process.md
> +!!! warning ""
Good idea. Will add.

2024-08-26 21:27 UTC, alepouna commented on docs/dev-corner/qa-process.md
> +!!! warning ""
```suggestion
!!! tip ""
```

Thoughts on using a more informative "tip" style theme for this annotation?

2024-08-26 21:27 UTC, alepouna commented on docs/dev-corner/qa-process.md
> +!!! warning ""
```suggestion
!!! tip ""
```

Same as above.

2024-08-26 21:27 UTC, alepouna commented on docs/dev-corner/qa-process.md
> +!!! warning ""
```suggestion
!!! tip ""
```
Same as above.

2024-08-27 17:36 UTC, Sleinmaster reviewed
One more, otherwise lgmt

2024-08-27 17:36 UTC, Sleinmaster commented on docs/dev-corner/qa-process.md
> +    You may notice of the section for "Awaiting Actions", this section typically means the PR has been approved and is waiting to be merged. You do not have to test these PRs as they will find their
```suggestion
    You may take notice of the section for "Awaiting Actions", this section typically means the PR has been approved and is waiting to be merged. You do not have to test these PRs, as they will find their way to the development version of the aircraft shortly.
```

2024-08-28 08:11 UTC, Valastiri approved these changes

2024-08-28 08:12 UTC, merged