docs: Updated GSX Integration Docs to reflect current implementation
flybywiresim/docs pull request #999
Opened 2024-08-26 18:42 UTC by JasonO99

Fixes #934 

## Summary
This PR updates the GSX Integration Documentation to better reflect changes made in recent PR's, and some other tweaks for typos etc.

- Corrected typo at the start of the Overview page
- Changed the hero image on the Overview page to something better to reflect the nature of this area of docs 
- Updated images to show the EFB page for the Payload and Fuel doc pages
- Updated Refuelling page to reflect the changes made in https://github.com/flybywiresim/aircraft/pull/8543
- Removed the information that states we offer the GSX Chocks and Cones feature as enabled in the included GSX profile, as this is no longer the case as of https://github.com/flybywiresim/aircraft/pull/8405
- Updated the GSX Aircraft Profile window to reflect the current default configuration also updated in the above PR.

### Location
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/gsxintegration/

Discord username (if different from GitHub): jason_91

2024-08-26 20:19 UTC, Valastiri reviewed
All is generally well :) As indicated in Discord let's look at the images before merging this. Appreciate the update!

2024-08-26 20:19 UTC, Valastiri commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +      - Ensure you have syncronised your required fuel with your Simbrief flight plan, or manually adjusted the slider to set how much fuel you require.
```suggestion
      - Ensure you have synchronised your required fuel with your Simbrief flight plan, or manually adjust the slider to set how much fuel you require.
```

2024-09-03 09:39 UTC, Sleinmaster requested changes

2024-09-03 09:39 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +Much of the refuelling process between the A32NX and GSX is automated, however some input is required from the user to set the fuel and initiate refuelling.
```suggestion
Much of the refuelling process between the A32NX and GSX is automated; However some input is required from the user to set the fuel and initiate refuelling.
```

2024-09-03 09:39 UTC, Sleinmaster commented on docs/fbw-a32nx/feature-guides/gsxintegration/fuel.md
> +      - Ensure you have synchronised your required fuel with your Simbrief flight plan, or manually adjust the slider to set how much fuel you require.
```suggestion
      - Ensure you have synchronised your required fuel with your SimBrief flight plan, or manually adjust the slider to set how much fuel you require.
```

2024-09-05 02:14 UTC, Valastiri commented
LGTM -- sleins review seems handled will merge thanks !

2024-09-05 02:15 UTC, merged